### ISSUE TITLE
parse failed: template: shortcodes/admonition.html:3: function "merge" not defined

### ISSUE THREAD

**Issue by agouny** [dillonzq/LoveIt#10]
Trying to use LoveIt and getting the below error when running hugo either locally or via netlify:

`Error: "/home/[...]/themes/LoveIt/layouts/shortcodes/admonition.html:3:1": parse failed: template: shortcodes/admonition.html:3: function "merge" not defined`

Haven't been able to find any pointers so far so raising an issue, thanks for your help.

**Comment by agouny** [comment]
hugo version 0.55.6+really0.54.0-1 (Debian buster)

**Comment by Programazing** [comment]
I'm having the same issue.

**Comment by Programazing** [comment]
@agouny Update to a newer version of Hugo

**Comment by shaneyost** [comment]
Running into same issue. I've installed the latest hugo

**Comment by idrusfachr** [comment]
+1 got same issue. hugo version 0.63.2 (newest)

**Comment by dillonzq** [comment]
https://github.com/gcushen/hugo-academic/issues/1464
maybe the same issue?

**Comment by idrusfachr** [comment]
Just share what happened on me. Maybe still don't answer the problem. I got this error twice when deploying on netlify. What i did to encounter this error is nothing. Literally I didn't make any changes on the file pointed on error log. I just edited another files (that not related to the issue), add new post, publish locally (I'm using R blogdown, fyi) to check if everything is work fine, then I commit & push the changes to my repo. and the deployment success. 

It happened twice on me and what can i suggest to you so far is just try to redeploy your site again.

**Comment by dillonzq** [comment]
@idrusfachr 
Which version of Hugo on Netlify are you using?
The demo site of the theme is also deployed on Netlify.

**Comment by idrusfachr** [comment]
I am using Hugo 0.63.2. And now is already running.

**Comment by rocketdonut** [comment]
Same issue here. Using v0.64.1/extended.

**Comment by rocketdonut** [comment]
Tried again by adding a netlify.toml in my root directory with my local version of hugo and everything is running smoothly.

```
[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.64.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
```

**Comment by he-y** [comment]
> Tried again by adding a netlify.toml in my root directory with my local version of hugo and everything is running smoothly.
> 
> ```
> [build]
>   publish = "public"
>   command = "hugo"
> 
> [context.production.environment]
>   HUGO_VERSION = "0.64.1"
>   HUGO_ENV = "production"
>   HUGO_ENABLEGITINFO = "true"
> ```

Tired but failed.
