### ISSUE TITLE
关于渲染页面时生产环境命令的建议

### ISSUE THREAD

**Issue by gears233** [dillonzq/LoveIt#103]
最近看了下Hugo的命令文档以及其他人制作的一些主题模板，Hugo 本身有生产环境方面的参数；而作者建议使用的命令是 HUGO_ENV=production hugo --gc --minify 。

建议作者考虑将模板内layouts文件夹下面的几个 html 页面内的 (getenv "HUGO_ENV") "production"  替换为 hugo.Environment "production" 

这样子有几个好处：生成 public 文件夹时的 hugo 命令只需要输入  hugo  --gc --minify即可，因为默认就是生产环境；而本地预览的时候需要输入 hugo server -D --environment production；另外就是 
HUGO_ENV=production hugo --gc --minify 这个在bash下可以执行，但是像 powershell 就不能识别了。

**Comment by pavo976** [comment]
https://translate.google.com/

Предлагаю начать писать на английском ;-)

**Comment by dillonzq** [comment]
Hi, @gears233 
Thanks for your suggestion!
It has been improved in #105.
