### ISSUE TITLE
主题 helloworld 入门失败，求帮助

### ISSUE THREAD

**Issue by ringlog** [dillonzq/LoveIt#109]
很喜欢这个主题，但是在使用上遇到不少困难。

➜  001Blog hugo new site testblog
➜  001Blog cd testblog
➜  testblog git init
➜  testblog git:(master) ✗ git submodule add https://github.com/dillonzq/LoveIt.git themes/LoveIt
➜  testblog git:(master) ✗ cp -R themes/LoveIt/exampleSite/ .
按照上面步骤，config.toml已经配置成LoveIt主题，并准备好样例站点内容。

启动报错：
`➜  testblog git:(master) ✗ hugo server
Error: module "LoveIt" not found; either add it as a Hugo Module or store it in "/Users/louis/CloudStation/001Blog".: module does not exist`

将文件夹重命名成LoveIt，并改动主题目录的配置为：
`# 主题目录
themesDir = ".."`

启动后报错：
`➜  LoveIt git:(master) ✗ hugo server
Building sites … ERROR 2020/03/04 11:15:29 Failed to read Git log: fatal: your current branch 'master' does not have any commits yet
Built in 26 ms
Error: Error building site: "/Users/louis/001Blog/LoveIt/content/posts/Basic-Markdown-Preview.zh.md:77:1": failed to extract shortcode: template for shortcode "admonition" not found`

代码我不会改，就把报错的文件删掉”content/posts/Basic-Markdown-Preview.zh.md“后再启动，报另外错误：
![image](https://user-images.githubusercontent.com/3939556/75841918-e4872480-5e09-11ea-9fed-69486bcb14c3.png)

至此卡主，以上折腾了好几个小时，挺打击使用的，请楼主一定帮忙我们小散哈

> ➜  testblog git:(master) ✗ tree .
.
├── archetypes
│   └── default.md
├── config
│   └── css
│       ├── _custom.scss
│       └── _override.scss
├── config.toml
├── content
│   ├── about.en.md
│   ├── about.zh.md
│   └── posts
│       ├── Basic-Markdown-Preview.zh.md
│       ├── documentation.en.md
│       ├── documentation.zh.md
│       ├── emoji-support.en.md
│       ├── markdown-syntax.en.md
│       ├── placeholder-text.en.md
│       ├── rich-content.en.md
│       ├── test-mermaid.zh.md
│       └── test.zh.md
├── data
├── layouts
├── static
│   ├── android-chrome-192x192.png
│   ├── android-chrome-512x512.png
│   ├── apple-touch-icon.png
│   ├── browserconfig.xml
│   ├── favicon-16x16.png
│   ├── favicon-32x32.png
│   ├── favicon.ico
│   ├── images
│   │   ├── Apple-Devices-Preview.png
│   │   ├── avatar.png
│   │   ├── emoji.jpg
│   │   ├── hugo.png
│   │   └── markdown.png
│   ├── logo.png
│   ├── mstile-150x150.png
│   ├── safari-pinned-tab.svg
│   └── site.webmanifest
└── themes
    └── LoveIt
        ├── LICENSE
        ├── README.md
        ├── README.zh.md
        ├── archetypes
        │   └── default.md
        ├── assets
        │   ├── css
        │   │   ├── _core
        │   │   │   ├── _base.scss
        │   │   │   ├── _layout.scss
        │   │   │   ├── _media.scss
        │   │   │   └── _normalize.scss
        │   │   ├── _page
        │   │   │   ├── _404.scss
        │   │   │   ├── _archive.scss
        │   │   │   ├── _home.scss
        │   │   │   ├── _index.scss
        │   │   │   ├── _single.scss
        │   │   │   └── _special.scss
...

提供几个环境信息：
`➜  ~ hugo version
Hugo Static Site Generator v0.60.1/extended darwin/amd64 BuildDate: unknown
➜  ~ go version
go version go1.13.4 darwin/amd64
`

**Comment by ZhaoqiangCn** [comment]
你好， 可以参考我的文章，当时我用的是EVEN主题，现在已经迁移到LOVEIT了，但是部署的步骤都差不多，还有B站视频参考链接。
https://www.nashome.cn/post/hugo-github-actions/

**Comment by dillonzq** [comment]
哈喽, @ringlog 非常感谢使用这个主题！
[完整的主题文档](https://hugoloveit.com/zh-cn/categories/documentation/) 刚刚上线了，可以参考一下，还有问题的话可以再留言.

**Comment by Kudoyafka** [comment]
问题是在这个路径没找到这个主题。我按照doc的路径也找不到默认的themes文件夹。如果放在默认的themes/LoveIt（像题主这样），你可以直接用# comment掉themesDir，他会默认在默认路径里找到的。
