### ISSUE TITLE
关于多语言支持的问题

### ISSUE THREAD

**Issue by gears233** [dillonzq/LoveIt#112]
看到作者将原先英语和中文的配置合并到一处了，但是不知道什么原因如果默认语言改成 zh-CN会出错，然后我把config.toml内所有的CN改为小写cn就正常了。
另外想请问下，如果仅仅想生成仅中文网站，之前的版本我是直接注释掉config.toml中切换语言的选项的，另外注释掉后相关的切换按钮也一起消失了，现在的版本想实现这个效果的话应该如何做？

```
#  [[menu.main]]
#    identifier = "en"
#    pre = '<i class="fas fa-language fa-fw"></i>'
#    name = ""
#    title = "English"
#    url = ""
#    weight = 5
```

**Comment by dillonzq** [comment]
哈喽, @gears233 
不带多语言的网站设置可以参考 [主题文档](https://hugoloveit.com/zh-cn/theme-documentation-basics/#site-configuration).
