### ISSUE TITLE
资源加载不太对劲.

### ISSUE THREAD

**Issue by yangzhaoyunfei** [dillonzq/LoveIt#121]
https://yangzhaoyunfei.github.io/
最新版, 前端也看不太懂, 求问大佬, 咋回事啊.
<img width="1133" alt="Snipaste_2020-03-09_10-50-12" src="https://user-images.githubusercontent.com/23518028/76178997-52f62900-61f4-11ea-862b-b7e3b47ff623.png">

**Comment by yangzhaoyunfei** [comment]
本地预览是没有问题的.

**Comment by dillonzq** [comment]
哈喽, @yangzhaoyunfei 
你有没有对生成的资源文件再次进行 minify?

**Comment by dillonzq** [comment]
你的问题类似于 https://discourse.gohugo.io/t/failed-to-find-a-valid-digest-in-the-integrity/20361/4

**Comment by yangzhaoyunfei** [comment]
> 你的问题类似于 https://discourse.gohugo.io/t/failed-to-find-a-valid-digest-in-the-integrity/20361/4

minify我没有用过. 一直是默认行为, 应该不是这个问题.
我之前用的portable git, 没办法配置换行符. 每次commit是会替换到我的换行符.
我换了install git, 配置了不替换换行符就好了.
看来是这个替换换行符改变了问价的hash.
