### ISSUE TITLE
按返回键时标题显示错误

### ISSUE THREAD

**Issue by Kudoyafka** [dillonzq/LoveIt#128]
在example site在文章按返回键的时候会出现问题。另外试了试从文章点完tag之类的再回来文章标题也会显示错误，看起来像是动画加载了一半就停住了。
平台是iPad Pro的Safari，暂时还没在电脑端试过。
手机没有相同的问题。

**Comment by Kudoyafka** [comment]
![B9976389-9372-40C9-9FA9-52C4997CAE27](https://user-images.githubusercontent.com/32047956/76244771-17b62300-6211-11ea-8e2f-f626346181f9.jpeg)
![DC0B7E88-D34E-46AD-A56E-FAC9E3590C3A](https://user-images.githubusercontent.com/32047956/76244772-184eb980-6211-11ea-89fd-c3dbeb6c6ce2.jpeg)
更新实例

**Comment by dillonzq** [comment]
哈喽, @Kudoyafka 
我在 iPad 上复现了这个问题，在 iPhone 上还未出现这种情况
但是这个问题看上去不是动画库的原因，大概率和 iOS Safari 本身的机制有关
