### ISSUE TITLE
Change show_in_homepage to exclude_from_homepage

### ISSUE THREAD

**Issue by nwneisen** [dillonzq/LoveIt#14]
When I list posts on my home page, I would expect them to be a list of all of my posts with the most recent being first. I think most people would expect this behavior. 

With the current behavior, only posts with `show_in_homepage` are shown.  I will have to go through all of my posts and add the `show_in_homepage` option and remember to add this to future posts. I think it would make more sense to reverse this logic and add all posts but exclude those with a specific option.

If there is concern about changing the behavior for people currently using the them, a new `home_mode` value could be created to allow for both behaviors.

**Comment by dillonzq** [comment]
Thanks for your advice. I would consider adding a `home_mode`.

**Comment by dillonzq** [comment]
Hi, @nwneisen 
improved in #74
