### ISSUE TITLE
图床图片在帖子显示问题

### ISSUE THREAD

**Issue by wangdongming007** [dillonzq/LoveIt#141]
1、我在帖子里引用了七牛存储的图片，在本地显示是加载七牛的图片，但博客仓库push上阿里云服务器运行时，发现七牛图片加载不了。本地的可以。是不是这个lazysizes.min.js加载不了呢？

2、文章的目录无法显示，是我使用姿势不对吗。[https://hugoloveit.com/zh-cn/theme-documentation-content/#1-%E5%86%85%E5%AE%B9%E7%BB%84%E7%BB%87](url)

**Comment by dillonzq** [comment]
哈喽, @wangdongming007 
1. lazysizes 不会影响图片加载，我个人网站上的图片也用了又拍云，你的问题可能和网络或者七牛云的设置有关
2. 文章目录需要在文章前置参数把 `toc` 设置 `true` 来开启

**Comment by wangdongming007** [comment]
经过测试
1）在mac上我发现https的图片可以加载显示，http的不行。而且和浏览器有关，chrome，http图片不能显示，https可以。Safari的http和https都可以。
2）在windows，chrome，http图片不能显示，https可以，edge的http图片不能显示，https可以。
但是我hexo的旧站，用Chrome，http和https都可以显示图片
晚点排查一下nginx看。
ps：这个主题做的很不错！
