### ISSUE TITLE
Problems with encoding special characters in json+ld (“invalid escape sequence”)

### ISSUE THREAD

**Issue by yangzhaoyunfei** [dillonzq/LoveIt#144]
@dillonzq  你好，我查看google 索引报告的时候, ,提示存在 ***无法解析的结构化数据
: 字符串中的转义序列无效***

如下列截图所示:
![image](https://user-images.githubusercontent.com/23518028/76549326-2f203500-64cb-11ea-87ad-178a54a6cdec.png)

 
<img width="1036" alt="转义字符错误2" src="https://user-images.githubusercontent.com/23518028/76550400-0d27b200-64cd-11ea-8958-ee940536f336.png">

<img width="837" alt="转义字符错误" src="https://user-images.githubusercontent.com/23518028/76550471-292b5380-64cd-11ea-98f9-4fd621da3e69.png">

具体的几处是:

转义前 | 转义后
------------ | -------------
' | \x27
& | \x26
\+ | \x2b

按谷歌的说法这种转义是非标准的
<img width="564" alt="转义字符错误4" src="https://user-images.githubusercontent.com/23518028/76550770-9e972400-64cd-11ea-8c05-7abeb6799887.png">

这导致发生错误的页面无法被展示在Google搜索结果页中，请问这个可以解决吗？

**Comment by dillonzq** [comment]
这个问题可能和 #78 重复, 并且 Hugo 论坛有类似的疑问
https://discourse.gohugo.io/t/problems-with-encoding-special-characters-in-json-ld-invalid-escape-sequence/3084/14
我会尽快解决这个问题
