### ISSUE TITLE
impossible to create any files in content folder

### ISSUE THREAD

**Issue by czegevarra** [dillonzq/LoveIt#145]
hi everybody!
I have got the situation: when I'm trying to create new post.md file in content folder, I recieve errors like this: 
`Building sites … panic: no source found, 0

goroutine 77 [running]:
github.com/gohugoio/hugo/hugolib.(*pagesCollector).addToBundle.func2(0xc0001f4588, 0x2, 0x5906f77)
        /private/tmp/hugo-20200204-62451-1g6w8m9/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/pages_capture.go:360 +0x2c7
github.com/gohugoio/hugo/hugolib.(*pagesCollector).addToBundle(0xc000916190, 0x5d583c0, 0xc0009307c0, 0x1, 0xc00092c840, 0xc0008ef860, 0x7e39b70)
        /private/tmp/hugo-20200204-62451-1g6w8m9/hugo-0.64.0/src/github.com/gohugoio/hugo/hugolib/pages_capture.go:395 +0x6b3
`

**Comment by czegevarra** [comment]
can you tell me please how can I resolve this problem?

**Comment by x1n5h3n** [comment]
I don't know if it's the same problem I faced. Mine was regarding git. I've resolved it creating a git directory on the root of blog repository (git init). Then just add the content (git add .) and commit (git commit -m "foo"). Hope this can resolve your problem

**Comment by dillonzq** [comment]
fixed in #271
