### ISSUE TITLE
Bad contents menu on mobile

### ISSUE THREAD

**Issue by x1n5h3n** [dillonzq/LoveIt#146]
An unwanted arrow is present on the top of the content menu of a post in mobile mode (tested in firefox on android)

**Comment by dillonzq** [comment]
Hi, @x1n5h3n 
Can you give a screenshot?

**Comment by x1n5h3n** [comment]
![Screenshot_20200314-150727](https://user-images.githubusercontent.com/17899389/76683609-6262e100-65fd-11ea-82fc-432005151527.jpg)

**Comment by dillonzq** [comment]
Hi, @x1n5h3n 
I have figured out the cause of this problem.
The unwanted arrow comes from the default style added by Firefox for the `summary` tag.
I will fix it right away.

**Comment by x1n5h3n** [comment]
thx for you work
