### ISSUE TITLE
Unwanted space added to first line of code

### ISSUE THREAD

**Issue by anup92k** [dillonzq/LoveIt#158]
Hello,
I've found that every first line of bash code start with a space.
For exemple, for the code :
```md
```bash
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.8 python3.8-dev python3.8-venv
```
(This code is followed by tree backquote but I don't know how to display them here...)

The result here :
![image](https://user-images.githubusercontent.com/51033013/76693507-a1794c80-6666-11ea-85b9-2ffdf57888e9.png)

When I add a new line the space does not show anymore.
![image](https://user-images.githubusercontent.com/51033013/76693516-ca014680-6666-11ea-8eed-7a9c10a672d6.png)
```md
```bash

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.8 python3.8-dev python3.8-venv
```

BTW : Thanks for this awsome theme !

**Comment by dillonzq** [comment]
Hi, @anup92k 
Which commit of the theme you used? And which device and browser you used for preview?

**Comment by anup92k** [comment]
Hi,
I'm using Hugo :
> Hugo Static Site Generator v0.67.0-7F1DA3EF windows/amd64 BuildDate: 2020-03-09T20:35:55Z

And LoveIT last version :
`git log`
> commit 9928d46a377de3e835ef849e9a5e3731f491192d (HEAD -> master, tag: v0.1.3, origin/master)
> Merge: ff4d2f2 ca13e7d
> Author: Dillon <dillonzq@outlook.com>
> Date:   Sat Mar 14 21:52:53 2020 +0800
> 
>     Merge pull request #153 from dillonzq/develop
> 
>     Release v0.1.3

`git status`
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> nothing to commit, working tree clean

For preview, I used Firefox 74.0 (64 bits) and olso Chrome Version 80.0.3987.132 (Build officiel) (64 bits)

I've upload my website with this theme a few hours ago. You can see it here : [link](https://www.scrample.xyz/installation-du-serveur-mqtt-mosquitto/)

I seams not to be related only on bash but also on non specified code
[see the large code starting with Unit](https://www.scrample.xyz/installation-du-serveur-mqtt-mosquitto/#systemd)

The YAML code seams fine but maybe it does not show that much because  of the indent of YAML : [exemple of YAML](https://www.scrample.xyz/installation-du-serveur-mqtt-mosquitto/#int%C3%A9gration-%C3%A0-home-assistant)

Let me know if you want more info.

Regards

**Comment by dillonzq** [comment]
Hi, @anup92k 
Maybe there is a problem with your configuration of the highlight part?
![image](https://user-images.githubusercontent.com/30786232/76750658-9be04b80-67b9-11ea-97b3-800a2b0b54a4.png)

Or maybe you should use hugo extended version?
![image](https://user-images.githubusercontent.com/30786232/76750790-ca5e2680-67b9-11ea-9487-524fea83224f.png)

**Comment by anup92k** [comment]
Hello,

My markup content does not have a lot of content just this :
```toml
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
```
So there is no reference of the highlight part.

When I make my content I use Windows for previous and use an Ubuntu server to compile the complete website. The website was build with hugo extended (not using extended causes compiling errors).

I may have found the problem with the help of the inspection tool of Google Chrome :
![Screenshot_53](https://user-images.githubusercontent.com/51033013/76797674-57ab7600-67ce-11ea-9a26-315d914aba03.png)  
When I disable the `padding: .2rem .4rem;`, it goes well as you can see.  
Re-enable it brings back the space :
![Screenshot_1](https://user-images.githubusercontent.com/51033013/76797823-a35e1f80-67ce-11ea-8bc8-3640e490b829.png)  
It refers to the line 4 of `/themes/LoveIt/assets/css/_partial/_single/_code.scss`.

I'm wondering now if it's an issue of if it's intentional. If it's an expected result please let me know.  
If it is I'm sorry for the inconvenience and thank you a lot for your help.

_I'm gonna try to put some highlight info to see if I can get rid of that._

**Comment by anup92k** [comment]
I tried to play with the parameters and got rid of the space by enable the code fences :

```toml
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
```
![image](https://user-images.githubusercontent.com/51033013/76799603-246ae600-67d2-11ea-9d8e-1213561e6ca1.png)

Set it to false re-cause the issue.

I'm gonna use these parameters from here.
If it's not an issue for you, you can close this case.

Again, thanks for your help.

**Comment by dillonzq** [comment]
@anup92k 
`noClasses = false` in `[markup.highlight]` is necessary configuration.
