### ISSUE TITLE
无法开启disqus

### ISSUE THREAD

**Issue by 404cn** [dillonzq/LoveIt#159]
已经添加了disqusShortName

在本地测试了一下  hugo server -e "production" 

Environment: "production"

但是还是没有评论

**Comment by dillonzq** [comment]
哈喽, @404cn 
从 v0.1.1 版本开始, disqus 和 gitalk 添加了 enable参数
![image](https://user-images.githubusercontent.com/30786232/76696430-89391a00-66c6-11ea-947b-f00f2348235d.png)

**Comment by 404cn** [comment]
我更新了最新的LoveIt主题并更新了config.toml为exampleSite的config.toml, 当我启动hugo server的时候

> Error: module "LoveIt" not found; either add it as a Hugo Module or store it in "/Users/liubo".: module does not exist

我尝试修改themesDir 为 "./themes",但是报错

<img width="861" alt="Screen Shot 2020-03-15 at 6 35 20 PM" src="https://user-images.githubusercontent.com/24653356/76699777-bfd55b80-66eb-11ea-9227-54bfa4a95c07.png">

这是我的[config file](https://github.com/404cn/blog/blob/master/config.toml)

**Comment by dillonzq** [comment]
@404cn 
你需要在配置文件中加入主题的版本号
![image](https://user-images.githubusercontent.com/30786232/76699859-5d308f80-66ec-11ea-8bff-0ba8ffb80308.png)
详见
https://hugoloveit.com/zh-cn/theme-documentation-basics/#site-configuration

**Comment by 404cn** [comment]
@dillonzq 
谢谢你的及时回复  😁

我之前搜索🔍️的时候也查到过这点.

可是我的配置文件中已经配置了版本号了, 我是直接复制示例网站的配置文件然后修改的.

**Comment by dillonzq** [comment]
@404cn 
可能配置文件路径不对？

**Comment by 404cn** [comment]
配置文件的路径应该是对的.

themesDir 没设置之前, 默认是 "../.." 报错的是找不到 module

设置为 "themes" 之后报错上面的不兼容更新什么的.

我再折腾折腾吧, 以前没折腾过这个, 不太熟悉. 哈哈.

不过还是谢谢啦 😎️

**Comment by 404cn** [comment]
把原来的全删了重新添加了submodule好了

**Comment by sfw222** [comment]
重新submodule是git submodule吗？我重新这样了，还是报错Error: module "LoveIt" not found，这个咋办？
