### ISSUE TITLE
config.toml update to include new Goldmark default

### ISSUE THREAD

**Issue by IllusiveMilkman** [dillonzq/LoveIt#16]
Please include the following to config.toml under the Example Site.

[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

Since Hugo 0.6.0 the default markdown now requires this to render HTML tags.  

As an example, look at the current Markdown syntax guide for LoveIt:
https://themes.gohugo.io//theme/LoveIt/post/markdown-syntax/

At present HTML is rendered with ```<!-- raw HTML omitted -->```  The above setting will rectify it, but ultimately it's your decision to include it or not.

**Comment by Programazing** [comment]
Added in Pull Request #29
