### ISSUE TITLE
gitalk does not display

### ISSUE THREAD

**Issue by x1n5h3n** [dillonzq/LoveIt#164]
I don't see anymore gitalk, does anyone face the same problem ?

**Comment by dillonzq** [comment]
@x1n5h3n 
![image](https://user-images.githubusercontent.com/30786232/76718622-50567f00-6772-11ea-8c9e-ee1f0a75f076.png)

**Comment by x1n5h3n** [comment]
thx ! I was missing the enable

**Comment by x1n5h3n** [comment]
but in the last version of the config.toml in exampleSite there is not an enable parameter for gitalk

**Comment by dillonzq** [comment]
@x1n5h3n 
Thanks for reminding. I will perfect the `config.toml` in exampleSite as soon as possible.
But you'd better refer to the [documentation](https://hugoloveit.com/theme-documentation-basics/#3-configuration) first than the `config.toml` in exampleSite.
