### ISSUE TITLE
后面能否添加大篇幅图片展示排版支持

### ISSUE THREAD

**Issue by zhijian-pro** [dillonzq/LoveIt#174]
如题,有时候希望展示摄影照片,大量照片如果用 md 排版很丑,所以希望有对图片的友好排版解决方案

**Comment by dillonzq** [comment]
@Anthony-Duan 
类似九宫格么？

**Comment by Anthony-Duan** [comment]
对的,九宫格,或者更适合展示图片的原型,我也不是很懂交互与前端,但是大致方向就是让摄影作品有更友好的方式展示

**Comment by shootheart** [comment]
+1有这个需求
