### ISSUE TITLE
font awesome icon spaces problem

### ISSUE THREAD

**Issue by Sharkigamers** [dillonzq/LoveIt#177]
There is a problem with local and production :
LOCAL :
![Capture du 2020-03-17 00-17-05](https://user-images.githubusercontent.com/49515579/76807474-c5fb3300-67e4-11ea-8ee0-a9d1dc5c42a6.png)

PROD : 
![Capture du 2020-03-17 00-17-31](https://user-images.githubusercontent.com/49515579/76807485-cabfe700-67e4-11ea-812c-2407de52a2c0.png)

it needs to have a space in production

**Comment by dillonzq** [comment]
Hi, @Sharkigamers 
I have confirmed the issue and it will be resolved soon.
