### ISSUE TITLE
style.scss transform error

### ISSUE THREAD

**Issue by yy77** [dillonzq/LoveIt#183]
On hugo version 0.67.1.

When try to build site using LoveIt theme, below error occurs.

**Error: Error building site: TOCSS: failed to transform "style.scss" (text/x-scss): resource "scss/css/style.template.scss_90197bdac482216ecaaaae0fb88517c1" not found in file cache**

Is there any other dependencies need to be installed first?

**Comment by microlong666** [comment]
Try installing hugo_extended instead. It's work.
https://github.com/gohugoio/hugo/releases
