### ISSUE TITLE
我在使用hugo命令构建静态页面时，报如下错误，这个应该怎么解决呢？

### ISSUE THREAD

**Issue by jiangliuhong** [dillonzq/LoveIt#186]
![image](https://user-images.githubusercontent.com/24851764/77024453-88a3ca80-69c9-11ea-8852-636f92b001e6.png)

**Comment by dillonzq** [comment]
和 #183 重复

**Comment by jiangliuhong** [comment]
我看了下 #183 ,好像也没写解决办法

**Comment by jiangliuhong** [comment]
我已经解决了。需要下载 hugo_extended_* 的文件
