### ISSUE TITLE
Content bundles featuredImage won't show on the homepage

### ISSUE THREAD

**Issue by AutomationD** [dillonzq/LoveIt#191]
When I use content bundle feature (with index.md) featured images on the homepage won't show.
Also, images in posts remain with relative path. It seems like if images would be sourced via permalinks that should work?

https://discourse.gohugo.io/t/relative-image-links-with-page-bundles-broken-on-main-page/18785/8

Thanks.

**Comment by dillonzq** [comment]
Hi， @AutomationD 
The theme does not yet support images in content bundles.

**Comment by dillonzq** [comment]
It will be fixed in #375
