### ISSUE TITLE
Not able to build a site locally

### ISSUE THREAD

**Issue by security-prince** [dillonzq/LoveIt#193]
Hi,
I am new to hugo and i am trying to follow this guide here https://gohugo.io/getting-started/quick-start/
and instead of the theme mentioned in the article i am trying to use the LoveIt theme but am getting the below error when i am trying to run `hugo server -D`:

```
$ hugo server -D
Building sites … ERROR 2020/03/22 11:41:10 

There are two possible situations that led to this error:
  1. You haven't copied the config.toml yet. See https://github.com/dillonzq/LoveIt#installation 
  2. You have an incompatible update. See https://github.com//dillonzq/LoveIt/blob/master/CHANGELOG.md 

有两种可能的情况会导致这个错误发生:
  1. 你还没有复制 config.toml 参考 https://github.com/dillonzq/LoveIt#installation 
  2. 你进行了一次不兼容的更新 参考 https://github.com//dillonzq/LoveIt/blob/master/CHANGELOG.md 

Built in 51 ms
Error: Error building site: logged 1 error(s)
```

**Comment by dillonzq** [comment]
Hi, @security-prince 
You need a special configuration config.toml:
https://hugoloveit.com/theme-documentation-basics/#basic-configuration
