### ISSUE TITLE
語法高亮有不正常空格

### ISSUE THREAD

**Issue by jkgtw** [dillonzq/LoveIt#194]
目前的 config.toml

[markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

會出現不正常的縮排空格（如下圖）

![sshot2020-03-22_15-28-18](https://user-images.githubusercontent.com/1110347/77244635-27425c80-6c52-11ea-9d66-65a433253f72.png)

如果把 lineNumbersInTable 改成 false 則會正常
但是行號會在 table 裡面

謝謝！

**Comment by dillonzq** [comment]
Fixed in #239
