### ISSUE TITLE
%!(EXTRA string=Text) in some text

### ISSUE THREAD

**Issue by Galco6** [dillonzq/LoveIt#197]
Hello,

When a build my blog I have some string errors like the ones in the image. Do you know what can be the error?

Thanks.

![imagen](https://user-images.githubusercontent.com/12474522/77536358-809dcc00-6e9c-11ea-907b-0c071bcbd5b9.png)

**Comment by ziobron** [comment]
I had the same issue and in my case, it was that I was missing some texts in my translation. They are updated sometimes with this theme update. Please take the newest English version from i18n and translate it from scratch.

**Comment by Galco6** [comment]
Thanks for the help @ziobron . Solved updating i18n files as you said.
