### ISSUE TITLE
怎么嵌入流程图呢

### ISSUE THREAD

**Issue by leaxoy** [dillonzq/LoveIt#20]
有没有一个比较详细的嵌入流程图的文档呢

**Comment by dillonzq** [comment]
@leaxoy 
最新会更新一下 exampleSite，里面会有使用流程图的文档，大致示例如下

```
{{< mermaid >}}
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
        +String beakColor
        +swim()
        +quack()
    }
    class Fish{
        -int sizeInFeet
        -canEat()
    }
    class Zebra{
        +bool is_wild
        +run()
    }
{{< /mermaid >}}
```

使用的是 [mermaidjs](https://mermaidjs.github.io/) 库

**Comment by leaxoy** [comment]
非常感谢！

**Comment by leaxoy** [comment]
另外这种办法的话，在Typora中是无法预览的， 有没有办法支持代码块的流程图呢 比如：
```
```mermaid
sequenceDiagram
    participant Publisher
    participant Broker
    participant Subscriber
    Publisher->>Broker: Publish
    Publisher->>Publisher: Delete(Msg)
    Broker->>Subscriber: Publish
    Broker->>Broker: Delete(Msg)
```
```

**Comment by dillonzq** [comment]
哈喽，@leaxoy
类似 Typora 这种代码块的流程图目前无法做到，因为当前 Hugo 对代码块的渲染结果还无法修改。
不过，Hugo 在 v0.62.0 中改用 `Goldmark` 支持了 Markdown Render Hooks，但是目前仅可以自定义链接和图片。
并且，这两种 Hook 在这个主题中已经用到了，将来有望支持代码块的 Hook，从而可以实现类似功能。

**Comment by dillonzq** [comment]
哈喽，@leaxoy 
这是 [mermaid 的文档](https://hugoloveit.com/zh-cn/theme-documentation-shortcodes/#mermaid).

**Comment by msdemt** [comment]
@dillonzq 
打扰下，嵌入是否需要额外的配置呢？

我使用exampleSite/content/posts/test.zh.md文件进行测试，流程图无法显示出来

还有一个问题，在exampleSite/content/posts/test.zh.md文件中的流程图上的图标需要切换下白天/夜间模式才能正常显示。

**Comment by mmfei** [comment]
@see https://github.com/dillonzq/LoveIt/pull/605
