### ISSUE TITLE
Provide a site param to hide the footer.

### ISSUE THREAD

**Issue by ankurkotwal** [dillonzq/LoveIt#209]
Hi,
It would be great if we could add a site param to hide the footer. I've coded a possible solution but since this is my first pull request, I thought I'd ask for a review at https://github.com/ankurkotwal/Hugo-LoveIt-Theme/commit/3ea53356fdf21adb6557f656960c7c6daa06e120 before submitting a PR. All comments welcome.

**Comment by ankurkotwal** [comment]
I ended up submitting a PR. Interested to get feedback, thanks!

**Comment by dillonzq** [comment]
@ankurkotwal Hi
I have added more configs to custom the footer. Of course you can hide it.
Thanks for your PR anyway ❤️

**Comment by ankurkotwal** [comment]
Thanks for adding the feature and for the feedback :)
