### ISSUE TITLE
Space after apostrophe

### ISSUE THREAD

**Issue by tlereste** [dillonzq/LoveIt#210]
I have a display problem with apostrophe as @cmpsoares91 said on issue #69 .
A space appears after each apostrophe a space.
After research this is due to a bug with Microsoft Yahei font : https://answers.microsoft.com/en-us/msoffice/forum/all/extra-font-added-after-apostrophe/78ba3986-d51f-45c7-beec-edf3b0715cdd

**Comment by vutruong99** [comment]
Hi @tlereste can you please tell me how to replace the font? I do not see the path to any font folder in LoveIt. Thank you very much.

**Comment by tlereste** [comment]
Hi @vutruong99 , if you forked the LoveIt theme, you can see my associated PR to do the fix. (into `assets/css/_variables.scss` file)

If not, you can override the **scss** by creating the file `config/css/_override.scss` in your root site folder.
The `_override.scss` must contain :  
```
html {
    font-family:-apple-system,BlinkMacSystemFont,PingFang SC,Microsoft Yahei UI,Segoe UI,Helvetica,Arial,sans-serif,Segoe UI Emoji !important;
}
```

**Comment by vutruong99** [comment]
![image](https://user-images.githubusercontent.com/43692044/79048217-b89b6200-7c45-11ea-8b96-fe752a96cf73.png)


Hey @tlereste thank you for replying so fast. Somehow I did not find your associated PR and I could not find the config folder in my root directory also. Is it possible that I used the wrong command when initializing hugo site? I did `hugo new site myNewSite`

**Comment by tlereste** [comment]
My PR is here : https://github.com/dillonzq/LoveIt/pull/211

Your hugo site is OK. Now you must manually create the folder `config/css` with file `_override.scss` to override the default **scss** configuration.

**Comment by vutruong99** [comment]
![image](https://user-images.githubusercontent.com/43692044/79048719-390f9200-7c49-11ea-8e70-493026a44be4.png)
I apologize for bothering you :( I think I added the UI to the code. Do I need to install the font anywhere? Thank you.

**Comment by tlereste** [comment]
No problem. You don't have to install the font. Have you rebuild the site after file update ? 🤔

**Comment by vutruong99** [comment]
Yeah I did rebuild a couple of times :(. Thank you so much anyways. :D :D

**Comment by tlereste** [comment]
Ok but sorry I have no others ideas...
You can check my personal website and compare with yours. I add `_override.scss` file like you and it works !

Here I my repo : https://github.com/tlereste/thibault-lereste-website
And here my website : https://thibault-lereste.fr

Have you tried to inspect your site css with your browser developer console and edit manually the css ? It works ?

**Comment by vutruong99** [comment]
I tweaked some lines in the variable.scss and it did not show any changes in my website. So I guess there is something wrong with that. I will take a look at your code for references. Thank you so much for your effort hehe 👯

**Comment by tlereste** [comment]
No problem. Keep me informed if you get there or not 😉

**Comment by vutruong99** [comment]
![image](https://user-images.githubusercontent.com/43692044/79051301-af1bf500-7c59-11ea-9a8a-2cc0e01bb8df.png)
I found out that this css is responsible for it but I cannot find it in the folder... Weird. I copied the config folder from your repo but still doesn't work. No worries Im just keeping y ou informed :D

**Comment by tlereste** [comment]
Nice 👍
