### ISSUE TITLE
设置defaultHiddenFromHomePage选项未生效

### ISSUE THREAD

**Issue by HStarrr** [dillonzq/LoveIt#215]
当在配置文件中设置defaultHiddenFromHomePage选项为true，并在文章中未添加hiddenFromHomePage属性时，该文章还是默认显示在首页上，感觉defaultHiddenFromHomePage未生效

**Comment by dillonzq** [comment]
0.2.0 版本配置修改了

**Comment by HStarrr** [comment]
是删除了这个功能吗？现在如果不让其显示在主页只能在文章内容中添加前置参数吗？

**Comment by dillonzq** [comment]
@HStarrr 全局配置移到 `page` 部分了
![image](https://user-images.githubusercontent.com/30786232/80912075-03078e80-8d6d-11ea-8f52-bf3e6e22bf9c.png)
https://hugoloveit.com/zh-cn/theme-documentation-basics/#site-configuration
前置参数不变

**Comment by HStarrr** [comment]
明白了，在说明中看见这个了，这个说明有歧义，把我带偏了😂
