### ISSUE TITLE
Set dark-theme as default theme for new users

### ISSUE THREAD

**Issue by Eliesemoule** [dillonzq/LoveIt#22]
Hello,

I want to know if it possible to set dark-theme as default theme for new users ? If yes, could please explain me how to do that.

Thanks

**Comment by jbfreels** [comment]
Not sure if this is the BEST way, but if you modify the logic in blog.js, you can swap it.  

```
$('body').toggleClass('light-theme');
isLight = !isLight;
window.localStorage && window.localStorage.setItem('theme', isLight ? 'dark' : 'light');
```

**Comment by Eliesemoule** [comment]
Hello,

Thank you for your reply. I just tested. Unfortunately it does not work. I still have the theme-light and can no longer switch to the dark-theme. Do you have another idea?

**Comment by jbfreels** [comment]
I'm sorry, I just tried to reproduce but I couldn't.  I gave up on the theme after having another issue.

**Comment by tfinardi** [comment]
> I want to know if it possible to set dark-theme as default theme for new users ? If yes, could please explain me how to do that.
> 

Hi @Eliesemoule,
if you really want this, you can just set the body class to "dark-theme", editing the file baseof.html in "themes/LoveIt/layouts/_default".

`<body class="dark-theme">
`

**Comment by dillonzq** [comment]
Hi, @Eliesemoule 
I would consider adding a config option `default_theme`.

**Comment by dillonzq** [comment]
Hi, @Eliesemoule
`defaultTheme` has been added to config file in #58.

**Comment by dillonzq** [comment]
Hi, everyone!
In #67, I have added `"auto"` config in `defaultTheme`, which detecting system dark mode to set site theme.
