### ISSUE TITLE
static目录应该放在哪里呢？网站不显示图片图标

### ISSUE THREAD

**Issue by xkerwin** [dillonzq/LoveIt#23]
我在本地调试正常后，push到github上发现网站的图标和图片都不显示！static目录应该放在哪里呢？请指教一下！在网上搜索很多都没解决方法

**Comment by xkerwin** [comment]
https://xkerwin.github.io

**Comment by 404cn** [comment]
blog/static

**Comment by hhaiyun** [comment]
放在hugo的根目录下

**Comment by whangh** [comment]
如果你使用了exampleSite/zh目录下的config.toml配置，可能是此处错误：
`staticDir = ["../static", "../../assets/others"]`
正确的应该是exampleSite/config.toml中的配置：
`staticDir = ["static", "../assets/others"]`

**Comment by xkerwin** [comment]
谢谢，这样编写后确实解决了问题！
