### ISSUE TITLE
全大写的分类标签显示异常

### ISSUE THREAD

**Issue by Jay-Young** [dillonzq/LoveIt#237]
如果分类是全大写的缩写名，只有首字母大写，而且每个字母之间有多余的空格：

![image](https://user-images.githubusercontent.com/8641055/79536412-99238f80-80b2-11ea-8250-9c4a860d42f6.png)

![image](https://user-images.githubusercontent.com/8641055/79535798-19e18c00-80b1-11ea-827c-f4323021d018.png)

查阅了 Hugo 的文档，好像和 humanize 这个函数有关，把和 categories 相关的 humanize 函数删除以后首页和文章页的分类都显示正常了。但是分类页面还是显示错误，删掉 humanize 反而只会显示全小写，保留 humanize 只显示首字母大写。

首页正常：
![image](https://user-images.githubusercontent.com/8641055/79536143-dfc4ba00-80b1-11ea-88d0-a7dd5af2fd36.png)

分类页面异常：
![image](https://user-images.githubusercontent.com/8641055/79536275-3e8a3380-80b2-11ea-82e2-5f73910df0e5.png)

请问下应该怎么解决？

**Comment by dillonzq** [comment]
#251 修复
