### ISSUE TITLE
lightgallery设置开启，没生效

### ISSUE THREAD

**Issue by linsage** [dillonzq/LoveIt#238]
文章配置
```
---
title: "xxx"
date: 2020-04-18T10:20:13+08:00
draft: false
lightgallery: true
---
```

**Comment by dillonzq** [comment]
参考一下最新的[文档](https://hugoloveit.com/theme-documentation-content/)

**Comment by linsage** [comment]
原来要用shortCode 的image才能开启lightgallery模式

**Comment by dillonzq** [comment]
@linsage ![Alt Text](/url/to/your/image "Title") 这种带标题的图片也支持

**Comment by linsage** [comment]
@dillonzq 👍可以，感谢

**Comment by yqchilde** [comment]
请问必须要在后面带标题吗，有没有其他的解决方案，我是从wp迁移过来，图片很多，必须带标题的话，改动挺费时间，现在发现不带标题是不支持的。
