### ISSUE TITLE
我直接修改了./assets/css/_variables.scss的一些值，但并不生效，这是怎么回事呢？

### ISSUE THREAD

**Issue by zhahuya** [dillonzq/LoveIt#243]
./assets/css/_variables.scss，修改背景颜色什么的，都不管用。

**Comment by zhahuya** [comment]
好了，使用 hugo_extended 就好了。

**Comment by CindyCyber** [comment]
> 好了，使用 hugo_extended 就好了。

你好，请问你怎么改的呢？我直接改的_variable.scss，改动之后没有生效呢？我试着在Chrome里用F12改，就有效果。但是改那几个scss文件都没效果不知道为啥。
