### ISSUE TITLE
提点建议：“所有文章”栏目所显示的文章数目可自定义。

### ISSUE THREAD

**Issue by zhahuya** [dillonzq/LoveIt#244]
1.现在主页的文章数量是可以自定义的，但我想“所有文章”这里也可以自定义，这样当我想看所有的文章的时候，我就可以将这里设置成很大的数，比如100而不需要翻页了。
2.个人意见：“引用”这个Markdown标签渲染出来的样式似乎有些惊人，感觉有些太醒目了。

**Comment by chenxuejian** [comment]
同求

**Comment by dillonzq** [comment]
两点都已经改进了，即将在 0.2.0 版本发布

**Comment by zhahuya** [comment]
> 两点都已经改进了，即将在 0.2.0 版本发布

感谢，这个项目的 commit 已成为我每天甜蜜的期待了，要注意身体……
