### ISSUE TITLE
Custom CSS changes not being picked up

### ISSUE THREAD

**Issue by Programazing** [dillonzq/LoveIt#25]
I added `assets/css/_custom.scss` to my website's directory and the theme doesn't seem to pick up on the contents of `_custom.scss`.

**Comment by hyde-stevenson** [comment]
I hve the same kind of behaviour. The style.min.css keeps the old values ...

**Comment by hyde-stevenson** [comment]
Even if I change the layout of the theme directly... I'm trying to figure out why :/

**Comment by Alextrapixel** [comment]
well, you need to install **hugo-extended** version to make your _custom.scss works.
hugo-extended version give support to Sass/SCSS
download from hugo releases [https://github.com/gohugoio/hugo/releases](https://github.com/gohugoio/hugo/releases)

**Comment by Programazing** [comment]
Thanks @Alextrapixel, that worked.

**Comment by micklynch** [comment]
Thanks @Alextrapixel , your comment solved it for me too.
