### ISSUE TITLE
Using mermaid on markdown

### ISSUE THREAD

**Issue by gyulkkajo** [dillonzq/LoveIt#26]
Hi!
First of all, thank you everything on this theme.

I found that drawing diagram by mermaid is not working. I checked mermaid syntax on other markdown editor but it works. It seems like that I missed something like configuration on config.toml or other configurations but couldn't find any options.

For double check, I show the script below:

\```mermaid
graph LR;
  A[Hard edge] -->|Link text| B(Round edge)
    B --> C{Decision}
    C -->|One| D[Result one]
    C -->|Two| E[Result two]
\```

Is there any option to enable mermaid plugin? or am I using it wrong?

**Comment by gyulkkajo** [comment]
I figured out myself.

set "diagram: true" on frontmatter and put mermaid syntax between "{{< diagram >}} ... {{< /diagram >}}"

**Comment by dillonzq** [comment]
Hi, @gyulkkajo 
Here is [mermaid docs](https://hugoloveit.com/theme-documentation-shortcodes/#mermaid).

**Comment by gyulkkajo** [comment]
> Hi, @gyulkkajo
> Here is [mermaid docs](https://hugoloveit.com/theme-documentation-shortcodes/#mermaid).

According to mermaid docs, it uses {{< mermaid >}}, not {{< diagram>}}".
