### ISSUE TITLE
[BUG] 在调试模式中无法访问主页“文档”页面

### ISSUE THREAD

**Issue by bao-wei** [dillonzq/LoveIt#289]
![image](https://user-images.githubusercontent.com/63962745/80608992-2f1fc880-8a6a-11ea-8939-daedf746ff4b.png)
这是我的前置信息，我在调试模式时，无法访问主页的文档页面，我在读了“主题文档-内容”后也没有找到要在前置信息中如何添加“文档”分类（下图）。
![image](https://user-images.githubusercontent.com/63962745/80609395-99d10400-8a6a-11ea-9299-544a9406bc28.png)
提示：
![image](https://user-images.githubusercontent.com/63962745/80609442-a48b9900-8a6a-11ea-925f-5d6ad3dd299e.png)

由于是小白新手，还请指点，谢谢作者提供如此美观的主题！

**Comment by dillonzq** [comment]
@bao-wei 菜单在 `config.toml` 中设置

**Comment by bao-wei** [comment]
> @bao-wei 菜单在 `config.toml` 中设置

![image](https://user-images.githubusercontent.com/63962745/80613606-12868f00-8a70-11ea-9906-3ab3eaebeb99.png)
请问我该如何将文章指向这个位置呢？我是不是需要在blog/posts目录下再创建一个categories文件夹，然后把文章放在这个路径下才可以呢？

**Comment by dillonzq** [comment]
@bao-wei 
文章的前置信息中:
![image](https://user-images.githubusercontent.com/30786232/80614533-241c6680-8a71-11ea-878f-28bcd9adb884.png)

**Comment by bao-wei** [comment]
非常感谢！！！
