### ISSUE TITLE
求助：请问作者“文档”中“摘要”中的特色图片前置参数格式怎么设置？我如图设置的无法显示，是我图片链接的问题吗？

### ISSUE THREAD

**Issue by bao-wei** [dillonzq/LoveIt#292]
请问特色图片前置参数格式怎么设置的？我这样设置无法显示：
![image](https://user-images.githubusercontent.com/63962745/80718536-db29e800-8b2c-11ea-9f23-e72e683a47ff.png)

(ps. 这个主题是真的赞👍👍👍)

**Comment by dillonzq** [comment]
@bao-wei 不要方括号

**Comment by bao-wei** [comment]
> @bao-wei 不要方括号

感谢大神！！！！
