### ISSUE TITLE
Search routing problem when baseUrl have subpath.

### ISSUE THREAD

**Issue by TyrangYang** [dillonzq/LoveIt#298]
### Describe the bug 描述你遇到的错误

I have deployed my Hugo site on an url with subpath: `<userName>.github.io/<porjectName>/` and enable Algolia search engine

The url of a search result should be:  `<userName>.github.io/<porjectName>/<resultTitle>/`

But actually link to `<userName>.github.io/<resultTitle>/` that the subpath is ignored

我将我的网页放到了`<userName>.github.io/<porjectName>/`并且启用了algolia。搜索的结果的url应该是 `<userName>.github.io/<porjectName>/<resultTitle>/` 但实际却是`<userName>.github.io/<resultTitle>/`

### Expected behavior 期待的行为

I look all records in dashboard of Algolia. It seems that the field `uri` used as a relative url for routing. To make my baseURL whose include subpath work properly at beginning, I add `canonifyURLs = true` in config file which ensure all urls are canonicalized by baseURL.

Can `canonifyURLs`  be added in search configuration?

我观察了一下algolia里的records。看起来uri被直接用作相对路径了。之前为了使带有子路径的baseURL正常运行。我在设置文件里添加了`canonifyURLs = true` ，相当于关闭了相对路径而直接使用baseURL。

是否在搜索过程中也可以添加进去绝对路径呢？
### Build Environment 构建环境

- OS: [macOS]
- Theme version[0.2.0]
- Hugo version [v0.69.0/extended]

**Comment by TyrangYang** [comment]
BTW, My repo link: https://github.com/TyrangYang/TyrangYang_blog

**Comment by dillonzq** [comment]
@TyrangYang 哈喽
你在什么地方需要用到 `canonifyURLs = true` 这个设置

**Comment by TyrangYang** [comment]
Hi,
我config.toml里用了。因为我的baseURL是<name>.github.io/<repoName>/。如果不用这个设置，像是点击header里的categories他会route到<name>.github.io/categories而不是<name>.github.io/<repoName>/categories下.

我想他应该是直接用了相对路径，像是`<a href='/<result>'></a>`这样。

可是search会出现类似的情况。点击一个search的结果会route到<name>.github.io/<result>上，而不是<name>.github.io/<repoName>/<result>

我不知道这个应该怎么设置了，我希望是如果设置canonifyURL也可以让search也使用上绝对路径

**Comment by dipperkun** [comment]
我也遇到类似的问题!我的url中不包含语言的，但是搜索出来的url却包含语言。例如
xxx.com/test/
搜索出来的路径为
xxx.com/zh-cn/test

**Comment by dillonzq** [comment]
@TyrangYang 这个主题对于路径使用所遵循的原则是尽可能不带域名，这是比较常规的做法。只有在 SEO 和 RSS 等地方用到了带域名的路径。
关于你的问题，我的建议是不设置canonifyURL，header 的 menu 中出现的路径错误问题是 Hugo 本身的一个 BUG，https://github.com/gohugoio/hugo/issues/4995，
应该在未来的某个版本会解决
目前我建议是在 menu 的 url 设置中使用完整的路径

**Comment by dillonzq** [comment]
> 我也遇到类似的问题!我的url中不包含语言的，但是搜索出来的url却包含语言。例如
> xxx.com/test/
> 搜索出来的路径为
> xxx.com/zh-cn/test

@dipperkun 你可以更具体描述你的问题吗，或者新建一个 issue，你的问题看上去是 `config.toml` 中多语言设置的问题

**Comment by dillonzq** [comment]
@TyrangYang 下个版本会新增一个参数来配置 index.json 中使用 absURL
