### ISSUE TITLE
Subtitle for posts

### ISSUE THREAD

**Issue by Nhoya** [dillonzq/LoveIt#3]
Hi,
first of all thanks for your work, I really appreciate this theme, I was wondering if would be ok to add subtitle to posts

**Comment by dillonzq** [comment]
Hi, @Nhoya 
Could you give more explanation for your suggestion?

**Comment by Nhoya** [comment]
For example 
![immagine](https://user-images.githubusercontent.com/7293260/74771999-7c740280-528f-11ea-928d-f8e371fa0273.png) here the second line is the subtitle

**Comment by dillonzq** [comment]
Hi, @Nhoya
Thanks for your suggestion.
It has been added to the roadmap.
