### ISSUE TITLE
[BUG] Javascript error when search config is disabled or missing

### ISSUE THREAD

**Issue by DaveA-W** [dillonzq/LoveIt#304]
Setting config.toml in version 0.2.4 with:
```
  # Search config
  [params.search]
    enable = false
```
results in a javascript error on page load:
![image](https://user-images.githubusercontent.com/6415842/80858753-f06a5800-8c8d-11ea-9246-d0de50c4fc10.png)

This prevents other modules like typeIt initialising, and also occurs if you omit the [params.search] section entirely.

Fix is to change the start of initSearch() within theme.js:
```
    initSearch() {
        const searchConfig = this.config.search;
        if (!searchConfig) return; // exit if disabled or missing
        if (!searchConfig.maxResultLength) searchConfig.maxResultLength = 10;
```

Happy to submit a PR to fix, but I'm not sure what you are using to minimise your `assets/js/theme.min.js`

**Comment by dillonzq** [comment]
@DaveA-W Thanks. I would fix it.

**Comment by matteototaro** [comment]
Same here, typeIt doesn't work anymore and the images in the posts are not centered.  As far as I know these are the problems that I encountered. Don't know if the problem with the images it's my fault ahah, I'm not an expert.

Anyway thank you so much @dillonzq  for the theme! it's amazing.

**Comment by dillonzq** [comment]
@matteototaro Thanks for your feedback.
1. Could you make a new issue to describing your problem about TypeIt?
2. Images without a title using Markdown syntax are not centered for compatibility with **inline images**.
   You can add a title for your image or use `image` shortcode or use `style` shortcode to make images centered.
   https://hugoloveit.com/theme-documentation-extended-shortcodes
