### ISSUE TITLE
[BUG] 搜索功能在不同语言下对about.md页面显示有误

### ISSUE THREAD

**Issue by microlong666** [dillonzq/LoveIt#305]
在中文搜索 **关于** 能显示关于页面 (about.zh-cn.md)

![批注 2020-05-02 154008](https://user-images.githubusercontent.com/55701850/80858707-a08b9100-8c8d-11ea-87ff-5b21c37653e7.png)

But 在英文搜索 **about** 显示无结果 (about.en.md)

![批注 2020-05-02 153618](https://user-images.githubusercontent.com/55701850/80858724-b8631500-8c8d-11ea-962d-c9b7115d42fe.png)

> 问题仅出现在lunr，algolia亲测没问题，两个about.md文章配置一致

### Build Environment 构建环境

- OS: [Windows 10]
- Theme version/commit [0.2.4, e3d774f]
- Search engine [Lunr.js]
- Hugo version [0.69.0, extended]

### Preview Environment 预览环境

- OS: [Windows 10, Android]
- Browser [Chrome]

**Comment by dillonzq** [comment]
@microlong666 `about` 在 Lunr 的英文搜索中默认会被过滤掉
https://lunrjs.com/docs/stop_word_filter.js.html#line46

**Comment by microlong666** [comment]
@dillonzq 感谢指路
