### ISSUE TITLE
Remove device mockups from screenshots and update resources

### ISSUE THREAD

**Issue by onedrawingperday** [dillonzq/LoveIt#313]
Hello @dillonzq 

I am one of the maintainers of Hugo Themes.

The Hugo Themes submission guidelines were updated recently with the following:

> Screenshots are used as theme previews in the list, they should feature a theme's layout (without any browser chrome or device mockups)

I kindly request that you remove the device mockups. The list is supposed to illustrate the layout of a theme. The mockups do not look particularly good on mobile.

Furthermore I noticed that you theme's demo fails to generated because you have not updated the theme's resources after making changes. 

You need to re-generate and then commit the updated resources since the theme needs to work with the basic version of Hugo.

Please let me know once you do the above.

cc: @digitalcraftsman

**Comment by dillonzq** [comment]
@onedrawingperday Thanks.
I will fix it soon.

**Comment by dillonzq** [comment]
@onedrawingperday 
I have fixed in v0.2.5.

**Comment by onedrawingperday** [comment]
@dillonzq 

I updated the theme in https://github.com/gohugoio/hugoThemes/commit/21fa988fbcdf6fbf8f17750db96b1996525bd3a8

The demo will be present on Hugo Themes once the website is published.
