### ISSUE TITLE
[BUG] Disabling search breaks theme.js

### ISSUE THREAD

**Issue by voska** [dillonzq/LoveIt#321]
### Describe the bug 描述你遇到的错误

When you set `languages.en.params.search.enable` to `false` it breaks a number of things, including TypeIt on the homepage.

### Expected behavior 期待的行为

Disabling search, should just disable search, keeping everything else the same

### Build Environment 构建环境

- OS: MacOS 10.15.4
- Theme version/commit 2.0 e3d774f
- Hugo version v0.69.2/extended darwin/amd64

### Preview Environment 预览环境

- OS: MacOS 10.15.4
- Browser Chrome 81.0.4044.129

### Additional Information 补充信息

I've done some digging:
Theme.js breaks in initSearch() because it tries to access `searchConfig.maxResultLength` when `searchConfig` doesn't exist.

`searchConfig` doesn't exist, because `assets.html` skips adding it when `search.enable` is `false`

**Comment by dillonzq** [comment]
@voska This has been fixed in #310 
It will be published in the next release.

**Comment by voska** [comment]
Amazing, thank you!
