### ISSUE TITLE
[BUG] Error with loading comment section with the latest release

### ISSUE THREAD

**Issue by hyper-potato** [dillonzq/LoveIt#338]
### Describe the bug 描述你遇到的错误
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:22:12: executing "content" at <partial "comment.html" .>: error calling partial: "/Users/xueni/Documents/Blog/hugo/myBlog/themes/LoveIt/layouts/partials/comment.html:6:15": execute of template failed: template: partials/comment.html:6:15: executing "partials/comment.html" at <$comment.enable>: can't evaluate field enable in type bool

### Expected behavior 期待的行为
Please help!

### Screenshots 屏幕截图
<img width="572" alt="Screen Shot 2020-05-09 at 22 23 34" src="https://user-images.githubusercontent.com/38929798/81490125-ba0b7a80-9243-11ea-9901-25b9c34bf2a7.png">

![image](https://user-images.githubusercontent.com/38929798/81490132-e3c4a180-9243-11ea-8226-bd3e63e91b28.png)

<img width="817" alt="Screen Shot 2020-05-09 at 22 25 22" src="https://user-images.githubusercontent.com/38929798/81490137-fb038f00-9243-11ea-8ffb-54df3a2ac3d8.png">

### Build Environment 构建环境

- OS: macOS
- Theme version/commit: v0.2.6
- Hugo version: Hugo Static Site Generator v0.70.0/extended darwin/amd64 

### Preview Environment 预览环境
- OS: macOS
- Browser Chrome

**Comment by ramrodo** [comment]
I'm facing the same issue. One workaround you can do is:

On file: `themes/LoveIt/layouts/partials/comment.html`

**Change this:**
```
{{- $comment := .Scratch.Get "comment" | default (dict "disqus" dict "gitalk" dict "valine" dict "facebook" dict "telegram" dict "commento" dict "utterances" dict) -}}
```

**To:**

```
{{- $comment := .Site.Params.comment -}}
```

**Comment by ramrodo** [comment]
I found the error. I just created an PR:

https://github.com/dillonzq/LoveIt/pull/341

**Comment by dillonzq** [comment]
@ramrodo @hyper-potato Hello
Version 0.2.0 is an incompatible major version update.
Sorry, some configuration and front matter parameters have changed due to some reasons.
Please check the latest documentation to change the parameters.
Same issue and solutions:
https://github.com/dillonzq/LoveIt/issues/275#issuecomment-620465616

**Comment by hyper-potato** [comment]
> I'm facing the same issue. One workaround you can do is:
> 
> On file: `themes/LoveIt/layouts/partials/comment.html`
> 
> **Change this:**
> 
> ```
> {{- $comment := .Scratch.Get "comment" | default (dict "disqus" dict "gitalk" dict "valine" dict "facebook" dict "telegram" dict "commento" dict "utterances" dict) -}}
> ```
> 
> **To:**
> 
> ```
> {{- $comment := .Site.Params.comment -}}
> ```

This helped! Thank you!

**Comment by hyper-potato** [comment]
> @ramrodo @hyper-potato Hello
> Version 0.2.0 is an incompatible major version update.
> Sorry, some configuration and front matter parameters have changed due to some reasons.
> Please check the latest documentation to change the parameters.
> Same issue and solutions:
> [#275 (comment)](https://github.com/dillonzq/LoveIt/issues/275#issuecomment-620465616)

By the time I created the issue I already did the same with 'comment' parameter. So not sure if this will help tho

**Comment by ramrodo** [comment]
Right. I think there is an issue related to the `$comment` variable @dillonzq. See that in the code, there is missing `.Site` `<here>`:

```
{{- $params := <here>.Params | merge .Site.Params.page -}}
```

https://github.com/dillonzq/LoveIt/blob/master/layouts/_default/baseof.html#L12

For that reason, I opened this PR: https://github.com/dillonzq/LoveIt/pull/341/files

**Comment by dillonzq** [comment]
@ramrodo @hyper-potato 
I have pinned the same issue #275.

**Comment by dillonzq** [comment]
> Right. I think there is an issue related to the `$comment` variable @dillonzq. See that in the code, there is missing `.Site` `<here>`:
> 
> ```
> {{- $params := <here>.Params | merge .Site.Params.page -}}
> ```
> 
> [/layouts/_default/baseof.html@`master`#L12](https://github.com/dillonzq/LoveIt/blob/master/layouts/_default/baseof.html#L12) [](/dillonzq/LoveIt/blob/HEAD@{2020-05-11T17:30:34Z}/layouts/_default/baseof.html#L12)
> 
> For that reason, I opened this PR: [#341 (files)](https://github.com/dillonzq/LoveIt/pull/341/files)

Thanks for your PR.
What needs to be explained is that the original code is correct. It is a new design since v0.2.0.
`.Site.Params.page` is global config and `.Params` is page local config.
Their structure is almost the same.
Therefore you can set global comment config in `config.toml` and set a different config in the front matter of some post pages,
which means `comment: true` in front matter is replaced by:

```yaml
comment:
  enbale: true
  ...
```

If you keep the old style of front matter, this error will happen.(<$comment.enable>: can't evaluate field enable in type bool)

**Comment by ramrodo** [comment]
I see. Thanks for the explanation. So, we need to make those changes in the global comment config.
