### ISSUE TITLE
请问如何自己加入其它CDN？

### ISSUE THREAD

**Issue by hoasxyz** [dillonzq/LoveIt#339]
想添加`pangu.js`，在`config.toml`中下加入：

```
  [params.cdn]
    # pangu.js@4.0.7 https://github.com/vinta/pangu.js
    panguJS = "https://cdn.jsdelivr.net/npm/pangu@4.0.7/dist/browser/pangu.min.js"
```
后重新部署发现并没有加上`pangu.js`的效果，请问应该如何做到呢？

---
Hugo版本：`v0.70.0/extended windows/amd64`
Chrome版本：`81.0.4044.138（正式版本） （64 位）`

**Comment by dillonzq** [comment]
@hoasxyz #357 新增支持

**Comment by hoasxyz** [comment]
好的，谢谢！
