### ISSUE TITLE
Valine下添加自定义emoji不生效

### ISSUE THREAD

**Issue by microlong666** [dillonzq/LoveIt#342]
在以下目录添加配置文件：
![批注 2020-05-09 220910](https://user-images.githubusercontent.com/55701850/81549321-222b9f00-93b1-11ea-9f7e-9abe1d6f0437.png)

在config.toml下配置：

![批注 2020-05-09 221123](https://user-images.githubusercontent.com/55701850/81549332-25bf2600-93b1-11ea-9d33-b6077e44986f.png)

Valine 1.4.14不生效，检查过CDN没问题，主题自带的yml则没问题：

![批注 2020-05-09 220929](https://user-images.githubusercontent.com/55701850/81549326-25268f80-93b1-11ea-9fd1-91bf5d46e66c.png)

能否出个关于emoji配置文件的说明，增加对更多emotion支持，或者指正是否有配置的错误。感谢😃

### Build Environment 构建环境

- OS: [Windows 10]
- Theme version/commit [0.2.6]
- Hugo version [0.70.0 extended]

### Preview Environment 预览环境

- OS: [Windows 10, Android]
- Browser [Chrome]

**Comment by dillonzq** [comment]
@microlong666 哈喽
可能是你的 `tieba.yml` 的 `emojiMaps` 之后的缩进有问题

**Comment by microlong666** [comment]
正确缩进还有转为json后都不行，还没能确定是什么问题，使用的是[这个项目的CDN](https://github.com/GamerNoTitle/Valine-Magic)，如果觉得不错可以考虑添加进去。

![批注 2020-05-11 203541](https://user-images.githubusercontent.com/55701850/81562221-0c28d900-93c7-11ea-8f4b-aeeaae8e0095.png)

**Comment by dillonzq** [comment]
@microlong666 可以考虑添加 😃

**Comment by BahuangShanren** [comment]
### 提交评论后，只显示所用emoji的代号
表情候选预览时，emoji正常显示：
![image](https://user-images.githubusercontent.com/48022216/92350866-d1cd0f80-f10c-11ea-8bdf-26e9c1fe1b62.png)
但是**提交评论后，只显示所用emoji的代号**（比如只显示了 `:alu(1):` ），而正常情况应该显示：![image](https://user-images.githubusercontent.com/48022216/92351231-ae569480-f10d-11ea-8692-e52b0778c0e1.png)

所以我的错误比 [microlong666](https://github.com/dillonzq/LoveIt/issues/342#issue-615763114) 更进一步嘛 😅
我的 [博客地址](https://www.shan-ren.cn/)

### 我为Valine添加自定义emoji时是这样做的：
1. 自定义了一个 [emoji CDN](https://cdn.jsdelivr.net/gh/BahuangShanren/picture@master/)
2. `themes\LoveIt\assets\data\emoji\my.yml`  文件的配置如下：
![image](https://user-images.githubusercontent.com/48022216/92352375-87e62880-f110-11ea-81b4-aa427e5897e9.png)
3. `config.toml` 文件的配置如下：
![image](https://user-images.githubusercontent.com/48022216/92352581-004ce980-f111-11ea-9613-e4c08731aabc.png)

**请问是哪里出了问题呢？**
难道说，自定义emoji CDN还需要修改 `themes\LoveIt\assets\lib\valine\Valine.min.js` 或  `themes\LoveIt\layouts\partials\comment.html` 吗？还是有其他什么要修改的？

**Comment by microlong666** [comment]
@BahuangShanren 表情能正常加载应该已经引入成功了，你所说的情况可能是 Valine 的问题，试试重装 Valine

**Comment by BahuangShanren** [comment]
### 将 `alu(1): ` 改为 `alu1:` ，解决问题

我原来的 `emoji` 配置文件是这么写的：
```yaml
emojiMaps:
  alu(1): alu/alu(1).png
```
改为
```yaml
emojiMaps:
  alu1: alu/alu(1).png
```
可能是 `(` 和 `)` 与 `emoji` 的表示代码混淆导致了我这个错误
