### ISSUE TITLE
[BUG] Google Analytics issue, problem with lazysizes and lightgallery, random typeit issues

### ISSUE THREAD

**Issue by matteototaro** [dillonzq/LoveIt#344]
Hi, before the latest upgrade (0.2.6) google analytics worked fine, but now it doesn't show anymore any live user. I tried multiple things, with or without filters. Also I put my ID in the new section [params.analytics.google] just to try but it doesn't work. I don't know if I messed up some value.

-Also, I use "figure" with image and when I put lazyload class and I use lightgallery with two sources for every image (low quality and high quality) during the transition from one to the other there's an annoying zoom-in in the picture. I've seen that you use "/svg/loading/normal.svg" in your example site but I wanted to put the low quality image first in the _src_ element because my pics are heavy and I want to give the user an idea of the picture while is waiting.

-Randomly the title with **typeit** of the entire site doesn't show up in Chrome and Edge, Firefox and Safari are ok. I use Firefox and in localhost and it shows up.

- OS: [ Windows 10]
- Theme version/commit [0.2.6]
- Hugo version [e.g. 0.69.0]
- Browser [e.g. Chrome, Edge,]
Firefox and Safari works fine

Thanks in advance!

**Comment by matteototaro** [comment]
Update: VSCode noticed that in the analytics file there are 14 errors **mysite\themes\LoveIt\layouts\partials\plugin\analytics.html** 
Also I saw that the image.html file in **mysite\themes\LoveIt\layouts\partials\plugin\image.html** uses lazyload and lightgallery with the tag "< image >" as your documentations say, so maybe I'll be using this tag.

**Comment by matteototaro** [comment]
Hi @dillonzq 
I just pulled the latest [commit ] (https://github.com/dillonzq/LoveIt/pull/358) you just did 2hours ago.

Unfortunately I found out that the google analytics still didn't work. VSCode found 8 errors in **mysite\themes\LoveIt\layouts\partials\plugin\analytics.html** .
I saw that the google analytics internal template were missing so I put them in the directory **\layouts\partials\head\meta.html** of my site via overwritting the meta.html file.

It worked and the google analytics page signed my live presence online, on the other hand this **worked only for desktop**. I tried with my phone and it didn't show the live user.
So the template thing isn't the only thing that's missing.

I hope you find this helpful, thanks in advance.

**Comment by dillonzq** [comment]
Hi, @matteototaro 
Maybe you opened an ad blocking plugin? It will affect the functionality of GA.

**Comment by matteototaro** [comment]
Hi @dillonzq,
yes indeed I use an AdBlock on firefox desktop and mobile, but the problem was that my android device is rooted so the adblock went too deep on my smartphone ahah because I block ads also on pc and I thought it was the same type of filter.

Now I checked and everything works, thank you!
