### ISSUE TITLE
执行 hugo server报错

### ISSUE THREAD

**Issue by iwyang** [dillonzq/LoveIt#346]
```
$ hugo server
Building sites … WARN 2020/05/12 17:26:17

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.

Built in 190 ms
Error: Error building site: TOCSS: failed to transform "style.scss" (text/x-scss): resource "scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d" not found in file cache

```

**Comment by h-2** [comment]
I get this, too.

**Comment by dillonzq** [comment]
Please install the extended version of hugo.

**Comment by h-2** [comment]
> Please install the extended version of hugo.

I don't even know what that is. And it's not provided by any of the operating systems I use.

**Comment by theapplegates** [comment]
Forgive me for answering if it is out of line.
You can get the extended release from [here](https://github.com/gohugoio/hugo/releases).
Just scroll to the bottom and you will see Hugo_extended_, that is what needs to be installed when someone mentions Hugo extended.

**Comment by dillonzq** [comment]
Hi, @h-2
![image](https://user-images.githubusercontent.com/30786232/81840182-33c0a280-957b-11ea-8e1e-c69604cf4954.jpeg)

The compatibility of Hugo basic version has been improved in v0.2.7.
Hugo extended version is only needed when using custom styles or `style` shortcode.

**Comment by g0rbe** [comment]
The error exists with hugo extended version.
Version: `Hugo Static Site Generator v0.72.0-8A7EF3CF/extended linux/amd64 BuildDate: 2020-05-31T12:14:23Z`

**Comment by chenxuejian** [comment]
![image](https://user-images.githubusercontent.com/10387832/85133940-3f844080-b26e-11ea-84b1-0aa0060c98dd.png)

**Comment by AutomationD** [comment]
I'm curious why is this issue closed? the issue indeed exists with hugo extended

**Comment by AutomationD** [comment]
Indeed this is happening when using `{{< style >}} {{< /style >}}` shortcodes. LoveIt 2.10 breaks on both hugo extended and regular hugo, while 1.x was working fine with this shortcode with hugo regular.
