### ISSUE TITLE
配置了gitalk不生效

### ISSUE THREAD

**Issue by EdisonZjs** [dillonzq/LoveIt#36]
![image](https://user-images.githubusercontent.com/38233247/72138074-f4185d00-33c6-11ea-802c-bf7ff4d04c8a.png)
comments.html复制的没有更改，config里面js和css的cdn也配置了，params.gitalk相关也配置了。

**Comment by dillonzq** [comment]
可能是在生成 HTML 时没有设置环境变量 `HUGO_ENV=production`?
