### ISSUE TITLE
[BUG] Search box icon

### ISSUE THREAD

**Issue by 0derel** [dillonzq/LoveIt#365]
### Describe the bug 描述你遇到的错误
Search box icon goes up and down when going to homepage or any page

### Build Environment 构建环境

- OS: macOS
- Theme version/commit 0.2.0
- Hugo version 0.62.0

### Preview Environment 预览环境

- OS: macOS
- Browser: Firefox

**Comment by dillonzq** [comment]
Hi, @0derel
It's a Firefox rendering bug, which does not seem to be reproduced on Chrome or Safari.😕️

**Comment by 0derel** [comment]
Yes, i tried it and it looks like firefox error. Thanks for your help.
