### ISSUE TITLE
Add site search function

### ISSUE THREAD

**Issue by alertcode** [dillonzq/LoveIt#37]

**Comment by dillonzq** [comment]
正在考虑添加

**Comment by ZhaoqiangCn** [comment]
我用大佬的主题加algolia做搜索的解决方案，附教程
https://www.nashome.cn/post/hugo-algolia/

**Comment by Briy09** [comment]
支持添加搜索功能，下面是一些参考：
https://ox-hugo.scripter.co/test/search/?q=hugo
https://scripter.co/search/?q=hugo
https://koirand.github.io/blog/
https://koirand.github.io/blog/2018/pulp-search/
https://discourse.gohugo.io/t/found-two-local-full-text-search-can-it-be-integrated-in-hugo/14318

**Comment by SenLief** [comment]
支持添加搜索功能，这样就拿来做本地笔记用了。

**Comment by iamwlb** [comment]
> 正在考虑添加

期待赶紧加上，大佬的教程不好使，点击搜索后整个背景都是黑色的，不是半透明的。

**Comment by dillonzq** [comment]
已经在 #231 中添加
