### ISSUE TITLE
[FEATURE] Auto Fill in Date Modified 自动填写文档修改时间

### ISSUE THREAD

**Issue by zhangj1an** [dillonzq/LoveIt#373]
### Feature Request 功能需求

- 想请问一下，对于每篇post的`date: 2020-05-19T21:57:40+08:00`和`lastmod: 2020-05-19T16:45:40+08:00`，有没有自动生成的功能？自己填写时间精确到秒有点难。

### Useful reference 有价值的参考

 - https://bookdown.org/yihui/rmarkdown-cookbook/update-date.html
类似于这样的function形式。如果能直接用plugin的话就更好了，诚心求教。。

你们的网站超级漂亮！！！很喜欢。谢谢！

**Comment by dillonzq** [comment]
哈喽, @zhangj1an 
使用 `hugo new posts/xxxx.md` 创建的文章 `date` 会自动生成.
使用 git 管理的项目可以自动根据 commit 的时间生成 lastmod 的时间

**Comment by zhangj1an** [comment]
啊谢谢！刚刚试了，使用`hugo new posts/xxxx.md`创建的new post确实能自动生成date，但是它是一个单独的`xxxx.md`文件，并不是一个folder里中英法三语`*.md`的，所以用`hugo serve --disableFastRender`时localhost上无法显示这份markdown文档。。

**Comment by dillonzq** [comment]
@zhangj1an 多语言模式下需要加语言后缀 `hugo new posts/xxx.en.md`
可以参考[这篇文档](https://hugoloveit.com/zh-cn/theme-documentation-basics/)的步骤创建一个单语言的网站.

配置尽量以文档页面为准，不建议直接使用 `exampleSite` 下的配置.

**Comment by zhangj1an** [comment]
根据你提供的链接我意识到可以用 [directory based archetypes](https://gohugo.io/content-management/archetypes/#directory-based-archetypes) 来按照loveit的theme搞一个建立新`post`的template,  就能直接生成`mynewpost`文件夹下`index.en.md`，`index.zh-cn.md`的文件，和他们的创建修改时间了。非常感谢！
