### ISSUE TITLE
[FEATURE] Support Page Bundle Images

### ISSUE THREAD

**Issue by Ben-Chapman** [dillonzq/LoveIt#375]
### Describe the bug 描述你遇到的错误

It appears that the change from `safeURL` to `relURL` in [f5fb31ec](https://github.com/dillonzq/LoveIt/commit/f5fb31ec43e59765feb0b214895d3cee1039d02a#diff-b9cb41333639f911a05f50d7fcb88025 ) has broken image URLs for images within a Page Bundle.

Given a directory structure of:

content/
├── posts
│   ├── my-post
│   │   ├── image1.png
│   │   ├── image2.png
│   │   └── index.md

an image reference of:
```
{{< image src="image1.png"
    caption="Caption Here"
    src-s="image1.png"
    src-l="image1.png"
>}}
```
and a `baseURL` of https://foo.com

the image href is generated as a relative URL from the `baseURL` value, which results in the image URL being https://foo.com/image1.png, which is not a valid image path given the directory structure:

```
<a class="lightgallery" href="/image1.png" title="/image1.png" data-thumbnail="/image1.png" 
[snip]
```

Previously (using `safeURL`) this same image URL would be correctly generated as "image1.png" resulting in a URL of https://foo.com/my-post/image1.jpg

```
<a class="lightgallery" href="image1.png" data-thumbnail="image1.png"><img class="lazyautosizes lazyloaded" src="image1.png" 
[snip]
```

### Expected behavior 期待的行为
Image path generation using `relURL` is working as [documented](https://gohugo.io/functions/relurl/), but it's usage in the image shortcode does not appear to work with content organized in Page Bundles.

I'm not sure why the change from `safeURL` to `relURL`, but would appreciate some guidance on how best to manage content organized within Page Bundles, or a fix to the image shortcode to correctly manage page bundle content.

### Build Environment 构建环境

- OS: Ubuntu eoan (19.10) 
- Theme version/commit: Currently 0.2.8, can repro on any version > 0.2.0
- Hugo version: Hugo Static Site Generator v0.70.0/extended linux/amd64 BuildDate: 2020-05-13T17:30:34Z

### Additional Information 补充信息

To reproduce:
```
$ cd $blog_dir
$ hugo new posts/testing/index.md
```
- Add an image to the `./content/posts/testing/` directory 
- Edit `index.md`, adding an image shortcode of:
```
{{< image src="image.png" caption="Lighthouse (`image`)" src-s="" src-l="" >}}
```
- `hugo serve -D`
- Observe broken image, and the generated HTML referencing an image path of `/`

**Comment by dillonzq** [comment]
Hi， @Ben-Chapman
The theme does not yet support images in content bundles.

I will add this feature soon.

**Comment by Ben-Chapman** [comment]
That's great to hear. I'm not at all blocked by this, but full support for page bundles would be fantastic.

Thanks for the great work!
