### ISSUE TITLE
[BUG] 当TOC处于keepStatic时，浏览器下面会出现左右移动的滚动条

### ISSUE THREAD

**Issue by dipperkun** [dillonzq/LoveIt#376]
### Describe the bug 描述你遇到的错误
 当TOC处于keepStatic时，浏览器在文章页面时，下面会出现左右移动的滚动条。
一段简短的对于你遇到的错误的描述.

### Expected behavior 期待的行为

一段简短的对于你期待的行为的描述.
文档内容位于浏览器中央，浏览器不会出现左右移动的滚动条。
### Screenshots 屏幕截图
![image](https://user-images.githubusercontent.com/1575205/82387674-3f740380-9a6a-11ea-9848-a04854d98142.png)

如果可以的话, 提供屏幕截图对解决问题很有帮助.

### Build Environment 构建环境

- OS: [e.g. Windows 10, macOS, Ubuntu]
- Theme version/commit [e.g. 0.2.0, 2ccba79]
- Hugo version [e.g. 0.69.0]

Please use Hugo **extended** version.
请使用 Hugo **extended** 版本.
Linux Mint 19.3
Chrome, Firefox
Hugo Static Site Generator v0.69.2-EC9DCF30/extended linux/amd64 BuildDate: 2020-04-24T07:57:53Z

### Preview Environment 预览环境

- OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android]
- Browser [e.g. Chrome, Safari, Firefox]
 Chrome, Safari, Firefox
### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...

**Comment by dipperkun** [comment]
补充：LoveIt：v0.2.9

**Comment by dillonzq** [comment]
哈喽, @dipperkun 
这个问题会尽快修复

**Comment by dipperkun** [comment]
谢谢！不懂前端，帮不上忙😓
