### ISSUE TITLE
Custom CSS doesn't seem to be applied

### ISSUE THREAD

**Issue by jbfreels** [dillonzq/LoveIt#38]
Giving this theme another go, stuck with custom CSS.  

```
╭─jbfreels@kira ~/src/jbfreels.com ‹master*›
╰─$ hugo env
Hugo Static Site Generator v0.62.2/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.13.5"
```

I've created `assets/css/_custom.scss` with the following in it...

```css
.home-intro .home-social-links i {
  font-size: 2.0rem;
}
```

I'm probably missing something simple.  I run `HUGO_ENV=production hugo --gc --minify` to generate the site.  Searching the `public` folder I don't see my change to `style.min.css` or any other file in `public`.

**Comment by jbfreels** [comment]
Updated to hugo v0.63.1, no change

```
╭─jbfreels@kira ~/src/jbfreels.com ‹master*›
╰─$ hugo env
Hugo Static Site Generator v0.63.1/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.13.6"
```

**Comment by jbfreels** [comment]
Updating the `_custom.css` in in the theme folder produces this...

![hugo-ignored-custom-css](https://user-images.githubusercontent.com/5649291/73122537-162be680-3f54-11ea-823a-4ccf2e53f6f5.png)

**Comment by dillonzq** [comment]
The latest commit has fixed the bug.

**Comment by jbfreels** [comment]
Confirmed, thanks!
