### ISSUE TITLE
[BUG] Overriding CSS does not seem to work as expected

### ISSUE THREAD

**Issue by KHannibal** [dillonzq/LoveIt#398]
Using Hugo extended 0.71.1 with LoveIt 0.2.10.

I added `/assets/css/_override.scss` but nothing I write in this file is picked up.

According to the theme's documentation, this is what I am supposed to do though.

![HL](https://user-images.githubusercontent.com/3843004/83331556-4cc59500-a297-11ea-9b48-39d22d43ef12.png)

**Comment by Selmirrrrr** [comment]
Hello, I'm facing the same issue on my side. Any thoughts ?

**Comment by aplatanado** [comment]
Same issue here with Hugo 0.72.0.

**Comment by py563** [comment]
+1 
same here

**Comment by py563** [comment]
did you give variable name correct? @Selmirrrrr it is working to me.

**Comment by KHannibal** [comment]
> After checking again, I came to the conclusion that it works.
> 
> When I copied variables form `_variables.scss` I copied them with the `!default` keyword and it didn't worked. But if for `$global-background-color-dark: #292a2d !default;` I paste `$global-background-color-dark: #ff0000;` it works fine.
> 
> Thanks @py563, I'll probably send a PR to improve documentation about this particular case.

Confirmed. I close the issue, sorry about that.

**Comment by ITAYC0HEN** [comment]
> if for `$global-background-color-dark: #292a2d !default;` I paste `$global-background-color-dark: #ff0000;` it works fine.

Confirm. I suggest it be mentioned as people like us love to copy paste from the variables.scss and easily miss the "!default"

**Comment by OrangeTux** [comment]
Coming here to say that it's wasn't clear for me that one shouldn't copy `!default` to `assets/css/_override.scss`. Maybe a note in the docs would help people like me to make that same mistake?

**Comment by jjatinggoyal** [comment]
It definitely isn't clear in docs that you need to remove` !default` in `assets/css/_override.scss`. Hoping this note gets added to docs
