### ISSUE TITLE
[BUG] Stackoverflow icon is not getting properly rendered

### ISSUE THREAD

**Issue by kishore-devaraj** [dillonzq/LoveIt#400]
### Describe the bug 描述你遇到的错误
一 On adding `stackoverflow` as a social media icon in the home profile section I'm getting codepen icon.

### Expected behavior 期待的行为

一 It should display the `stackoverflow` icon (available in font-awesome)

### Screenshots 屏幕截图

如果可以的话, 提供屏幕截图对解决问题很有帮助.
<img width="225" alt="Screenshot 2020-05-31 at 7 39 39 PM" src="https://user-images.githubusercontent.com/29497877/83354717-16137b80-a378-11ea-8225-b9d783e79159.png">

### Build Environment 构建环境
- OS:  macOS
- Theme version/commit - latest
- Hugo version [e.g. 0.71.0]

### Preview Environment 预览环境
- OS: macOS
- Browser: Firefox Developer edition

**Comment by py563** [comment]
please reedit the issue title to describe the specific bug which you described rather than having an ambiguous title. 

for the wrong icon issue change line 159 in file `assets/data/social.yml` to `fab fa-stack-overflow`.
