### ISSUE TITLE
[BUG] The generated HTML is not valid

### ISSUE THREAD

**Issue by nekr0z** [dillonzq/LoveIt#401]
The theme generates HTML that does not pass common validators.

https://validator.w3.org/nu/?doc=https%3A%2F%2Fhugoloveit.com
is a good example.

**Comment by khusika** [comment]
I have done for some fixes at #558

**Comment by khusika** [comment]
There is also issue reported by this link
https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fhugoloveit.com%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en
I'll try to figure it out the fixes

**Comment by uPagge** [comment]
@khusika Would you like to switch to a [new repository with fork](https://github.com/upagge/uBlogger) :angel:?
