### ISSUE TITLE
[BUG] Hugo/Katex failed to render multi-line Latex

### ISSUE THREAD

**Issue by zqfang** [dillonzq/LoveIt#402]
### Describe the bug 描述你遇到的错误

一段简短的对于你遇到的错误的描述.
Katex failed to render mult-line Latex

一段简短的对于你期待的行为的描述.

Latex code
```
$$
\begin{aligned}
P\left(X=x | Y=c_{k}\right) &=P\left(X^{(1)}=x^{(1)}, \cdots, X^{(n)}=x^{(n)} | Y=c_{k}\right) \\
&=\prod_{j=1}^{n} P\left(X^{(j)}=x^{(j)} | Y=c_{k}\right)
\end{aligned}
$$
```
the output should be
<img width="475" alt="Screen Shot 2020-06-01 at 15 43 51" src="https://user-images.githubusercontent.com/5889336/83461900-b58b4980-a41e-11ea-9f56-6fa609ee41e2.png">

### Screenshots 屏幕截图

如果可以的话, 提供屏幕截图对解决问题很有帮助.
<img width="729" alt="Screen Shot 2020-06-01 at 15 39 34" src="https://user-images.githubusercontent.com/5889336/83461677-2f6f0300-a41e-11ea-8ae9-fb2e95fd804c.png">

### Build Environment 构建环境

- OS: macOS,
- Theme version/commit: v0.2.10,  f787a4e

- Hugo version: v0.72.0/extended

```
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.14.3"
```

### Preview Environment 预览环境

- OS: macOS
- Browser Chrome

**Comment by zqfang** [comment]
I add 
```
markup: "mmark"
math: true
```
to the `toc` in each post, and solved the problem temporarily.

However,  "mmark" is deprecated. Don't know when this will break again.

**Comment by ben519** [comment]
Hey, I've also been fighting with this issue and the numerous quirks of katex + hugo. Regarding your particular case, here's a solution that drops your dependency on "mmark" (which as you mention is deprecated).

# 1. In your front matter, use
```
math:
  enable: true
```
(alternatively, you can set this up in config.toml)

# 2. In your post, use
```
$$
\begin{aligned} P\left(X=x | Y=c_{k}\right) &=P\left(X^{(1)}=x^{(1)}, \cdots, X^{(n)}=x^{(n)} | Y=c_{k}\right) \\\\ 
&=\prod_{j=1}^{n} P\left(X^{(j)}=x^{(j)} | Y=c_{k}\right) \end{aligned}
$$
```
Some subtleties to point out:

1. `\begin{aligned}` can't be on its own line. Nor can `\end{aligned}`. So you can't do
```
$$
\begin{aligned}
P\left(X=x | Y=c_{k}\right) &=P\left(X^{(1)}=x^{(1)}, \cdots, X^{(n)}=x^{(n)} | Y=c_{k}\right) \\\\ 
&=\prod_{j=1}^{n} P\left(X^{(j)}=x^{(j)} | Y=c_{k}\right)
\end{aligned}
$$
```

2. You need to use four `\`s instead of two because they need to be escaped.
3. You must have a trailing space at the end of those four `\`s. That is, you need `\\\\ ` instead of `\\\\`.

**Comment by zqfang** [comment]
@ben519 , thanks for your sharing. But I still have other weird problems even I add `\\\\ ` to latex code, for example
```latex
$$
F_{X}(x)=\operatorname{Pr}(X \leq x)= 
\left\{ \begin{array}{l}
0 \text { if } x<0 \\
\frac{1}{2} \text { if } 0 \leq x<1 \\
1 \text { if } x \geq 1
\end{array} \right.
$$
```
however, with 
```yaml
markup: "mmark"
math: true
```
All my math equations rendered properly, except deprecation warning

**Comment by ben519** [comment]
@zqfang 

I hear you - I too have come up against many weird issues with my old latex code. Personally though, I'd opt to tinker with my latex code until it plays nicely with hugo and Katex. For example, looking over some [Katex examples](https://katex.org/docs/supported.html) and doing some tinkering, I can rewrite your code above as 

```
$$
F_{X}(x)=\operatorname{Pr}(X \leq x)= \begin{cases} 
0 &\text{if } x<0 \\\\ 
\frac{1}{2} &\text{if } 0 \leq x<1 \\\\ 
1 &\text{if } x \geq 1 \end{cases}
$$
```

and this renders nicely on my blog.

<img width="408" alt="Screen Shot 2020-06-05 at 2 58 49 PM" src="https://user-images.githubusercontent.com/723099/83917825-27280800-a73d-11ea-830e-f8fc8d92118f.png">

Keep in mind that [mmark will be removed in a future Hugo release](https://gohugo.io/content-management/formats/).

**Comment by zqfang** [comment]
@ben519 , Thank you very much for sharing. I see, it's all about the katex syntax. 

By the way, I use `\cr` to replace `\\` and it works fine. I just don't like `\\\\ `. It's not pretty in the old `mmark`

**Comment by SimZhou** [comment]
So it seems to be the problem of Katex Syntax, it just does not support line feed in the formula, right?

**Comment by ben519** [comment]
@SimZhou I'm not sure what you mean by "line feed". If you mean *newline*, it works - you just have to use four backslashes with a trailing space, like `\\\\ `. There are some other quirks as well, but with enough tinkering, every formula I've attempted has rendered fine. If you want to see what is possible, check out [this page](https://www.gormanalysis.com/blog/introduction-to-neural-networks/) of my blog.

**Comment by SimZhou** [comment]
> @SimZhou I'm not sure what you mean by "line feed". If you mean _newline_, it works - you just have to use four backslashes with a trailing space, like `\\\\ `. There are some other quirks as well, but with enough tinkering, every formula I've attempted has rendered fine. If you want to see what is possible, check out [this page](https://www.gormanalysis.com/blog/introduction-to-neural-networks/) of my blog.

i c i c, thx for explaining!
