### ISSUE TITLE
[BUG] toc 目录异常

### ISSUE THREAD

**Issue by ZhaoUncle** [dillonzq/LoveIt#410]
### Describe the bug 描述你遇到的错误

1. md 文件内容
```
# 一级目录
## 二级目录
### 三级目录
#### 四级目录
##### 五级目录
###### 六级目录
```
2. 配置目录展开折叠，当为 false 的时候，可以正出显示右边栏目录，但是个人认为展示效果有点不是很好。
问题：
如图 1：为何原文会有“#”好“|”的效果？如果是博主个人喜好，请忽略。
如图 2：右边栏每个目录之间前置空间间隔过大，还带有“|”前缀，是否能够调整缩小？
```
    # 目录配置
    [params.page.toc]
      # whether to make the table of the contents in the sidebar automatically collapsed
      # 是否使侧边目录自动折叠展开
      auto = false
```
如图：
图 1：
![image](https://user-images.githubusercontent.com/31182637/83833052-9b52b380-a71d-11ea-8e05-a938b36d18f1.png)
图 2：
![image](https://user-images.githubusercontent.com/31182637/83833038-9130b500-a71d-11ea-9739-fa0a8c264a97.png)

3. 右边栏目录展示效果，只有一级和和二级目录生效。
```
    # 目录配置
    [params.page.toc]
      # whether to make the table of the contents in the sidebar automatically collapsed
      # 是否使侧边目录自动折叠展开
      auto = true
```
![image](https://user-images.githubusercontent.com/31182637/83833400-73b01b00-a71e-11ea-9249-1255987c32c7.png)

### Build Environment 构建环境

- OS: [macOS]
- Theme version/commit [commit f787a4e5ad4edf60467658d10c286248dc5027a6 (HEAD -> master, tag: v0.2.10, origin/master, origin/HEAD]
- Hugo version [v0.67.0/extended]

### Preview Environment 预览环境

- OS: [macOS]
- Browser [Chrome]

**Comment by SimZhou** [comment]
You need to set the boundary of toc levels to show in global `config.toml`:
```toml
[markup]
  [markup.tableOfContents]
    ordered = false
    startLevel = 1
    endLevel = 6
```
This would solve your issue.

However, there is another bug if you in the meantime set 'toc: auto: true' in the FrontMatter of an article, to open the auto collapse function of TOC (#428). So just leave it false first.

**Comment by ZhaoUncle** [comment]
The problem I want to express more is about the display effect of the markdown directory level, whether it is in the article details or the dynamic column directory on the right.

**Comment by SimZhou** [comment]
> The problem I want to express more is about the display effect of the markdown directory level, whether it is in the article details or the dynamic column directory on the right.

Regarding **Question 2.1**:
**\#** and **|** symbols are pre-set by the author with css. You could modify the file at `<your site>\themes\loveit\assets\css\_page\_single.scss` to come up with your own heading styling. 

e.g. to remove **#** and **|**, simply remove the codes `from line 100 to line 118`:
```css
    > h2,
    > h3,
    > h4,
    > h5,
    > h6 {
      > .header-mark::before {
        content: "|";
        margin-right: .3125rem;
        color: $single-link-color;

        [theme=dark] & {
          color: $single-link-color-dark;
        }
      }
    }

    > h2 > .header-mark::before {
      content: "#";
    }
```

**Question 2.2**:
Similarly, the styling of toc is located at `themes\loveit\assets\css\_partial\_single\_toc.scss`. 
To modify the front gap, decrease the value `padding-left` at `line 28`:
```css
      ul {
        padding-left: 1.5rem;
      }
```
To remove **|** symbol, it is at `line 17`:
```css
      a:first-child::before {
        content: "|";
        font-weight: bolder;
```

**Question 3:** 
Check #428

**Comment by ZhaoUncle** [comment]
@SimZhou 
Thank you very much! You are correct, I'm sorry I'm not familiar with front-end code.
