### ISSUE TITLE
[FEATURE] few questions.

### ISSUE THREAD

**Issue by colinder** [dillonzq/LoveIt#423]
Hi 
Thank you for your service!
I think this is very goood theme and i using your theme
I have a few questions.

First of all, How do you make classification in categories?
(In navbar → click "Categories") 
![image.png](https://files.alexhchu.com/2020/06/19/5d24194fc0b2d.png)

For each post, input   
---
categories: [django]
---
this text but it not work

As I am Korean, the explanation might have been strange because I am not good at English, but if you reply to my email, I will capture the specific questions and ask you again.

thank you

**Comment by nekr0z** [comment]
If you're using TOML front-matter (i.e. your frontmatter ends with `+++`) the correct syntax is:
```
categories = ["django", "reinhardt", "music", "awesome"]
```
