### ISSUE TITLE
[FEATURE] few questions2

### ISSUE THREAD

**Issue by colinder** [dillonzq/LoveIt#426]
Hi 
it me again  :)

I was testing the posting, and I had a question.

I uploaded it to git and saw the results, how can I change the lines in the .md file?
![image](https://user-images.githubusercontent.com/60080125/85205422-4ab29b80-b356-11ea-9f0d-9026456bce61.png)

I want to organize my writing by changing the lines.
I'd appreciate it if you could tell me how.
Thank you!

**Comment by nekr0z** [comment]
First of all, please consider closing the issue with your previous question.

Second, what exacly are you trying to achieve? It looks like what you did is simlpy upload the generated website to GitHub. That is a perfectly OK way to publish.

If instead you want a repository of the source files that would deploy to GitHub Pages automatically when you make changes to source md files, you should have done what [documentation](https://gohugo.io/hosting-and-deployment/hosting-on-github/) suggests.

**Comment by colinder** [comment]
The first issue closed.

![image](https://user-images.githubusercontent.com/60080125/85238291-ff88ad80-b467-11ea-9e55-1cd0be4f8362.png)
On the right is written in the .md file and on the left is output looks like this

And I want to give a space between the first line and the bottom line, but when I turn on the server, there is no space between the first line and the bottom line.
How do I give you a space.

**Comment by nekr0z** [comment]
> I want to give a space between the first line and the bottom line, but when I turn on the server, there is no space between the first line and the bottom line.

Markdown treats a single `newline` character as a space, and two or more `newline` characters in a row are treated as "new paragraph" command.  This is why you are only getting one "new paragraph" command in your example.

If you need to add multilple `newline` characters one after another you can escape them with `\`:
```
This line is 3 paragraps higher
\
\
\
than this line.
```
---

This line is 3 paragraps higher
\
\
\
than this line.

---

If you want _all_ the paragraph breaks on _all_ the pages of your website look bigger, you can use custom CSS file to define a bigger `margin` on `.single .content p`. The LoveIt theme defines it as
```
{
  margin: .5rem 0;
}
```
i.e. `.5rem` for vertical, 0 for horizontal, so if your custom CSS file (`assets/css/_custom.scss`) had
```
.single .content p {
    margin: 1rem 0;
}
```
your paragraps would have twice as much space between them compared to theme's default.

**Comment by colinder** [comment]
ok, I found a solution.

and Can you customize a Blockquotes?
I want to change to the basic(Default) markdown Blockquotes form.

**Comment by SimZhou** [comment]
> ok, I found a solution.
> 
> and Can you customize a Blockquotes and Inline Code(`)?
> I want to change to the basic(Default) markdown Blockquotes form and Inline Code

Blockquote: located at `themes\loveit\assets\css\_page\_single.scss`, from `line 244` to `line 255`

Inline Code: `themes\loveit\assets\css\_partial\_single\_code.scss`, from `line 1` to `line 14` and `line 32` to `line 38`

There you go.

**Comment by colinder** [comment]
in accordance with your comments

I tried to customize it, but it didn't work.

my code is as follows.
![image](https://user-images.githubusercontent.com/60080125/85462664-a85a1880-b5e0-11ea-860a-c29c55ecdd87.png)

output is as follows.
![image](https://user-images.githubusercontent.com/60080125/85462818-e35c4c00-b5e0-11ea-8492-402575a4e138.png)

I'd appreciate it if you could explain why there is no change.
(The Inline Code also remains unchanged.)

**Comment by SimZhou** [comment]
@colinder 
Well, It works from my side: 
![image](https://user-images.githubusercontent.com/11748629/85510771-7077c300-b62a-11ea-985f-070f9f4d4a16.png)

Do you have custom css files in <your site>/assets/css/... ? Maybe the theme settings are overrided by sth else.

**Comment by colinder** [comment]
@SimZhou 
😶 That's weird.

I created a folder and file with the address below.
<my site>\assets\css\_page\_single.scss

and try to below
![image](https://user-images.githubusercontent.com/60080125/85585642-2408a380-b67b-11ea-8005-7906378050f8.png)
but it didn't work.

Are there any additional things I need to do?
I don't know what I'm missing.

**Comment by SimZhou** [comment]
> @SimZhou
> 😶 That's weird.
> 
> I created a folder and file with the address below.
> `<my site>\assets\css\_page\_single.scss`
> 
> and try to below
> ![image](https://user-images.githubusercontent.com/60080125/85585642-2408a380-b67b-11ea-8005-7906378050f8.png)
> but it didn't work.
> 
> Are there any additional things I need to do?
> I don't know what I'm missing.

Try overridding by modifying `<your site>/assets/css/_custom.scss`, modifying by `<your site>\assets\css\_page\_single.scss` would lose everything else except you copy the whole `_single.scss` file from theme dir to this dir. 
BTW, I've tried both, your code is correct, but I don't know why your's is not working.

![_custom.scss](https://user-images.githubusercontent.com/11748629/85598137-e22d2c80-b67d-11ea-9c18-44cd1e49d414.png)
![_single.scss](https://user-images.githubusercontent.com/11748629/85599351-01788980-b67f-11ea-85f1-3b8983f2efe6.png)

**Comment by colinder** [comment]
😶 
Is there any part I need to touch in the _overrinde.scss file and config.toml file?

Your screenshot shows two files changing, but I didn't touch them when it came to customization.

**Comment by SimZhou** [comment]
well, would that be the issue of caching? Maybe try change a browser, or chrome incognito mode?

**Comment by SimZhou** [comment]
btw, you could modify the styling in chrome f12

**Comment by SimZhou** [comment]
To debug the page, like this:

![test6](https://user-images.githubusercontent.com/11748629/85840837-c3d74600-b7cf-11ea-9ae5-f34c8d1f80ff.gif)

**Comment by SimZhou** [comment]
Clearing browser cache data would also do

**Comment by colinder** [comment]
> Clearing browser cache data would also do

I've tried everything I know and everything you've taught me, but I haven't succeeded.
Using the developer tools(f12) (debug the page) (element - style) confirmed that it could be modified as I wanted.
I don't know what kind of bug this is or if it's just me, but I don't think there's any way anymore.

**Comment by colinder** [comment]
OMG.
I checked, and you're '_style.scss' is reflected. but I'm 'style.min.csss' is reflected!
I don't know how to change it.  I'd appreciate it if you could tell me how.
 
 
-----Original Message-----

**Comment by SimZhou** [comment]
I don't understand...I don't even have a file called `style.min.csss` in my hugo project...

**Comment by SimZhou** [comment]
you might reopen the issue if you wanna someone else's help

**Comment by colinder** [comment]
I registered to use valine, but it doesn't work normally.

I modified the contents of config.toml as below.
I think we need to write appId, appkey.
However, I don't know what value to enter appId, appkey. Please give me some advice.
