### ISSUE TITLE
[BUG] exampleSite fails to build, f787a4e

### ISSUE THREAD

**Issue by SimZhou** [dillonzq/LoveIt#432]
There's a bug when buiding the exampleSite in the themes folder:

```
ERROR 2020/06/24 13:58:13 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://instagram.com/p/BWNjjyYFxVx/&hidecaption=1": Get "https://api.instagram.com/oembed/?url=https://instagram.com/p/BWNjjyYFxVx/&hidecaption=1": dial tcp 31.13.97.245:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Built in 30695 ms
Error: Error building site: "C:\Users\yihua\My Programs\Hugo\testsite\content\posts\theme-documentation-built-in-shortcodes\index.zh-cn.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
```

The error happens in the article Theme documentation - Build in Shortcodes, when the whole article (including zh-cn, fr, en) is deleted, the build succeeds. 

 f787a4e

**Comment by nekr0z** [comment]
The build failure is due to timeout of `https://api.instagram.com` from your machine; the site builds OK on my machine and on the CI/CD system.

Either avoid using `{{< instagram >}}` shortcode (section 4 of the "offending" page) or make sure your ISP doesn't block Instagram servers.

**Comment by SimZhou** [comment]
I see, however I assume network status should not prevent hugo from building the site? Is it a must for instagram/twitter?
btw, youtube works just fine.

**Comment by nekr0z** [comment]
I agree it's a bug, however, it's not a bug in this theme; LoveIt uses Hugo's builtin `instagram` shortcode`, so you may want to report it up there.

**Comment by SimZhou** [comment]
Good idea. 

So I had a search and found the same issue: https://github.com/gohugoio/hugo/issues/7228

If anyone's got the same issue pls go check it there.
