### ISSUE TITLE
[RESOLVED] [BUG] titles of the articles are pasted on the left

### ISSUE THREAD

**Issue by Eliesemoule** [dillonzq/LoveIt#435]
I don't know if it's a bug or if I'm doing something wrong, but the titles of the articles are pasted on the left. While I would like it to be pasted on the right like on your demo website

<img width="825" alt="Capture d’écran 2020-06-23 à 10 37 47" src="https://user-images.githubusercontent.com/20320541/85694486-74155380-b6d7-11ea-9b77-0215a1ac5a37.png">

- OS: CentOS 8
- Theme: 0.2.10
- Hugo version: 0.71.0 extended

- OS: MacOS X 10.15.5 or Fedora 32
- Browser: Firefox 77.0.1 (Mac OS X and Linux) or Chrome 83.0.4103.116 (Mac OS X)

**Comment by nekr0z** [comment]
This is expected behavior.

Titles of posts (of type `post`, i.e. residing in `/content/posts/`) are aligned to the left, titles of other articles are aligned right.

For example: [this](https://evgenykuznetsov.org/en/posts/2020/new-github/) is a post on my site; the title "Doubting Everything" is on the left. [This](https://evgenykuznetsov.org/en/about/) is a non-post article on my site; the title "About" is aligned right.

You can customize this behavior using custom CSS.

**Comment by Eliesemoule** [comment]
Thanks for your reply.

All posts are locate in content/posts/ folder as you can see below
<img width="560" alt="Capture d’écran 2020-06-25 à 13 10 50" src="https://user-images.githubusercontent.com/20320541/85709260-5fd85300-b6e5-11ea-8f07-ecea278fccbf.png">

Below the first line of the post :
---
title: "Commandes Proxmox"
author: elie
type: post
date: 2020-06-10T07:43:15+00:00
url: /2020/06/10/commandes-proxmox/
categories:
  - Aides-mémoire
  - Auto-hébergement
  - Proxmox
  - Serveur
  - Virtualisation
tags:
  - auto-hebergement
  - commandes
  - linux
  - proxmox
  - proxmox 6
  - proxmox 6.0
  - serveur

---

If the not-default behavior aligns the titles to the left, why isn't it the case with me?

**Comment by nekr0z** [comment]
Try removing `type: post` from the frontmatter or changing it to `type: posts`.

**Comment by Eliesemoule** [comment]
Thanks a lot for your help. It works fine, now !

**Comment by nekr0z** [comment]
Glad you have it sorted out!

Please consider closing the issue so that the developers are not distracted (in case your issue is indeed resolved).

**Comment by nekr0z** [comment]
> That's strange, I didn't have the problem with another theme

LoveIt is quite different from other themes in that its `posts` layout is a non-default one. Usually theme authors do things the other way around and have `posts` type rendered by a default layout.
