### ISSUE TITLE
footer中的内容都无法显示是哪里设置有问题吗

### ISSUE THREAD

**Issue by ZhaoqiangCn** [dillonzq/LoveIt#439]
### Describe the bug 描述你遇到的错误

阅读原文，上一章下一章，分享，这些底部的内容都没有显示

另外TOC也无法显示

### Build Environment 构建环境

https://www.nashome.cn

搭建在github pages，和netlify 都无法显示 production参数已加。
最新版0.2.x

![image](https://user-images.githubusercontent.com/19513914/85976067-45b3b300-ba0c-11ea-9923-29902526dd8a.png)

![image](https://user-images.githubusercontent.com/19513914/85976207-8d3a3f00-ba0c-11ea-86a0-ee85d73dc521.png)

**Comment by KFCxMcDonalds** [comment]
how u solve this problem? I still can't have toc, my website do not show posts on the homepage neither, but I have set Hiddenfromhomepage=false
