### ISSUE TITLE
Hinding avatar?

### ISSUE THREAD

**Issue by werkstattcodes** [dillonzq/LoveIt#44]
many thanks for this beautiful theme. One question - is there any option to hide the avatar (other than displaying a white picture). Leaving the file location empty produces an error.

**Comment by dillonzq** [comment]
Hi, @werkstattcodes 
home_mode will be improved recently

**Comment by dillonzq** [comment]
Hi, @werkstattcodes 
I have added more configuration for the home page to custom profile and posts in #74 .
