### ISSUE TITLE
[QUESTION] Recent posts do not appear on the home page

### ISSUE THREAD

**Issue by Eliesemoule** [dillonzq/LoveIt#441]
Recent posts do not appear on the home page

I think I did something wrong or forgot to do something but I don't know what.

Could you help me, please...

### Build Environment 构建环境

- OS: CentOS 7
- Theme version/commit: 0.2.10
- Hugo version: 0.71.0-06150C87/extended

### Preview Environment 预览环境

- OS: Mac OS X 10.5.5 or Fedora 32
- Browser: Chrome 83.0.4103.116 or Firefox 77.0.1

### Additional Information 补充信息

Configuration files
  [params.page]
    # whether to hide a page from home page
    # 是否在主页隐藏一篇文章
    hiddenFromHomePage = false

front matter code
---
title: "Commandes Proxmox"
author: elie
type: posts
date: 2020-06-10T07:43:15+00:00
url: /2020/06/10/commandes-proxmox/
categories:
  - Aides-mémoire
  - Auto-hébergement
  - Proxmox
  - Serveur
  - Virtualisation
tags:
  - auto-hebergement
  - commandes
  - linux
  - proxmox
  - proxmox 6
  - proxmox 6.0
  - serveur

---

**Comment by nekr0z** [comment]
Nearly impossible to tell what the issue is without seeing the source files (at least `config.toml` and the non-appearing `.md`s).

**Comment by Eliesemoule** [comment]
My config.toml.txt and md.txt file didn't appear in home page are attached to this message
[config.toml.txt](https://github.com/dillonzq/LoveIt/files/4846650/config.toml.txt)
[2020-06-10-commandes-proxmox.md.txt](https://github.com/dillonzq/LoveIt/files/4846655/2020-06-10-commandes-proxmox.md.txt)

**Comment by TsukimiSerenade** [comment]
I poured your config and post as they are to my localhost.  I only commented the line ` #themesDir = "/var/www/html/hugo-test/themes"` to fit my environment. They all worked fine. The article is shown in the homepage. You may need to investigative other issues.

I suggest you update to the latest release. If it doesn't work, leave this post only to see if it works. If it works, keeping adding older post until it break again.

**Comment by Eliesemoule** [comment]
I tested with `#themesDir = "/var/wwww/html/hugo-tests/themes"` as well as with the latest version of hugo and it doesn't work any better. I have tried with one post and it doesn't wok better.

Do you have anther to solved the issue?

**Comment by nekr0z** [comment]
> I tested with `#themesDir = "/var/wwww/html/hugo-tests/themes"` as well as with the latest version of hugo and it doesn't work any better. I have tried with one post and it doesn't wok better.

I'm afraid we'll need your whole directory (or perhaps a git repository) in this case to debug this.

You see, as @TsukimiSerenade illustrated, the post itself (as well as your config) does not break things and behaves as expected. This means that Hugo works as expected, the theme works as expectes, your post works as expected and your config is OK. However, you say you don't get the desired behaviour, which means there's something else that breaks things.

We are no mentalists, we have no way of knowing what else is in your site's directory that could affect the behaviour, so we need the whole picture to help you. As it is, there's no demonstratable bug.

**Comment by TsukimiSerenade** [comment]
> Do you have anther to solved the issue?

Did you update this theme, LoveIt to the latest release as well? Did you move out all the posts out and bring it back one by one?
I suggest you build a new site folder and use you current config, and bring you old article one by one to see if anything breaks at any time.

**Comment by Eliesemoule** [comment]
@nekr0z I have created a git repository with with all files of my website : https://github.com/Eliesemoule/Hugo-test.git
@nekr0z @TsukimiSerenade I apologize for the lack of precision. Thank you for taking the time to help me.
Below all actions I did :

- I'm already using the latest version of the theme (v0.2.10)

- I tested with only one post (2020-06-10-commands-proxmox.md)

- I tested by commenting on the line: themesDir = "/var/www/html/hugo-test/themes"

- I updated the Hugo binary with the latest version (v0.73.0 extended)

**Comment by TsukimiSerenade** [comment]
Please note that commenting the line: `themesDir = "/var/www/html/hugo-test/themes"` is for my personal environment setup, not a general solution. 
I poured the whole project in, nothing is shown in the homepage.  When I replaced it with my theme folder, everything is working properly. 
So try to re-download the theme.
<img width="1344" alt="Screen Shot 2020-07-01 at 2 28 23 PM" src="https://user-images.githubusercontent.com/32047956/86278915-269d5880-bba7-11ea-800e-915a8c448844.png">

**Comment by Eliesemoule** [comment]
I uncomment `themesDir = "/var/www/html/hugo-test/themes"`, I deleted the theme directory.I re-downloaded it, unzipped it and now it works perfectly Recent posts appear on the home page.
Thank you very much @nekr0z and @TsukimiSerenade
