### ISSUE TITLE
[BUG] telegram的评论区不正确显示

### ISSUE THREAD

**Issue by techkoala** [dillonzq/LoveIt#444]
### Describe the bug 描述你遇到的错误

telegram的评论区不正确显示，显示到页脚最下面，也是就比页面底部的网站说明还要更下面

### Screenshots 屏幕截图
![批注 2020-07-03 110840.png](https://i.loli.net/2020/07/03/d1D6wexFnYITS3P.png)

这里只是本地演示，所以提示域名有问题

### Build Environment 构建环境

- OS: [Ubuntu 20.04]
- Theme version/commit [v0.2.10]
- Hugo version [e.g. 0.68.3]

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [ Windows 10]
- Browser [Chrome]

**Comment by sosiristseng** [comment]
Related to #433

**Comment by ron159** [comment]
> Related to #433

Thx

**Comment by techkoala** [comment]
> Related to #433

THx
