### ISSUE TITLE
推送时出现了错误：Process completed with exit code 255.

### ISSUE THREAD

**Issue by aynix** [dillonzq/LoveIt#449]
**workflow 出现了错误，以下是网页端运行日志，不知道怎么修改。我也没有改动过主题文件夹/layouts/partials/init.html**

> Run hugo --minify
WARN 2020/07/07 15:27:20 Module "LoveIt" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Error: add site dependencies: load resources: loading templates: "/home/runner/work/aynix.github.io/aynix.github.io/themes/LoveIt/layouts/partials/init.html:35:1": parse failed: template: partials/init.html:35: function "warnf" not defined
##[error]Process completed with exit code 255.

**这是邮箱收到的错误信息：**
Run failed for blog (70ebc90)

Repository: aynix/aynix.github.io
Workflow: hugo push to github pages
Duration: 29.0 seconds
Finished: 2020-07-07 15:27:24 UTC
View results
Jobs:
build-deploy failed (1 annotation)

**这是遇到问题的界面截图：**
https://i.loli.net/2020/07/07/AR6eKHmzCkcIoG8.png

hugo：v0.73.0/extended windows/amd64
博客托管在 Github Pages 上，主题是最新的

**Comment by aynix** [comment]
刚才问了其他的大佬，好像是主题没有适配hugo的新版本，可以降低hugo版本试试。

**Comment by BoWang816** [comment]
0.74.2可
