### ISSUE TITLE
[FEATURE] switch to ForkAwesome

### ISSUE THREAD

**Issue by nekr0z** [dillonzq/LoveIt#451]
While free to use, Font Awesome is not free software. Fork Awesome (https://forkaweso.me/) can mostly replace it, and it's MIT licensed like LoveIt.

**Comment by besendorf** [comment]
Someone already developed a script for LoveIt to switch to Fork Awesome: https://codeberg.org/tytan652/use_loveit_with_fork_awesome
Would be awesome to include this into upstream LoveIt

**Comment by dillonzq** [comment]
See #679
