### ISSUE TITLE
[FEATURE] Long code snippets to be opened by default

### ISSUE THREAD

**Issue by coroutineDispatcher** [dillonzq/LoveIt#460]
Leave long code snippets open by default 

I hope I am not repeating an issue here. But even when I read the documentation, looks somehow bothering to click on the code snippet in order for it do drop down and render. What I mean is:

Instead of:

> Programming language block (click to open)

to have this:

> Programming language block
line1
line2
line30

All the time opened. Or, a value which the user can decide if by default should be all time opened or clickable.

**Comment by wang95** [comment]
You can set the value of max lines
https://hugoloveit.com/theme-documentation-basics/#3-configuration

[params.page.code]
      # the maximum number of lines of displayed code by default
      maxShownLines = 10

**Comment by coroutineDispatcher** [comment]
Thanks for the reply. And last question, this needs to be configured on the `toml` file right?

**Comment by wang95** [comment]
yes

**Comment by coroutineDispatcher** [comment]
Thank you.
