### ISSUE TITLE
[BUG] Bold is not applied.

### ISSUE THREAD

**Issue by colinder** [dillonzq/LoveIt#465]
Bold is not applied.

i write  **props(부모에서 자식에게 데이터 이동)**와 __emit(자식에서 부모에게 데이터 이동)__이다.  
but it not work

![image](https://user-images.githubusercontent.com/60080125/87794866-3b097280-c882-11ea-8d53-cef15e9daaa4.png)

**Comment by fspranger** [comment]
As it looks to me a `space` is missing after the last `**` as well as `__`.

Example `**Bold** text`

**Comment by colinder** [comment]
Thank 
I found that there was a difference between `<` and `(` in using bold(`**`). 
If `(` or `)` is included in the bold, space should be used at the end, and in the case of `<`, space is not required.
