### ISSUE TITLE
Failed to read Git log: fatal: your current branch 'master' does not have any commits yet[BUG] Some problem...

### ISSUE THREAD

**Issue by dducted** [dillonzq/LoveIt#473]
Hi guys,

After installation and setup I am getting the following error:
`Failed to read Git log: fatal: your current branch 'master' does not have any commits yet`

I checked older issues but none was in english, so I wasnt able to find a solution for it.

Thanks for your help!

**Comment by 189169** [comment]
我把exampsite 文件复制到我的网站目录里 试了下也出现这个错误
➜ hugo server -D
WARN 2022/07/16 11:39:16 Module "LoveIt" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Start building sites …
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
ERROR 2022/07/16 11:39:17 Failed to read Git log: fatal: your current branch 'master' does not have any commits yet
WARN 2022/07/16 11:39:17

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.
WARN 2022/07/16 11:39:17 The "tweet" shortcode will soon require two named parameters: user and id. See "C:\hugo\sites\ctf2333\content\posts\theme-documentation-built-in-shortcodes\index.en.md:151:1"
WARN 2022/07/16 11:39:38 The "tweet" shortcode will soon require two named parameters: user and id. See "C:\hugo\sites\ctf2333\content\posts\theme-documentation-built-in-shortcodes\index.zh-cn.md:152:1"
Error: Error building site: logged 1 error(s)
