### ISSUE TITLE
[FEATURE] 添加 gravatar 头像的镜像地址支持

### ISSUE THREAD

**Issue by zaunist** [dillonzq/LoveIt#479]
### Describe the feature you want 描述你的功能需求

- Feature 1
现在主题默认用的是 gravatar 的官方源，在国内访问加载很慢甚至有时候打不开，是否能添加一个选择 gravatar 源的配置？
- ...

### Useful reference 有价值的参考

If available, provide useful links to fulfill the feature.
如果可以的话, 提供实现这个功能的相关参考链接.

**Comment by xss4755** [comment]
希望增加+1
