### ISSUE TITLE
[BUG] Error on loading homepage featuredImagePreviews

### ISSUE THREAD

**Issue by SimZhou** [dillonzq/LoveIt#486]
I am using the latest 0.2.10 version of theme, and the preview image on homepage suddenly fail to load. 

I checked the img tag and found it is trying to load the image from the global dir (which should be a local dir)

I am using the front matter as like this:
```
featuredImage: "Self-motivation.jpg"
featuredImagePreview: "Self-motivation.webp"
```
I could have changed the front matter as like this to make it work, but it is ugly: 
```
featuredImage: "Self-motivation.jpg"
featuredImagePreview: "/posts/2020/how-to-retrieve-motivation/Self-motivation.webp"
```

The point is, **in the beginning the first one works pretty fine for my first 3 posts**, and idk why it fails to work now, I think I didn't touch anything inside the theme folder.

**Comment by SimZhou** [comment]
Hey Idk why but right after I've posted this issue, the thing works. Truly dumb : \
I think it is an issue of my local browser or network or sth.

**Comment by SimZhou** [comment]
Hey I am encountering this issue again! This is happening while I am editing my new posts, but after a hot reload, Some of the preview images are gone:
I located the issue with chrome, it seems somethings' went run when rendering different size of the preview images
![image](https://user-images.githubusercontent.com/11748629/91065634-4f9c1000-e663-11ea-9d32-ad13844b8ddd.png)
So, when I change my browser into mobile mode, the image would immediately show up:
![image](https://user-images.githubusercontent.com/11748629/91065975-b0c3e380-e663-11ea-9b21-888fbc43a484.png)

btw, re-deploying the hugo server **does not** work. Tha'ts why I am reopening this issue.

**Comment by SimZhou** [comment]
Here is an animated picture to illustrate the issue: 
![123](https://user-images.githubusercontent.com/11748629/91066341-2e87ef00-e664-11ea-93c0-bdc7b0d473be.gif)

**Comment by SimZhou** [comment]
Solved. In `layouts/partials/plugin/image.html`，the medium sized **srcset** is not using the correct pre-defined variable. 
See `data-srcset` attribute in <img> tag below: 
```javascript
{{- if .Linked -}}
    <a class="lightgallery" href="{{ $large | safeURL }}" title="{{ .Title | default $alt }}" data-thumbnail="{{ $small | safeURL }}"{{ with .Caption }} data-sub-html="<h2>{{ . }}</h2>{{ with $.Title }}<p>{{ . }}</p>{{ end }}"{{ end }}{{ with .Rel }} rel="{{ . }}"{{ end }}>
        <img
            class="lazyload{{ with .Class }} {{ . }}{{ end }}"
            src="{{ $loading.RelPermalink }}"
            data-src="{{ .Src | safeURL }}"
            data-srcset="{{ $small | safeURL }}, {{ .Src | safeURL }} 1.5x, {{ $large | safeURL }} 2x"
            data-sizes="auto"
            alt="{{ $alt }}"{{ with .Height }} height="{{ . }}"{{ end }}{{ with .Width }} width="{{ . }}"{{ end }} />
    </a>
{{- else -}}
    <img
        class="lazyload{{ with .Class }} {{ . }}{{ end }}"
        src="{{ $loading.RelPermalink }}"
        data-src="{{ .Src | safeURL }}"
        data-srcset="{{ $small | safeURL }}, {{ .Src | safeURL }} 1.5x, {{ $large | safeURL }} 2x"
        data-sizes="auto"
        alt="{{ $alt }}"
        title="{{ .Title | default $alt }}"{{ with .Height }} height="{{ . }}"{{ end }}{{ with .Width }} width="{{ . }}"{{ end }} />
{{- end -}}
```
which should be
```javascript
{{- if .Linked -}}
    <a class="lightgallery" href="{{ $large | safeURL }}" title="{{ .Title | default $alt }}" data-thumbnail="{{ $small | safeURL }}"{{ with .Caption }} data-sub-html="<h2>{{ . }}</h2>{{ with $.Title }}<p>{{ . }}</p>{{ end }}"{{ end }}{{ with .Rel }} rel="{{ . }}"{{ end }}>
        <img
            class="lazyload{{ with .Class }} {{ . }}{{ end }}"
            src="{{ $loading.RelPermalink }}"
            data-src="{{ .Src | safeURL }}"
            data-srcset="{{ $small | safeURL }}, {{ $src | safeURL }} 1.5x, {{ $large | safeURL }} 2x"
            data-sizes="auto"
            alt="{{ $alt }}"{{ with .Height }} height="{{ . }}"{{ end }}{{ with .Width }} width="{{ . }}"{{ end }} />
    </a>
{{- else -}}
    <img
        class="lazyload{{ with .Class }} {{ . }}{{ end }}"
        src="{{ $loading.RelPermalink }}"
        data-src="{{ .Src | safeURL }}"
        data-srcset="{{ $small | safeURL }}, {{ $src | safeURL }} 1.5x, {{ $large | safeURL }} 2x"
        data-sizes="auto"
        alt="{{ $alt }}"
        title="{{ .Title | default $alt }}"{{ with .Height }} height="{{ . }}"{{ end }}{{ with .Width }} width="{{ . }}"{{ end }} />
{{- end -}}
```

**Comment by SimZhou** [comment]
@dillonzq You wanna fix it yourself or to leave me the chance to make a PR? :)

**Comment by khusika** [comment]
> I am using the latest 0.2.10 version of theme, and the preview image on homepage suddenly fail to load.
> 
> I checked the img tag and found it is trying to load the image from the global dir (which should be a local dir)
> 
> I am using the front matter as like this:
> 
> ```
> featuredImage: "Self-motivation.jpg"
> featuredImagePreview: "Self-motivation.webp"
> ```
> 
> I could have changed the front matter as like this to make it work, but it is ugly:
> 
> ```
> featuredImage: "Self-motivation.jpg"
> featuredImagePreview: "/posts/2020/how-to-retrieve-motivation/Self-motivation.webp"
> ```
> 
> The point is, **in the beginning the first one works pretty fine for my first 3 posts**, and idk why it fails to work now, I think I didn't touch anything inside the theme folder.

This may happen when you used `webp` as image source. According to [ Hugo image processing documentation](https://gohugo.io/content-management/image-processing/#target-format), at this time only `jpg`, `png`, `tif`, `bmp`, and `gif` format images can be used in Hugo. But there is currently no WebP support for Hugo. That's why the images you use aren't generated with the LoveIt shortcodes.

If you wanted to use WebP encoding in Hugo, you can try to [build Hugo from source](https://gohugo.io/getting-started/installing/#source) with picking this PR [#7155](https://github.com/gohugoio/hugo/pull/7155) in your git-tree.

Read my article about _[WebP Image Processiong in Hugo](https://khusika.com/webp-image-processing-in-hugo/)_ for more information.

**Comment by SimZhou** [comment]
> > I am using the latest 0.2.10 version of theme, and the preview image on homepage suddenly fail to load.
> > I checked the img tag and found it is trying to load the image from the global dir (which should be a local dir)
> > I am using the front matter as like this:
> > ```
> > featuredImage: "Self-motivation.jpg"
> > featuredImagePreview: "Self-motivation.webp"
> > ```
> > 
> > 
> > I could have changed the front matter as like this to make it work, but it is ugly:
> > ```
> > featuredImage: "Self-motivation.jpg"
> > featuredImagePreview: "/posts/2020/how-to-retrieve-motivation/Self-motivation.webp"
> > ```
> > 
> > 
> > The point is, **in the beginning the first one works pretty fine for my first 3 posts**, and idk why it fails to work now, I think I didn't touch anything inside the theme folder.
> 
> This may happen when you used `webp` as image source. According to [ Hugo image processing documentation](https://gohugo.io/content-management/image-processing/#target-format), at this time only `jpg`, `png`, `tif`, `bmp`, and `gif` format images can be used in Hugo. But there is currently no WebP support for Hugo. That's why the images you use aren't generated with the LoveIt shortcodes.
> 
> If you wanted to use WebP encoding in Hugo, you can try to [build Hugo from source](https://gohugo.io/getting-started/installing/#source) with picking this PR [#7155](https://github.com/gohugoio/hugo/pull/7155) in your git-tree.
> 
> Read my article about _[WebP Image Processiong in Hugo](https://khusika.com/webp-image-processing-in-hugo/)_ for more information.

Well, I don't know this but apparently this is not what I've encountered, since I tried jpg and it is not working either. 

BTW, I already solved this issue up there. Thanx for the help :P
