### ISSUE TITLE
[BUG] Netlify deploy got Error: "/opt/build/repo/themes/LoveIt/layouts/partials/assets.html:15:1": parse failed: template: partials/assets.html:15: function "merge" not defined

### ISSUE THREAD

**Issue by yvza** [dillonzq/LoveIt#503]
Hallo guys, i need help to solve this, i new to hugo, and already learn basic through gohugo website, after hugo installed i choose this theme to get experience on hugo

This is my reference: https://hugoloveit.com/theme-documentation-basics/#basic-configuration

When i running locally, it works fine
![Image 2](https://user-images.githubusercontent.com/25668079/90953086-6c470680-e41d-11ea-942d-1494e503760e.png)
![Image 4](https://user-images.githubusercontent.com/25668079/90953092-779a3200-e41d-11ea-9596-19dd99b513a6.png)

But i got this error, when i trying to deploy it on Netlify
![Image 1](https://user-images.githubusercontent.com/25668079/90953104-8c76c580-e41d-11ea-998b-e8dd6c1fd4e0.png)

Any solutions?

**Comment by anyanf** [comment]
同遇到这个问题了，求问解决方案

**Comment by anyanf** [comment]
set Netlify env:HUGO_VERSION = 0.74.3
It can be solved
@yvza

**Comment by yvza** [comment]
ohh my bad, sorry i miss netlify.toml config
thanks @anyanf 

ref: https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify
