### ISSUE TITLE
[BUG] 测试文章.md中的menu含有一个新建菜单,文章删除后,menu却删不掉了

### ISSUE THREAD

**Issue by ibolee** [dillonzq/LoveIt#507]
博客建立以后,我复制了其它博客主题的演示文章.md放在:\根目录\content\posts路径下
后来发现这篇文章中的头部信息的menu值为:tutorials

也就是文章头部信息是这样的:

`---
title: "演示文章"
date: 2020-08-27T21:00:05+08:00
draft: true
categories: ["tutorials"]

lightgallery: true
---`

后来把这篇文章删除了,重新用hugo生成,发现menu上面的tutorials这个导航去不掉了:
如图 : https://img.ibolee.com/git_blog/bug1.png
演示地址 : https://ibolee.github.io

后来我尝试把public出来的静态文件进行了全部删除,然后重新生成,然后发现这个tutorials还是没有清除掉,求教各位大佬解决方法.

**Comment by afderlqs** [comment]
去主目录下的config.toml中看看导航栏是否有这个。
或者：把examplesite中的config.toml替换为主目录下的同名文件，在 hugo serve 调试修改下。

**Comment by ibolee** [comment]
@afderlqs 
感谢回复!
主目录下的config.toml中没有这个,已经排查过了.
