### ISSUE TITLE
Header bar behavior and back-to-top button

### ISSUE THREAD

**Issue by t404notfound** [dillonzq/LoveIt#51]
Hi, I notice that the header bar doesn't hide when we scroll down. Is it an intended behavior? In my opinion, the bar should hide when users scroll down at some point and it shows up again when the user scroll up, just like many websites. It will increase browsing experience.

Also, there is no back-to-top button when browsing in mobile devices. Should we add it?

**Comment by dillonzq** [comment]
fixed in #73
