### ISSUE TITLE
Need help on SEO and Adsense 😟

### ISSUE THREAD

**Issue by Shivanandroy** [dillonzq/LoveIt#516]
I'm new to Hugo and I love this theme. I have 2 very basic question though:

1. **What are settings that needs to be changed for an optimized SEO or any suggestions to improve SEO?**
I'm using the default settings that comes packaged with the theme

**2. Where actually I need to place the Adsense code?**

**Comment by Ben-Chapman** [comment]
Hey @Shivanandroy,
Google Analytics is already embedded and configured in this theme. To enable it, within `config.toml`, you'll need to include `googleAnalytics = "UA-XXXXXXX-X`

Check out the [configuration from the example site](https://github.com/dillonzq/LoveIt/blob/master/exampleSite/config.toml#L38) for more detail.

I don't know of any theme specific SEO settings aside from `[params.page.seo]` in `config.toml`, but if other folks have more info I'd love to know also.

**Comment by Shivanandroy** [comment]
Thanks @Ben-Chapman ! 
- I've added googleAnalytics as you mentioned above. I was unclear about the Adsense code and where do I have to put them in Hugo website - The Adsense code starts with `<script>some adsense code</script>`
- Can you please help me understand these `[params.page.seo]` parameters
```
[params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""
```

**Comment by Ben-Chapman** [comment]
Adsense is automatically injected into your pages if enabled, and you should be able to see this by viewing the source of your site. You can find the theme source [here](https://github.com/dillonzq/LoveIt/blob/master/layouts/partials/plugin/analytics.html).

To be honest, I haven't taken the time to really understand the SEO optimizations, so unfortunately I can't help much there.

**Comment by rajanpanchal** [comment]
@Shivanandroy 
I have added Adsense code here: 
themes/LoveIt/layouts/_default/baseof.html

**Comment by Shivanandroy** [comment]
@rajanpanchal  thanks. Can you show me where exactly in baseof.html file. Is it between <head> tags.

**Comment by rajanpanchal** [comment]
Here it is.
```
<!DOCTYPE html>
<html lang="{{ .Site.LanguageCode }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
<meta name="robots" content="noodp" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
	<script data-ad-client="ca-pub-6073208778082866" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <title>
			{{- .Title | default .Site.Title -}}
        </title>
```

**Comment by Shivanandroy** [comment]
Thanks you @rajanpanchal
