### ISSUE TITLE
[BUG] Doesn't work with Hugo >= v0.75.0

### ISSUE THREAD

**Issue by nekr0z** [dillonzq/LoveIt#518]
When `.Content` is nil, the `function/content.html`partial fails the new error check [introduced](https://gohugo.io/news/0.75.0-relnotes/#notes) in Hugo v0.75.0.

**Comment by KHannibal** [comment]
When building my site, I get the following error :

`ERROR 2020/09/15 09:26:56 render of "page" failed: "/Users/khan/Sites/hugo/themes/LoveIt/layouts/posts/single.html:42:37": execute of template failed: template: posts/single.html:42:37: executing "content" at <partialCached "function/path.html" . .>: error calling partialCached: partials that returns a value needs a non-zero argument.`

**Comment by vinimmelo** [comment]
After 0.75.0 the theme doesn't work anymore. Breaking changes from Hugo, sad.

**Comment by nekr0z** [comment]
> If anyone can do this, I found this "work around"

This is not a work-around, and it is not even related to the problem. #519 is a fix that actually is [two lines of code](https://github.com/dillonzq/LoveIt/pull/519/files).

**Comment by theapplegates** [comment]
Ah, ok. I see that now. My bad.

**Comment by mwolfaardt** [comment]
When wil the next release be and the change go in? At the moment I can't publish my site.

**Comment by nekr0z** [comment]
> When wil the next release be and the change go in?

No one knows. See #514.



> At the moment I can't publish my site.

Yes, you can: either use an older Hugo version or fix your copy of the theme by adding the necessary lines.

**Comment by mwolfaardt** [comment]
Is there any update on this? or planned release update?

**Comment by achenger** [comment]
With the help of automated deployment tools  (such as https://vercel.com/ ), we can lock the version of hugo in 0.74.0 by creating file `vercel.json`. For details pls. browse https://vercel.com/docs/build-step#build-&-development-settings

**Comment by antedoro** [comment]
Hi on mac I use this workaround:

Go here: [hugo repo](https://github.com/gohugoio/hugo/releases) and find Hugo version you want (in my case v0.74.3).
Download file and copy it on /usr/local/bin/ so:

From downlod directory with Terminal:

`cp hugo_extended_0.74.3_macOS-64bit.tar.gz  /usr/local/bin/`

go on `cd /usr/local/bin/`

extract it with: 

` tar -zxvf ugo_extended_0.74.3_macOS-64bit.tar.gz`

Now you need an alias to call this particular version of hugo:

```
cd /usr/local/bin/hugo-0.74.3/
# ./hugo version
```

```
alias hugo74='/usr/local/bin/hugo-0.74.3/hugo'
hugo74 version
```

cd on working directory and 

`hugo74 server -D`
