### ISSUE TITLE
[BUG] ICP设置不能使用HTML格式

### ISSUE THREAD

**Issue by weeshinwang** [dillonzq/LoveIt#528]
### Describe the bug 描述你遇到的错误

在`config.toml` 中的icp设置中无法成功超链接。（由于管局要求必须将备案号超链接到管局的网站）
例如：
```
  [params.footer]
    enable = true
    icp = "<a href="url">link text</a>"
```

显示错误
```
config.toml:80:1": unmarshal failed: Near line 80 (last key parsed 'params.footer'): expected a top-level item to end with a newline, comment, or EOF, but got 'u' instead
```

### Build Environment 构建环境

- OS: [Windows 10]
- Theme version/commit [0.2.10, f787a4e]
- Hugo version [0.75.1]

**Comment by weeshinwang** [comment]
问题解决了 是引号的问题，在参数中使用单引号就没问题了，例如：

```
  [params.footer]
    enable = true
    icp = "<a href='url'>link text</a>"
```

**Comment by nekr0z** [comment]
`icp = '<a href="url">link text</a>'`

**Comment by weeshinwang** [comment]
> `icp = '<a href="url">link text</a>'`

Thank you  Sir, the problem is indeed caused by the quotation mark 😁😁
