### ISSUE TITLE
[BUG] Tags and Categories are not displaying in blog posts

### ISSUE THREAD

**Issue by mwolfaardt** [dillonzq/LoveIt#538]
### Describe the bug 描述你遇到的错误
I've defined tags and categories in the head of the blog post, but it is not displaying in the page, all that display is a "," comma next to the icon

一段简短的对于你遇到的错误的描述.

### Expected behavior 期待的行为

一段简短的对于你期待的行为的描述.

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/11614412/96923978-4b993c80-14b2-11eb-96e2-acbc969b6e7a.png)

如果可以的话, 提供屏幕截图对解决问题很有帮助.

### Build Environment 构建环境

- OS: [e.g. Windows 10, macOS, Ubuntu]
- Theme version/commit [e.g. 0.2.0, 2ccba79]
- Hugo version [e.g. 0.69.0]

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android]
- Browser [e.g. Chrome, Safari, Firefox]

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...
categories : ["Azure"]
tags: ["ACS", "Power Apps"]

**Comment by mwolfaardt** [comment]
Any update?

**Comment by nekr0z** [comment]
Please show your front matter in full.

**Comment by mwolfaardt** [comment]
In my blog posts I added the following : 
categories : ["Azure"]
tags: ["ACS", "Power Apps"]

**Comment by nekr0z** [comment]
These two lines can not be a part of the valid front matter.

Hugo takes JSON, TOML, or YAML as front matter. Your two lines are not JSON (because the words `categories` and `tags` are not in quotes), not TOML (because TOML has `=` instead of `:`), and not YAML (because YAML doesn't have `[]` brackets).

**Comment by mwolfaardt** [comment]
Thank you,  I'll have a look how to do yaml arrays

**Comment by nekr0z** [comment]
@mwolfaardt if your front matter is supposed to be in YAML (begins and ends with `---`), then the lines you want are:
```yaml
categories:
- Azure
tags:
- ACS
- Power Apps
```
Feel free to consult [Hugo documentation](https://gohugo.io/content-management/front-matter/) when in doubt. Also, please don't forget to close this issue.

**Comment by mwolfaardt** [comment]
Hi, thanks I've made the change as above, but still have the same issue : 
![image](https://user-images.githubusercontent.com/11614412/99904549-2b88b300-2cd4-11eb-86f8-b45ce4f0afac.png)

Front matter: 
categories: 
- Power Apps Center of Excellence
- Power Apps
tags:
- COE
- Power Apps

I've also looked at the Hugo Documentation and video and all seem correct.

**Comment by mwolfaardt** [comment]
So I kinda got it working, had to do two things : 
1. Remove the spaces from the front matter Power Apps became Power-Apps
2. Create a folder or file with the same name Power-Apps.md 
3. Add the following front matter within the file : 
---
Title : Power Apps
---

Only problem I'm facing now is when you go to the categories no pages are listed

**Comment by mwolfaardt** [comment]
Got it fixed, added 
[taxonomies]
  series = "series"
  tag = "tags"
  category = "categories"
into my config.toml
