### ISSUE TITLE
[BUG] Unable to override "maxShownLines = 10"

### ISSUE THREAD

**Issue by reachsumit** [dillonzq/LoveIt#540]
### Describe the bug 描述你遇到的错误

一段简短的对于你遇到的错误的描述.
`config.toml` has this setting:
maxShownLines = 10
When I try to override this from my post's index.md file, overriding doesn't work and the value in config.toml is still used.

### Expected behavior 期待的行为
`maxShownLines = 20` or any other value should work when overriding from individual posts.

一段简短的对于你期待的行为的描述.
`maxShownLines` overriding from posts should work.

### Screenshots 屏幕截图

如果可以的话, 提供屏幕截图对解决问题很有帮助.
NA

### Build Environment 构建环境

- OS: [e.g. Windows 10, macOS, Ubuntu]
- Theme version/commit [e.g. 0.2.0, 2ccba79]
- Hugo version [e.g. 0.69.0]
Windows 10, Google Chrome, 0.74

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android]
- Browser [e.g. Chrome, Safari, Firefox]
Windows 10, Google Chrome

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...
NA

**Comment by nekr0z** [comment]
Can't reproduce. Can you share at least the full `config.toml` and the full front-matter for the page in querstion?

**Comment by reachsumit** [comment]
Thanks for looking into this, @nekr0z  ! Here's the config.toml: https://justpaste.it/1qihp
Relevant section:
```
    [params.page.code]
      # whether to show the copy button of the code block
      # 是否显示代码块的复制按钮
      copy = true
      # the maximum number of lines of displayed code by default
      # 默认展开显示的代码行数
      maxShownLines = 10
```

Here's the header in my .md file:
```
---
weight: 1
title: "Decoding the LeetCode: Sliding Window Pattern Explained"
draft: false
date: 2020-10-26
lastmod: 2020-10-26
description: "Identifying patterns among questions is quite an effective strategy when you are grinding LeetCode in preparation for your upcoming software engineering interviews. In this article, you will develop intuitions about Sliding Window pattern. You will also get a template approach to write code to solve these problems. I will also walk you through some LeetCode questions to show how to apply the template and at the end, there will be some LeetCode exercises for you to practice what you learn."
tags: ["leetcode", "algorithms"]
categories: ["Software Engineering"]
aliases:
    - /leetcode-sliding-window/
maxShownLines: 30
---
```

The generated page is here: https://blog.reachsumit.com/posts/2020/10/leetcode-sliding-window/
I have up to 21 lines of Python code, but still the code is not fully displayed in markdown.

Please let me know if you need any additional detail.

**Comment by reachsumit** [comment]
Oh, and I'm on this Hugo version:

Hugo Static Site Generator v0.76.5-60F0725B windows/amd64 BuildDate: 2020-10-14T15:16:53Z

**Comment by nekr0z** [comment]
Yeah, you're holding it the wrong way(™).

See, the page-level parameters defined in the front-matter redefine [params.page]-scoped part of the `config.toml`. By doing what you did there you've redefined `params.page.maxShownLines` to the value of `30`, whereas the `params.page.code.maxShownLines` remained `10` as defined in your `config.toml` — and that's the parameter LoveIt is looking at when rendering.

For things to work the way you want them to, the front matter should look something like:
```
---
weight: 1
title: "Decoding the LeetCode: Sliding Window Pattern Explained"
draft: false
date: 2020-10-26
lastmod: 2020-10-26
description: "Identifying patterns among questions is quite an effective strategy when you are grinding LeetCode in preparation for your upcoming software engineering interviews. In this article, you will develop intuitions about Sliding Window pattern. You will also get a template approach to write code to solve these problems. I will also walk you through some LeetCode questions to show how to apply the template and at the end, there will be some LeetCode exercises for you to practice what you learn."
tags: ["leetcode", "algorithms"]
categories: ["Software Engineering"]
aliases:
    - /leetcode-sliding-window/
code:
    maxShownLines: 30
---
```

**Comment by reachsumit** [comment]
I see. Thank you for pointing out the mistake, @nekr0z ! I just tested in offline and it worked as expected after making the change as your recommendation. Thank you!! :)
