### ISSUE TITLE
建议 comments.html 中 Valine 配置项 meta 默认值改为与官方默认值一致

### ISSUE THREAD

**Issue by gears233** [dillonzq/LoveIt#55]
rt   在查看Valine 有关设置时，看到模板中 meta  值固定为 ["nick", "mail"],  建议在 config 中增加个配置项吧，meta = ['nick','mail','link'] ，网站地址的输入有时候还有有些作用的

**Comment by dillonzq** [comment]
谢谢建议，会尽快增加这个配置

**Comment by yangzhaoyunfei** [comment]
这一版你的Valine 评论系统能用吗，我的没生效啊，两三个前是有的，今天更新了一下，不显示了

**Comment by gears233** [comment]
> 这一版你的Valine 评论系统能用吗，我的没生效啊，两三个前是有的，今天更新了一下，不显示了

我这边没问题，你那边用不了的话 可以考虑手动改下 comments.html 页面里的一段配置

` new Valine({
            el: "#vcomments",
            appId: "{{ .Site.Params.valine.appId }}",
            appKey: "{{ .Site.Params.valine.appKey }}",
            meta: ['nick', 'mail',],
            notify: "{{ .Site.Params.valine.notify }}",
            verify: "{{ .Site.Params.valine.verify }}",
            avatar: "{{ .Site.Params.valine.avatar }}",
            placeholder: "{{ .Site.Params.valine.placeholder }}",
            visitor: "{{ .Site.Params.valine.visitor }}",
            recordIP: "{{ .Site.Params.valine.recordIP }}",
            lang: "{{ T `valineLang` }}",
        });
    })();`

上面的 如 "{{ ***** }}",这样的，直接按 Valine 官方的配置格式，修改相应的内容应该就可以了。

 comments.html 这个文件位于 \layouts\partials 下。然后，这个文件改动过后，config.toml 里面关于Valine的配置就不会对 改动部分生效了。

另外，建议你用模板后，把模板里面的内容按文件夹形式复制一份到 根目录下，这样子Hugo 生成的时候是优先使用 根目录下的配置的，没有的部分才是从模板找。以后，模板有关文件更新了，你就对比下改动的部分内容，有需要再修改或覆盖根目录下的文件。

**Comment by dillonzq** [comment]
哈喽，@yangzhaoyunfei 
你是在 `localhost` 调试吗？目前所有的评论系统在 `localhost` 上都不生效

**Comment by dillonzq** [comment]
哈喽，@gears233
已经在 #66 中改进

**Comment by yangzhaoyunfei** [comment]
> 哈喽，@yangzhaoyunfei
> 你是在 `localhost` 调试吗？目前所有的评论系统在 `localhost` 上都不生效

知道了，谢谢
