### ISSUE TITLE
[BUG] meta description is wrong

### ISSUE THREAD

**Issue by Th1nhNg0** [dillonzq/LoveIt#550]
This meta should be "description", not "Description"
https://github.com/dillonzq/LoveIt/blob/f787a4e5ad4edf60467658d10c286248dc5027a6/layouts/partials/head/meta.html#L3

**Comment by khusika** [comment]
> This meta should be "description", not "Description"
> https://github.com/dillonzq/LoveIt/blob/f787a4e5ad4edf60467658d10c286248dc5027a6/layouts/partials/head/meta.html#L3

This is right, you can do PR for it.
