### ISSUE TITLE
项目还在维护吗？

### ISSUE THREAD

**Issue by Gkirito** [dillonzq/LoveIt#552]
我看好多issues没有人回复了，请问这个项目还在维护吗？

**Comment by victor-pogor** [comment]
Hi @Gkirito 

Please see these issues: #565, #564, #563 and #514.

---
🔗 [https://github.com/sunt-programator/CodeIT](https://github.com/sunt-programator/CodeIT)

**Comment by Gkirito** [comment]
Wow Thx

**Comment by dillonzq** [comment]
See #672
