### ISSUE TITLE
评论组件不加载

### ISSUE THREAD

**Issue by HarrisonLee1998** [dillonzq/LoveIt#553]
### Describe the bug 描述你遇到的错误
无论是disqus还是gitalk，部署后都不加载。

一段简短的对于你遇到的错误的描述.
在配置文件设置了评论以及相应评论组件的enable为true，而且文章的comment也为true，但是部署后，还是不加载组件。

### Expected behavior 期待的行为
显示评论组件。

一段简短的对于你期待的行为的描述.
在配置文件中启用后，应该在页面中加载相应的组件。

### Screenshots 屏幕截图

如果可以的话, 提供屏幕截图对解决问题很有帮助.

### Build Environment 构建环境

- OS: [e.g. Windows 10, macOS, Ubuntu] Windows10
- Theme version/commit [e.g. 0.2.0, 2ccba79] 0.2.0
- Hugo version [e.g. 0.69.0] v0.78.1/extended windows/amd64

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android] Windows10
- Browser [e.g. Chrome, Safari, Firefox] Chrome

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...

**Comment by HarrisonLee1998** [comment]
在front matter中的设置应该是：
```yml
comment:
  enable: true
```
而不是
```yml
comment: true
```

**Comment by chienhsiang-hung** [comment]
disqus 還是不加載
