### ISSUE TITLE
Breathe a second life into the project / Fork

### ISSUE THREAD

**Issue by uPagge** [dillonzq/LoveIt#564]
Since the developer has unfortunately abandoned the project :disappointed:, I would like to take responsibility for its support and development in the future.

:link: -> https://github.com/uPagge/uBlogger.

I focused on adding new features, refreshed the design of the posts, fixed the bugs I found. 
There were so many changes (the ability to choose a separate design for the post, breadcrumbs, a new comment system and much more), and so much to do, that I decided to give the template a **new name uBlogger.**

**I will be glad if you look at it, you may like the updated design.**

**Comment by dillonzq** [comment]
See #672
