### ISSUE TITLE
[FEATURE] Call to maintain the theme on the new repository

### ISSUE THREAD

**Issue by victor-pogor** [dillonzq/LoveIt#565]
Hi all.

We all love this theme. But, as we have seen, this theme has not been supported since May 2020.

I tried to contact the owner of this repository, but he did not respond.

The contributors also opened the issue (#514) and asked if this repository is still maintained, but we also receive no response.

I decided to create a [`CodeIT 👩‍💻`](https://github.com/sunt-programator/CodeIT) theme and maintain it. So I call you to contribute to a new theme to improve and develop it 💡.

---

🔗[https://github.com/sunt-programator/CodeIT](https://github.com/sunt-programator/CodeIT)

**Comment by nirgn975** [comment]
I would love for this theme to keep on living.
I'll do what I can to help your maintain the new repo on CodeIT.

**Comment by dillonzq** [comment]
See #672
