### ISSUE TITLE
[BUG] 目录toc的当前位置识别偏移

### ISSUE THREAD

**Issue by LAShZ** [dillonzq/LoveIt#573]
### Describe the bug 描述你遇到的错误

侧边目录的当前位置识别总是识别到下一个标题处。demo网站中正常，将相同的配置信息复制过来后错误。

### Expected behavior 期待的行为

识别位置正常

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/43739446/105139324-1f34a100-5b31-11eb-8a53-0e50d5e0bd7e.png)
![image](https://user-images.githubusercontent.com/43739446/105139376-2eb3ea00-5b31-11eb-896f-28f786904169.png)

### Build Environment 构建环境

- OS: Windows 10
- Theme version/commit : f787a4e
- Hugo version : v0.80.0/extended

### Preview Environment 预览环境

- OS: Windows 10
- Browser: Chrome
### Additional Information 补充信息

Configuration files or front matter code:
配置文件或者前置参数的代码:

    # Table of the contents config
    # 目录配置
    [params.page.toc]
      # whether to enable the table of the contents
      # 是否使用目录
      enable = true
      # whether to keep the static table of the contents in front of the post
      # 是否保持使用文章前面的静态目录
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      # 是否使侧边目录自动折叠展开
      auto = false

**Comment by wang95** [comment]
配置文件里，目录默认级别是从H2开始的
```toml
[markup.tableOfContents]
  startLevel = 2
  endLevel = 6
```
看了一下你的文章，正文里面有H1标题
你可以改成 `startLevel = 1` 就行了。但是这个设置，在开启了目录自动折叠会有个小问题，见 #428 

不过 Markdown 语法，一个文档内不能有一个以上的H1标题 [MD-025](https://github.com/DavidAnson/markdownlint/blob/v0.22.0/doc/Rules.md#md025)，因为文章标题已经是H1了，正文里面就不要再用H1标题了

**Comment by LAShZ** [comment]
> 配置文件里，目录默认级别是从H2开始的
> 
> ```toml
> [markup.tableOfContents]
>   startLevel = 2
>   endLevel = 6
> ```
> 
> 看了一下你的文章，正文里面有H1标题
> 你可以改成 `startLevel = 1` 就行了。但是这个设置，在开启了目录自动折叠会有个小问题，见 #428
> 
> 不过 Markdown 语法，一个文档内不能有一个以上的H1标题 [MD-025](https://github.com/DavidAnson/markdownlint/blob/v0.22.0/doc/Rules.md#md025)，因为文章标题已经是H1了，正文里面就不要再用H1标题了

已经解决，感谢
