### ISSUE TITLE
[BUG] Markdown 标题渲染错误

### ISSUE THREAD

**Issue by MekaYangyi** [dillonzq/LoveIt#580]
### Describe the bug 描述你遇到的错误

Markdown ##第二级标题会多显示#号

### Screenshots 屏幕截图

https://hugoloveit.com/zh-cn/theme-documentation-built-in-shortcodes/

![image](https://user-images.githubusercontent.com/20621802/107111112-37722300-6888-11eb-8fed-bfd328968819.png)

### Build Environment 构建环境

- OS:  window10
- Theme version/commit：f787a4e5ad4edf60467658d10c286248dc5027a6
- Hugo version ：8.0

**Comment by CindyCyber** [comment]
这个不是bug，是锚点，在目录里面点击这个标题，就会定位到这个锚点处。
