### ISSUE TITLE
[BUG?] featured-image-preview now work

### ISSUE THREAD

**Issue by Ryuyxx** [dillonzq/LoveIt#582]
### Describe the bug 描述你遇到的错误

- featured-image now work
- Do I need to configure something in `config.toml`?

### Expected behavior 期待的行为
- image for the content preview in the home page

### Screenshots 屏幕截图

<img width="746" alt="Screen Shot 2021-02-06 at 16 21 16" src="https://user-images.githubusercontent.com/69892552/107112576-fedc4480-689b-11eb-908e-0bb237466cda.png">
<img width="304" alt="Screen Shot 2021-02-06 at 16 21 02" src="https://user-images.githubusercontent.com/69892552/107112578-026fcb80-689c-11eb-90e7-8c4383e6e20d.png">
<img width="252" alt="Screen Shot 2021-02-06 at 16 20 51" src="https://user-images.githubusercontent.com/69892552/107112588-1287ab00-689c-11eb-892c-ef32984cc929.png">

### Build Environment 

- OS: macOS
- Theme version `not sure`
- Hugo version v0.80.0

**Comment by uPagge** [comment]
most likely it only works for posts in a folder. That is, create a separate folder / posts / my_post / put files in it and rename the md file to index.md

P.S. this project is abandoned, I support the fork

https://github.com/uPagge/uBlogger

**Comment by Ryuyxx** [comment]
Appreciate your reply.

The problem was solved by renaming the file to `index.md`.

I'll check out your fork sometime:+1:

**Comment by Ryuyxx** [comment]
I tried a few things, but can't this select an image on the URL?
Do I always have to have the image locally?
