### ISSUE TITLE
[BUG] The `favicon` only works in the local environment.

### ISSUE THREAD

**Issue by 3ru** [dillonzq/LoveIt#583]
### Describe the bug 

favicon not work in `public` environment. However, its **work on my local environment**.

This might be related to #331 

- `public` source
When I click `../favicon.ico` -> `404 error`
```
<link rel="shortcut icon" type=image/x-icon href=../favicon.ico>
```

- my tree
```
├───static
│   │   android-chrome-192x192.png
│   │   apple-touch-icon.png
│   │   browserconfig.xml
│   │   cover.png
│   │   favicon-16x16.png
│   │   favicon-32x32.png
│   │   favicon.ico
│   │   logo.png
│   │   mstile-150x150.png
│   │   safari-pinned-tab.svg
│   │   site.webmanifest
```

**Comment by dillonzq** [comment]
@3ru maybe you should use absPath of your favicon `../favicon.ico` -> `/favicon.ico`

**Comment by 3ru** [comment]
I don't remember what I fixed myself, but it now appears normally.
