### ISSUE TITLE
Some problem when customing fonts 修改字体时遇到的问题

### ISSUE THREAD

**Issue by CindyCyber** [dillonzq/LoveIt#585]
我想修改文章中代码块的字体为[Consolas-with-Yahei](https://github.com/CindyCyber/Consolas-with-Yahei)
我已经下载了hugo-extend
请问如何将代码块的字体更改为这个呢？顺带问一下如何调整字号，代码块字号有点小。
看了文档，那个方法好像不适用于我想改的这个字体。
感谢阅读。

I want change the font of codeblock into [Consolas-with-Yahei](https://github.com/CindyCyber/Consolas-with-Yahei)
I've downloaded the hugo-extend
Please tell me how to apply this change. BTW, how can I adjust the font size of codeblock, it seems a little bit small.
I've read the document, the solution isn't work with the font I want.
Thanks for reading.

**Comment by CindyCyber** [comment]
已经解决了，安装了extended版本没有替换掉旧版本。

**Comment by xiaohao890809** [comment]
请问下怎么自定义字体呢？

**Comment by riokaa** [comment]
> 请问下怎么自定义字体呢？

https://hugoloveit.com/zh-cn/theme-documentation-basics/#34-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
