### ISSUE TITLE
[FEATURE] Is it possible to add the "Top of Articles" function? | 是否可以添加“文章置顶”功能？

### ISSUE THREAD

**Issue by misitebao** [dillonzq/LoveIt#589]
### Describe the feature you want 描述你的功能需求

- Feature 1 功能需求 1
In order to let others see a certain article 100%, I hope to add an article to the top function to avoid the situation that important articles are not displayed due to chronological order | 为了让别人可以百分百看到某一篇文章，我希望可以新增一个文章置顶功能以避免因为时间先后顺序而导致重要的文章不被显示的情况

### Useful reference 有价值的参考
This is a feature that many blog sites have, and it is also used by many people, but I did not see it in the documentation. | 这是很多博客网站都有的一个功能，而且也被很多人使用，然而我在文档里面并没有看到它。

**Comment by CindyCyber** [comment]
其实可以通过调整文章权重来解决，你在文章默认参数里面加入weight参数，修改它的值就可以达到置顶效果了。这样的好处是，还可以同时置顶多篇文章。

**Comment by misitebao** [comment]
@CindyCyber 好的，感谢大佬😇。
