### ISSUE TITLE
Add syntax highlighter for R

### ISSUE THREAD

**Issue by idrusfachr** [dillonzq/LoveIt#59]
Hi,
Thank you for your great work! Just wonder of how to add syntax highlighter for R programming? Is there already available and we just need to set params on config file or it needs further development?

Thank you in advance.

**Comment by shanepiesik** [comment]
R syntax highlighting works for R in .md files but does not work in .Rmd

**Comment by shanepiesik** [comment]
Following these steps will get you R syntax highlighting in .Rmd files there https://bookdown.org/yihui/blogdown/templates.html#how-to

**Comment by dillonzq** [comment]
@idrusfachr 
The default R syntax highlighting looks like:
![image](https://user-images.githubusercontent.com/30786232/74095617-68f9c680-4b2e-11ea-9535-df201f6eb9ec.png)

You could edit `config/css/_custom.css` in your project folder to override the variables in `assets/css/_variables.scss` in the LoveIt folder to customize the highlighting style.

**Comment by dillonzq** [comment]
:grin: I'm considering improving the color scheme of the syntax highlighting.

**Comment by idrusfachr** [comment]
> R syntax highlighting works for R in .md files but does not work in .Rmd

I tried both .Rmd and .md but still doesn't work.


> @idrusfachr
> The default R syntax highlighting looks like:
> ![image](https://user-images.githubusercontent.com/30786232/74095617-68f9c680-4b2e-11ea-9535-df201f6eb9ec.png)
> 
> You could edit `config/css/_custom.css` in your project folder to override the variables in `assets/css/_variables.scss` in the LoveIt folder to customize the highlighting style.

That looks good to me. How can I activate this? Do i need to set parameter on my config file? Since using the default parameter still doesn't work in .md and .Rmd file. Like this:
![Capture](https://user-images.githubusercontent.com/16331835/74097702-01e60d00-4b42-11ea-8077-2bc09aabb602.PNG)

**Comment by dillonzq** [comment]
@idrusfachr Is your original Markdown document like this?
![image](https://user-images.githubusercontent.com/30786232/74098989-71b3c200-4b59-11ea-989d-00cf3b6494c9.png)

**Comment by idrusfachr** [comment]
Hi @dillonzq,

I get this on .md file
![image](https://user-images.githubusercontent.com/16331835/74099864-9f4d3b00-4b5a-11ea-94d1-03701cf6db9d.png)

and this on .Rmd file
![image](https://user-images.githubusercontent.com/16331835/74099923-213d6400-4b5b-11ea-9eb5-b2a9a3234e6e.png)

But both return this when rendered to html
![image](https://user-images.githubusercontent.com/16331835/74099899-f5ba7980-4b5a-11ea-844b-eb05c2cfa413.png)

**Comment by dillonzq** [comment]
@idrusfachr
Is the highlight configuration in your config file like this?
![image](https://user-images.githubusercontent.com/30786232/74104402-48ae2400-4b8f-11ea-9708-1c88d9a0cb00.png)

**Comment by idrusfachr** [comment]
@dillonzq Finally fixed by set `pygmentsUseClasses = false` in my config file

**Comment by pablocal** [comment]
I'm in the same situation as @idrusfachr above. I really like this Hugo theme but I normally use data and output in my posts so I use .Rmd instead of markdown. 

The syntax highlight does not work. I have tried to customise the css with no success. Could you give a brief indication of how to do so. 

@idrusfachr where about of the config file did you set `pygmentsUseClasses = false` ?

**Comment by idrusfachr** [comment]
> @idrusfachr where about of the config file did you set `pygmentsUseClasses = false` ?

Hi @pablocal , I putted it [here](https://github.com/idrusfachr/hugo-blog/blob/master/config.toml). Look at line 18 - 22.
