### ISSUE TITLE
[FEATURE] 代码样式精简

### ISSUE THREAD

**Issue by devcxl** [dillonzq/LoveIt#591]
### 代码样式精简

代码折叠这个功能非常好,

但是例如下面这样都是短代码的情况

会让人感觉写的文章比较杂乱
 
![图片](https://user-images.githubusercontent.com/64475363/111624844-27564780-8827-11eb-87c4-b44865cf3d20.png)

所以,能不能改为在代码行数超出一定数目(可以手动设置)时才加入代码折叠功能

**Comment by backsided** [comment]
这种情况直接用行内代码就可以了
