### ISSUE TITLE
所以爱是会消失的对吗？So Love will disappear, right?

### ISSUE THREAD

**Issue by HEIGE-PCloud** [dillonzq/LoveIt#597]
明明是一个叫LoveIt的主题，现在看上去却是完全被抛弃了。我很喜欢这个主题，并愿意继续维护下去，所以遵守MIT协议基于LoveIt主题创建了[DoIt](https://github.com/HEIGE-PCloud/DoIt)主题。如果你正在使用LoveIt主题并发现一些问题，可以试着无痛迁移至DoIt主题。当然，DoIt主题仍然处于非常初始的阶段，相关问题可能依然存在。但至少有人能读到你的issue，社区提交的pull requests也会被尽快合并。谢谢。

Although it is a theme called LoveIt, it now seems to be completely abandoned. I like this theme very much and I am willing to continue to maintain it, so I created the [DoIt](https://github.com/HEIGE-PCloud/DoIt) theme based on the LoveIt theme in compliance with its MIT license. If you are using the LoveIt theme and find some bugs, you can try to migrate to the DoIt theme effortless. Of course, the DoIt theme is still in a very initial stage, and related problems may still exist. But at least someone can read your issue, and pull requests submitted by the community will be merged as soon as possible. Many thanks.

**Comment by sosiristseng** [comment]
FYI, there are two themes based on LoveIt and are actively maintained besides yours:

https://github.com/sunt-programator/CodeIT (This one is closer to LoveIT)

https://github.com/uPagge/uBlogger (the author made several modifications to it)

**Comment by SpongeBab** [comment]
hhh，如果愿意的话，我想和你一起继续维护这个主题，虽然我最近在学习计算机视觉，只是在本科学过html，不是太熟悉

**Comment by HEIGE-PCloud** [comment]
@SpongeBab 没有问题呀！向你发送了collaborator邀请 :)

**Comment by SpongeBab** [comment]
我好菜，github上找不到你的邀请:o

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/115956304-04891400-a4f4-11eb-87d1-16c98820a5f3.png)

@SpongeBab 看上去你已经成功接受了邀请并称为了collaborator！很棒！现在你已经可以创建自己的branch并开始提交commit了 :)

更多的问题可以通过我的邮箱`heige.pcloud@outlook.com`来联络我。尽量不继续污染这个issue了~

**Comment by cityiron** [comment]
> ![image](https://user-images.githubusercontent.com/52968553/115956304-04891400-a4f4-11eb-87d1-16c98820a5f3.png)
> 
> @SpongeBab 看上去你已经成功接受了邀请并称为了collaborator！很棒！现在你已经可以创建自己的branch并开始提交commit了 :)
> 
> 更多的问题可以通过我的邮箱`heige.pcloud@outlook.com`来联络我。尽量不继续污染这个issue了~

可以邀请下我吗？虽然我只是个服务端开发，不过觉得这个主题很好，想能继续用下去

**Comment by SpongeBab** [comment]
OK, Anyone who wants to continue to contribute to this repository,please new issue in the [DoIt](https://github.com/orgs/Hugo-DoIt).Or come here[https://github.com/Hugo-DoIt/DoIt/issues](https://github.com/Hugo-DoIt/DoIt/issues),I will invite you to contribute together.
Don' bother the repo.

**Comment by HEIGE-PCloud** [comment]
> > ![image](https://user-images.githubusercontent.com/52968553/115956304-04891400-a4f4-11eb-87d1-16c98820a5f3.png)
> > @SpongeBab 看上去你已经成功接受了邀请并称为了collaborator！很棒！现在你已经可以创建自己的branch并开始提交commit了 :)
> > 更多的问题可以通过我的邮箱`heige.pcloud@outlook.com`来联络我。尽量不继续污染这个issue了~
> 
> 可以邀请下我吗？虽然我只是个服务端开发，不过觉得这个主题很好，想能继续用下去

发送了邀请。我想声明，collaborator只适用于想要长期维护这个项目的同学，你可能需要频繁地抽出时间来review changes或discuss ideas。单纯地想要提交一些commits的话直接fork了pull request就行了。

**Comment by khusika** [comment]
I'm still using this theme as base beside there are lot of user try to manage this theme on the other forked project.

- Revamped UI display (Both Mobile & Desktop)
- Improve responsive UI
- Optimize all CSS and HTML resources under [w3.org](https://www.w3.org/) (_no more warns were reported_)
- Optimize home-page with LightHouse: 100 score on SEO/A18Y/BestPractice, and 98-100 score on Performance
- Upgrade all available libraries
- Remove some deprecated codes
- Add more comment system
- Improve command-line-interface and continuous-integration cycle with [Github-Actions](https://github.com/features/actions)
- Automatically remove unused JavaScript and CSS codes
- Stable for personal use

I still keep this changes as private projects called [FeelIt](https://github.com/khusika/FeelIt). 
If you are interesting with my changes see the demo in [khusika.com](https://khusika.com).

![HTML Validator](https://img.shields.io/github/workflow/status/khusika/khusika.github.io/HTML%20Validator?label=HTML%20Validator&style=flat-square)

**Comment by dillonzq** [comment]
See #672
