### ISSUE TITLE
valine无法关闭验证？

### ISSUE THREAD

**Issue by hhaiyun** [dillonzq/LoveIt#6]
config里verify = false后依然有数字验证

**Comment by skycity233** [comment]
必须要同时设定notify为false，这是避免有人恶意轰炸你的邮箱

**Comment by dillonzq** [comment]
根据 [Valine 的 Wiki 说明](https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE):
![image](https://user-images.githubusercontent.com/30786232/73332925-3553ac80-42a3-11ea-986b-d4c8f06eb24d.png)
