### ISSUE TITLE
[FEATURE] Waline支持

### ISSUE THREAD

**Issue by zhshch2002** [dillonzq/LoveIt#600]
### Describe the feature you want 描述你的功能需求

支持Waline评论组件。

Support Waline comment component.

### Useful reference 有价值的参考

我从上一个站点迁移过来，原先使用的就是Waline。

https://waline.js.org/

**Comment by zhou-tiandi** [comment]
> ### Describe the feature you want 描述你的功能需求
> 支持Waline评论组件。
> 
> Support Waline comment component.
> 
> ### Useful reference 有价值的参考
> 我从上一个站点迁移过来，原先使用的就是Waline。
> 
> https://waline.js.org/

Hi, I suggest you have a look at this [theme](https://github.com/HEIGE-PCloud/DoIt)
你好，建议看看这个主题
