### ISSUE TITLE
If you miss with LoveIt, you have to FeelIt this project :)

### ISSUE THREAD

**Issue by khusika** [dillonzq/LoveIt#608]
# FeelIt Theme | Hugo [![Netlify Status](https://api.netlify.com/api/v1/badges/6c8cd9a1-4916-4705-b286-dce0930b9217/deploy-status)](https://app.netlify.com/sites/hugofeelit/deploys)

[![GitHub release (latest by date)](https://img.shields.io/github/v/release/khusika/FeelIt?style=flat-square)](https://github.com/khusika/FeelIt/releases)[![Hugo](https://img.shields.io/badge/Hugo-%5E0.84.0-ff4088?style=flat-square&logo=hugo)](https://gohugo.io/)[![License](https://img.shields.io/github/license/khusika/FeelIt?style=flat-square)](https://github.com/khusika/FeelIt/blob/main/LICENSE)
Hi everyone, i'm here to share another fork project based on LoveIt with the new looks and various fixes called [FeelIt](https://feelit.khusika.com)

Let's see how you can FeelIt this project via [feelit.khusika.com](https://feelit.khusika.com).
See how the changes made in the [release notes](https://github.com/khusika/FeelIt/releases), or simplify go to the [FeelIt Basic Theme Documentations](https://feelit.khusika.com/theme-documentation-basics/)

Feel free to follow or contribute to the FeelIt project
Source Codes: [github.com/khusika/FeelIt](https://github.com/khusika/FeelIt)

This issue is fulfilled for #514 #563
Also a different projects from #564 #565 #597

-signed-off: [Khusika](https://khusika.com)

**Comment by tbm98** [comment]
@khusika Thank you! :D

**Comment by oktayaa** [comment]
khusika, your is the only fork that I've seen doesn't work as a drop-in replacement. What needs to be done to migrate an existing loveit site to it? I made no modifications to the theme.

**Comment by dillonzq** [comment]
See https://github.com/dillonzq/LoveIt/issues/672
