### ISSUE TITLE
[FEATURE] 文章的目录增加可折叠功能

### ISSUE THREAD

**Issue by Zhang21** [dillonzq/LoveIt#610]
### Describe the feature you want 描述你的功能需求

- Feature 1 功能需求 1
 
我希望能够增加文章目录的可折叠功能，我需要看目录的时候点开，不需要看的时候关闭。

<br>

If available, provide useful links to fulfill the feature.
如果可以的话, 提供实现这个功能的相关参考链接.

我之前使用的是hexo Next主题，有这个功能。

<br>

打开和关闭目录效果：

![image](https://user-images.githubusercontent.com/18358275/122191266-29cb4a80-cec5-11eb-9f24-37df39af0158.png)

![image](https://user-images.githubusercontent.com/18358275/122191527-67c86e80-cec5-11eb-8e8d-823e19fc14b1.png)

<br>

希望可以折叠LoveIt的文章目录：

![image](https://user-images.githubusercontent.com/18358275/122191777-9b0afd80-cec5-11eb-9f14-de16c63b8dff.png)

**Comment by Zhang21** [comment]
还有一个疑问，目录里面为啥不支持一级标题(`#`)，而是从二级标题(`##`)开始计算目录的？

**Comment by Zhang21** [comment]
> > 还有一个疑问，目录里面为啥不支持一级标题(`#`)，而是从二级标题(`##`)开始计算目录的？
> > 我之前hexo Next中，一级标题(`#`)没有用来定义文章名称，而是直接定义的标题。这样导致我原来hexo里面的文章，在LoveIt里，一级目录无效，而从二级目录开始算起。
> 
> markdown里一级标题转到 html里就是 `<h1></h1>`，一般的 html规范里是作为网站标题吧。参考：https://docs.microsoft.com/en-us/contribute/markdown-reference#headings
> 
> > * There must be a space between the last # and heading text.
> >   Each Markdown file must have one and only one H1 heading.
> > * The H1 heading must be the first content in the file after the YML metadata block.
> > * H2 headings automatically appear in the right-hand navigating menu of the published file. Lower-level headings don't > appear, so use H2s strategically to help readers navigate your content.
> > * HTML headings, such as <h1>, aren't recommended, and in some cases will cause build warnings.
> > * You can link to individual headings in a file via bookmark links.

这样我从hexo nexT转换的话就太麻烦了，文章目录结构全变了。

可能后面我需要修改自己写文章的目录结构了, `#`(一级标题)給文章题目，`##`二级标题开始写各章节。

谢谢提醒。

**Comment by Lruihao** [comment]
可以设置 h1~h6 的
![image](https://user-images.githubusercontent.com/33419593/144557631-614fcf25-c187-4355-a79f-943ec1b1db3d.png)

**Comment by Zhang21** [comment]
> > 还有一个疑问，目录里面为啥不支持一级标题(`#`)，而是从二级标题(`##`)开始计算目录的？
> 
> @Zhang21 可以设置 h1~h6 的 ![image](https://user-images.githubusercontent.com/33419593/144557631-614fcf25-c187-4355-a79f-943ec1b1db3d.png)

我试下，阿里嘎多。

**Comment by Zhang21** [comment]
@Lruihao 可以了，阿里嘎多。

hugo渲染速度确实比hexo快多了。

**Comment by Lruihao** [comment]
@Zhang21 你还在用 LoveIt 主题吗，我 fork 了 LoveIt 做了一些 bug 修复也有新加一些功能，你可以试试看 https://github.com/Lruihao/FixIt

**Comment by Zhang21** [comment]
> @Zhang21 你还在用 LoveIt 主题吗，我 fork 了 LoveIt 做了一些 bug 修复也有新加一些功能，你可以试试看 https://github.com/Lruihao/FixIt


谢谢！
