### ISSUE TITLE
[FEATURE] Customize previous and next post/page links in footer

### ISSUE THREAD

**Issue by curio-sitas** [dillonzq/LoveIt#621]
### Description

add a "next" and "prev" field in the markdown metadata to customize previous and next post/page links in the footer.

This could be usefull for series of articles that present a chapter-like structure

**Comment by dillonzq** [comment]
Fixed in [d2d66e5](https://github.com/dillonzq/LoveIt/issues/d2d66e5163f1b1d7ad69a80e3e11fb73dc15ac69)
