### ISSUE TITLE
添加脚注后推送内容和目录出现重叠

### ISSUE THREAD

**Issue by bugsuse** [dillonzq/LoveIt#63]
<img width="972" alt="1" src="https://user-images.githubusercontent.com/16102453/74152925-54aaec00-4c4a-11ea-8515-fae11ae89a31.png">

如图。不知道是不是我哪里设置的问题，推送中添加脚注后，出现了上面的现象。此推送链接：http://www.i-lightning.cn/2020/02/wrf%E6%A8%A1%E5%BC%8F%E5%89%8D%E5%A4%84%E7%90%86wps/#%E5%8F%82%E8%80%83%E9%93%BE%E6%8E%A5

**Comment by dillonzq** [comment]
哈喽，@bugsuse
这是 CSS 中对 `<a>` 标签的 `word-break` 设置问题，会尽快修复

**Comment by dillonzq** [comment]
Fixed in #71
