### ISSUE TITLE
请问下主页的这个图标是怎么加上去的呢？

### ISSUE THREAD

**Issue by xiaohao890809** [dillonzq/LoveIt#632]
请问下主页的这个图标是怎么加上去的呢？看起来像Font Awesome，但是我加进去就报错了

<img width="1234" alt="WX20211118-001459@2x" src="https://user-images.githubusercontent.com/9626465/142238553-1ed8d5fa-4baa-46c8-93a6-91816c09d3f9.png">

**Comment by sugarlesss** [comment]
看 css 名称是 Font Awesome
