### ISSUE TITLE
如何启用侧边栏目录

### ISSUE THREAD

**Issue by LomotHo** [dillonzq/LoveIt#65]
![image](https://user-images.githubusercontent.com/16211479/74215492-3ab9e980-4cdc-11ea-93d0-717e150dae0b.png)
如图

**Comment by dillonzq** [comment]
哈喽，@LomotHo 
在你的文章中设置如下
![image](https://user-images.githubusercontent.com/30786232/74217923-cd11bb80-4ce3-11ea-9bc2-9e0fea213e7b.png)

**Comment by LomotHo** [comment]
谢谢！

**Comment by beihai0xff** [comment]
> 哈喽，@LomotHo 在你的文章中设置如下 ![image](https://user-images.githubusercontent.com/30786232/74217923-cd11bb80-4ce3-11ea-9bc2-9e0fea213e7b.png)

已有的存量文章如何全局开启呢？
