### ISSUE TITLE
[BUG] KaTeX mathematical formulas are not expressed.

### ISSUE THREAD

**Issue by YoungEun-IN** [dillonzq/LoveIt#651]
### Describe the bug 描述你遇到的错误

一段简短的对于你遇到的错误的描述.

I cannot express more than two lines of a formula using a block delimiter.
I want to express the following formula using KaTeX.
$$ y = \begin{cases} 0 \qquad (b + w_1x_1 + w_2x_2 \leq 0) \\
1 \qquad (b + w_1x_1 + w_2x_2  > 0) \end{cases}$$
However, the formula is not expressed.

### Expected behavior 期待的行为

一段简短的对于你期待的行为的描述.

### Screenshots 屏幕截图
![image](https://user-images.githubusercontent.com/46465928/154807177-5001191d-d561-4fff-8cb6-49623f093911.png)
![image](https://user-images.githubusercontent.com/46465928/154807200-c6a7ce5f-23ee-4c33-82ef-4623e9439609.png)
![image](https://user-images.githubusercontent.com/46465928/154807212-0f9e0edd-ff46-43e1-be1b-4f7ab29b1889.png)

如果可以的话, 提供屏幕截图对解决问题很有帮助.

### Build Environment 构建环境

- OS: Windows 10
- Theme version/commit : [c752a47]
- Hugo version : 0.92.0

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

I am using ** Hugo extended version **.

### Preview Environment 预览环境

- OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android]
- Browser [e.g. Chrome, Safari, Firefox]

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...

**Comment by kissingfire123** [comment]
Hi @YoungEun-IN  ， 首先你的公式本来就有问题，标准的`KaTeX` **行尾换行**是用`\\`，而不是`\`。  
可以在[Katex官方在线语法测试网站](https://katex.org/#demo) 进行验证。  

--------------------  

**我也发现了LoveIt主题的这个bug**，`\\`也没办法换行，要用`\\\\`才能换行，以及公式中使用`\\;`来表示空格，而非标准的`\;`。    
_个人猜测是本Hugo主题对反斜杠在公式中使用时候的转义处理有点问题。_
麻烦 @dillonzq  关注一下，抱歉突然的cue，因为我并不知道怎么修改。。。

**Comment by kissingfire123** [comment]
附上我的一篇文章，通篇都是通过work-around来解决公式换行这个问题的：[My blog:数学公式katex常用语法总结](https://kissingfire123.github.io/2022/02/18_数学公式katex常用语法总结/) ，希望哪位大神能早日解决这问题，谢谢～

**Comment by kissingfire123** [comment]
`回复我自己`：这个问题和LoveIt主题无关，是Hugo的Markdown解释器的问题，0.60.0版本之后，不使用mmark，转而投入goldmark怀抱。mmark现在是deprecated的状态，hugo-v0.92.0未来几个版本内彻底移除。
**所以在v0.92.0之前** 可以在markdown的题头加一句：
```yaml
markup : "mmark"
```
会看到hugo终端报warning，但是能用`\\`换行了，而不是`\\\\`。
> 参考链接：
> - https://github.com/dillonzq/LoveIt/issues/402
> - https://github.com/wowchemy/wowchemy-hugo-themes/issues/1568

**Comment by kissingfire123** [comment]
建议Close该问题 @YoungEun-IN

**Comment by timerring** [comment]
提供一个v0.92.0之后的解决方法：

https://github.com/gohugoio/hugo-goldmark-extensions?tab=readme-ov-file#passthrough-extension

在你的 config.toml 中添加

sample:
```
[markup.goldmark.extensions.passthrough]
    enable = true
[markup.goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)']]
```

这样不需要再对 括号或者_ 转义的同时，也不再需要 \\\\ 代替 \\ 了。
