### ISSUE TITLE
[BUG] 文章页面logo无法显示

### ISSUE THREAD

**Issue by yangliuly1** [dillonzq/LoveIt#656]
### Describe the bug 描述你遇到的错误

文章页面logo无需显示

### Expected behavior 期待的行为

想让文章页面的logo正常显示

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/43691492/156600901-b40fb33e-db0f-406c-a363-f9a5609be857.png)

![image](https://user-images.githubusercontent.com/43691492/156600487-0cf30f6c-3ce9-4b42-9a33-f11fd890d7d8.png)

![image](https://user-images.githubusercontent.com/43691492/156600936-bdc8c317-bc68-4eb7-b0e3-02ceaa1b542d.png)

### Build Environment 构建环境

- OS: Windows 10
- Theme version 0.2.x
- Hugo version  0.92  extended

### Preview Environment 预览环境

- OS: Windows 10
- Browser:Chrome

**Comment by kissingfire123** [comment]
我和你同版本呢。
话说，是否是logo.png没放对位置呢？根目录有个static文件夹，我的文件是 `static/img/home-logo.ico` ，所以这行我就写：
```toml
logo = "/img/home-logo.ico"
```

**Comment by yangliuly1** [comment]
> 我和你同版本呢。 话说，是否是logo.png没放对位置呢？根目录有个static文件夹，我的文件是 `static/img/home-logo.ico` ，所以这行我就写：
> 
> ```toml
> logo = "/img/home-logo.ico"
> ```

感谢你的回复，已经解决了，确实是路径不对。
