### ISSUE TITLE
[FEATURE] Custom CSS/theme?

### ISSUE THREAD

**Issue by OxNinja** [dillonzq/LoveIt#666]
### Describe the feature you want 描述你的功能需求

Is it possible to add a way to change the default theme/colors? For example change from blue to green or red... Maybe I missed that in the existing issues, but it would be nice to being able to change the colors of the theme :smile:

**Comment by tomaja-linuxo** [comment]
Custom style can be added in assets/css/_override.scss/

**Comment by OxNinja** [comment]
Seems that I can't override the SCSS, in my `/path/to/project/assets/css/_override.scss`:

```scss
$single-link-color: #bd2d2d !default;
$single-link-color-dark: #e25555 !default;

$single-link-hover-color: #bd2d2d !default;
$single-link-hover-color-dark: #e25555 !default;

$code-color-dark: #e66969 !default;
$code-font-size: .8rem !default;
$code-background-color: #f4f4f4 !default;
```
After `hugo serve`, no changes in the theme

`hugo v0.98.0+extended linux/amd64`

**Comment by nekr0z** [comment]
> no changes in the theme

Why should there be any changes with your `_override.scss`? You are [misusing](https://sass-lang.com/documentation/variables#default-values) the `!default` flag, so your variable assignments can never work (according to the Sass language specification). Remove all the `!default` flags and try again.

**Comment by OxNinja** [comment]
Thanks this is working! I lack some knowledge about SCSS
