### ISSUE TITLE
[FEATURE] 添加 leancloud 计数功能

### ISSUE THREAD

**Issue by XXiaoA** [dillonzq/LoveIt#673]
### Describe the feature you want 描述你的功能需求
添加 leancloud 统计网站的pv，uv……

### Useful reference 有价值的参考
<https://blog.csdn.net/u013553529/article/details/63357382>

**Comment by Lruihao** [comment]
@XXiaoA [FixIt](https://github.com/hugo-fixit/FixIt) 主题已支持该功能，欢迎使用👏

**Comment by XXiaoA** [comment]
> @XXiaoA [FixIt](https://github.com/hugo-fixit/FixIt) 主题已支持该功能，欢迎使用clap

你好，我好像没有看见该功能。只有卜算子统计

**Comment by Lruihao** [comment]
> > @XXiaoA [FixIt](https://github.com/hugo-fixit/FixIt) 主题已支持该功能，欢迎使用clap
> 
> 你好，我好像没有看见该功能。只有卜算子统计

不好意思我没有仔细看，leancloud 计数功能没有单独的，只有附属于 leancloud 的评论系统有提供。 已经建了 issue [FixIt#178](https://github.com/hugo-fixit/FixIt/issues/178)
