### ISSUE TITLE
Unable to Deply

### ISSUE THREAD

**Issue by WrestlingMob** [dillonzq/LoveIt#680]
I'm using cloudflare pages, and when trying to deploy, I get the following error: 

`<pre class="c_kb c_bp c_pb c_rv c_rt c_ru c_cx c_um c_ml c_mj c_mk c_gk c_gl c_br c_tv">

23:57:00.258 | Executing user command: hugo
-- | --
23:57:00.328 | Error: "/opt/buildhome/repo/themes/LoveIt/layouts/partials/assets.html:11:1": parse failed: template: partials/assets.html:11: function "merge" not defined
23:57:00.338 | Failed: build command exited with code: 255
23:57:01.145 | Failed: an internal error occurred

</pre>`

what's going on?

**Comment by dillonzq** [comment]
@WrestlingMob Please use the bug issue template to create an issue. Your problem seems to be an incorrect version of Hugo. Which version of Hugo are you using?

**Comment by WrestlingMob** [comment]
I’m sorry. I’m using my phone. When I tapped to type the format went away. 

I set the environment variable in cloud flare pages to 0.98.0 per their documentation. I believe my GitHub has my source uploaded if you want to take a look. I’m currently putting my child to sleep my apologies for the headache but I appreciate you.
