### ISSUE TITLE
[BUG] Liquid Exception on GitHub deployment

### ISSUE THREAD

**Issue by Renardjojo** [dillonzq/LoveIt#683]
### Describe the bug 描述你遇到的错误

 Hey ! I try to host my blog in github with your theme but I have an exception on exampleSite folder:

 Liquid Exception: Liquid syntax error (line 26): Variable '{{</* style "text-align:right; strong{color:#00b1ff;}' was not properly terminated with regexp: /\}\}/ in themes/LoveIt/exampleSite/content/posts/theme-documentation-extended-shortcodes/index.en.md

### Build Environment 构建环境

- OS: Windows 10
- Theme version/commit: c87b6a5108324e42c3bcf59e1e48191aa72a62a8
- Hugo version:  v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1

### Preview Environment 预览环境

- OS: Windows 10
- Browser: firefox

### Additional Information 补充信息

[Here ](https://github.com/Renardjojo/renardjojo.github.io/runs/6614437421?check_suite_focus=true) a link to the pipeline error

**Comment by dillonzq** [comment]
@Renardjojo Take a look at [this issue](https://github.com/gcushen/hugo-academic/issues/959#issuecomment-468005772).
Probably you are pushing your site source, not the built content, into your repository. GitHubPages does not build Hugo projects, only Jekyll ones.

[Here](https://gohugo.io/hosting-and-deployment/hosting-on-github/) you can find at least three ways to host hugo projects with GHPages.

**Comment by smitz94** [comment]
Hi @dillonzq I faced the same issue but I resolved it by adding **.nojekyll** file in the main branch. Thank you for the theme by the way. I came searching for solution here but as I resolved it sharing my input.

**Comment by spy-cuttfish** [comment]
> Hi @dillonzq I faced the same issue but I resolved it by adding **.nojekyll** file in the main branch. Thank you for the theme by the way. I came searching for solution here but as I resolved it sharing my input.

Thanks, your solution is very helpful
