### ISSUE TITLE
[BUG] giscus setting

### ISSUE THREAD

**Issue by Cyan-Zhou** [dillonzq/LoveIt#686]
### Describe the bug 描述你遇到的错误
在之前版本中自己设置了 giscus，方法是直接把 giscus 官网生成的代码放在 /layouts/comment.html 里，简单粗暴，非常有效，但是问题是一方面有主题切换时 giscus 不能同步的问题，另一方面想要设置某些页面不显示评论区（比如 about 页面），而这时在文章中添加 comment: enable: false 并不能实现这一效果。在 0.2.10 版本的更新之后，我试图采用新版本的 giscus 设置，但在 config 中开启 giscus 设置，并填入参数后，giscus 在所有页面都不显示了。
我不知道是新版本的 bug 还是更新主题过程中可能产生了一些问题，https://github.com/Cyan-Zhou/blog_source_code/tree/master 这是我的博客的源码，其中 /layouts/comment.html 是我用来覆盖主题中的同名文件的，在这个文件的帮助下，giscus 可以正常出现，但不能在特定页面关闭。而如果删除这个文件的话，即便在 config.toml 文件中打开 giscus 并填入参数，博客也不能显示评论区。

### Expected behavior 期待的行为

我没有计算机基础，很多设置都是参考教程手把手学会，慢慢理解的，LoveIt 相关的教程很多也很详细，给我帮到了很多，但是这个问题我尽我所能地检索一个可能地答案也没有找到。不太清楚问题是在更新主题的过程中还是其他地方。希望可以帮助我。

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/105734547/171451334-7a7caad0-1677-4f69-8fdf-0ad4a986233a.png)
localhost模式下，存在 /layouts/comment.html 文件时评论区显示

![image](https://user-images.githubusercontent.com/105734547/171451708-f8a1bf57-c46a-4342-82d0-47f9a9f40cab.png)
而在删除了 /layouts/comment.html 文件后，config.toml 中 giscus 开启的情况下，评论区依旧不显示

### Build Environment 构建环境

- OS: Windows 10
- Theme version/commit 0.2.11
- Hugo version 0.99.1

### Preview Environment 预览环境

- OS: Windows 10
- Browser Chrome

**Comment by xwi88** [comment]
It seems work well, the following links maybe helpful for you:

- https://github.com/xwi88/xwi88.github.io.source
- https://xwi88.com/hugo-plugin-giscus-support/
  - gisscus support notes 
- https://xwi88.com/about/
  -  about md set, comment: false 
- https://xwi88.com/cheat-sheet-docker-related
  - post md set, comment: false

**Comment by Cyan-Zhou** [comment]
@xwi88 Thank you for your answer!
I pushed a new version of my blog source code, by using the default setting of giscus, https://github.com/Cyan-Zhou/blog_source_code/tree/master , please try it again. There isn't comment function at any page, not to mention those pages like `about.md` with `comment: false`. 
I also studied your source code, and I cannot find anything that I can do ( sorry for my poor ability to read codes, I might miss something important). To my understand, if I want to open the giscus comment, all I need to do is to modify the `config.toml` file, and make sure that  `/layouts/comment.html`  has corresponding setting of giscus. Did I miss something? 

As for your tips, they are pretty helpful, for images I put them in `static` dir. And what do you mean "pls not modify the layouts, if no special deal."? Some people say that if I want to make any change that related to changes with files in the `/themes/theme-name/layouts/` , it's better that I copy such files to the `/layouts/` to overwrite the files in themes, they say it's easier to change or update themes in the future. 

Thank you again for your patience.

**Comment by xwi88** [comment]
@Cyan-Zhou 
invalid dir structure, pls ref: https://github.com/xwi88/xwi88.github.io.source
- LoveIt must in dir: **themes/LoveIt**
- some useful script can ref: **https://github.com/xwi88/xwi88.github.io.source/blob/main/Makefile**
  - run some scripts like: _make dev_
  - comment plugin will effect in the production.

**Comment by xwi88** [comment]
@Cyan-Zhou any questions, comments, thks.

**Comment by Cyan-Zhou** [comment]
@xwi88 Awesome, I solve this problem by deleting all files in `public` (except `.git` folder), then run `hugo` . As you said, I tried run `hugo server -w -e production -DF` and it works great, maybe it's because some files need to be regenerated. Thank you!
