### ISSUE TITLE
[BUG] Unable to render collapsible code block

### ISSUE THREAD

**Issue by bharathyes** [dillonzq/LoveIt#688]
### Describe the bug 描述你遇到的错误

Codeblocks enclosed in triple ` doesn't render as collapsible elements with copy button. Instead get a generic codeblock with only highlighting.

Have checked the config.toml but all related to code is present. Unsure of what I am missing here.

### Expected behavior 期待的行为

Expecting collapsible codeblocks with copy button that uses HTML tables to render.

### Screenshots 屏幕截图

Current:
![generic codeblock](https://user-images.githubusercontent.com/4404023/172058151-fa66c458-409e-4024-89e1-0ba46ef4aaf8.png)

Expected:
![image](https://user-images.githubusercontent.com/4404023/172058674-9f81c7bf-2425-4af1-80a6-9133ecc9efc7.png)

### Build Environment 构建环境

- OS: Windows 11
- Theme commit: 5e2fb81e1ce03f3986c719342c351683c38f5998
- Hugo version: 0.98.0

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: Windows 11
- Browser: Chrome

### Additional Information 补充信息

```
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = -1
```

```java
switch(status) {
  case SUBSCRIBER:
    // code block
    break;
  case FREE_TRIAL:
    // code block
    break;
  default:
    // code block
}
```

**Comment by sarathmekala** [comment]
I am also seeing this issue.. @dillonzq can this bug get triaged/prioritized?

**Comment by sarathmekala** [comment]
@bharathyes The solution is provided by @dillonzq here https://github.com/dillonzq/LoveIt/issues/361

**Comment by bharathyes** [comment]
@sarathmekala Worked as expected. Thanks for pointing out (y)
