### ISSUE TITLE
Apostrophe showing weird formatting

### ISSUE THREAD

**Issue by cmpsoares91** [dillonzq/LoveIt#69]
Hello Everyone,

Love the theme, thanks for sharing it with the community. However, I'm getting a small issue that's bugging me. When I use the Apostrophe character in a word composition like `wasn't` I'm expecting it to stay together. However, for some reason the character following the apostrophe is somehow tabbed in its formatting, if I look into the underlying HTML it's correct, but something in the CSS seems to be doing this.

Example/test page: https://www.cmpsoares.com/2020/02/something-comes-soon/

Does anyone know how I can fix this?
Many thanks.

**Comment by jbfreels** [comment]
Are we seeing the same thing?  Here's a screenshot of what I see...
![cmpsoares91](https://user-images.githubusercontent.com/5649291/74588960-296c2800-4fcf-11ea-9ff5-ef50899d4179.png)

**Comment by cmpsoares91** [comment]
Yes, I did the last deploy with the full Hugo command from your readme and it seems OK now. Not sure if it was that.. Thanks!
