### ISSUE TITLE
[BUG] 新人hello word报错，fatal error: pipe failed

### ISSUE THREAD

**Issue by soapffz** [dillonzq/LoveIt#750]
## 操作步骤
```
brew install hugo
hugo new site soapffz_com
cd soapffz_com
git init
git submodule add https://github.com/dillonzq/LoveIt.git themes/LoveIt
cp -rf themes/LoveIt/exampleSite/* ./
vim config.toml

themesDir = "./themes/"

hugo server -D
```

## 报错如下

```
Built in 519 ms
Watching for changes in /Users/soapffz/soapffz_com/{archetypes,assets,content,data,layouts,static,themes}
Watching for config changes in /Users/soapffz/soapffz_com/config.toml, /Users/soapffz/soapffz_com/themes/LoveIt/config.toml
fatal error: pipe failed

goroutine 1 [running]:
runtime.throw({0x1061ee6cf?, 0x1400287e000?})

...
```

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/43143519/192091122-730143d2-6be4-4f61-9f75-170b43b8cdcd.png">

https://app.warp.dev/block/GudscCjGCNbwv5a00eTV4r

## 环境如下

hugo v0.104.0+extended darwin/arm64 BuildDate=unknown
go version go1.18.6 darwin/arm64

新人折腾几个小时已经不想玩了，求助。

**Comment by gouez** [comment]
同样遇到该问题

**Comment by soapffz** [comment]
老哥我已经解决这个问题了，希望能帮到你

这个问题只会在`MacOs`中出现

报错例子：

```
Watching for config changes in /config.toml
fatal error: pipe failed

    goroutine 1 [running]:
    runtime.throw(0x2b42b07, 0xb)
```

问题原因：是`MacOs`的问题而不是`Hugo`或者当前主题的问题，可通过`launchctl limit maxfiles`或者`ulimit -n`命令查看默认限制的文件大小数

解决方案 1：`hugo server --watch=false`，将`观察文件系统的变化并根据需要重新创建`这个选项关闭

解决方案 2：修改 MacOS 最大文件数：`sudo launchctl limit maxfiles 100000 500000`

参考文章：[On upgrade to v0.76.5: fatal error: pipe failed](https://discourse.gohugo.io/t/on-upgrade-to-v0-76-5-fatal-error-pipe-failed/28912/6)
