### ISSUE TITLE
[BUG] 首页不显示文章

### ISSUE THREAD

**Issue by yyt6801** [dillonzq/LoveIt#775]
hugo版本：hugo_extended_0.107.0_windows-amd64  
最新的LoveIt-master，解压至themes文件夹，重命名为LoveIt  
然后在config中添加 theme = "LoveIt"  
hugo new post/first.md  
添加一些内容，修改 draft: false   
hugo server -D
运行首页无法显示文章

**Comment by ah31b32yiub1t1** [comment]
是否為config.toml未配置完全?

可複製官方文檔<2.3 基础配置>之config.toml配置內容使用:

[主题文档 - 基本概念](https://hugoloveit.com/zh-cn/theme-documentation-basics/)

<img width="847" alt="2022-12-06 170403" src="https://user-images.githubusercontent.com/65009307/205867476-94ac1104-6f42-4ae4-8455-11458365b996.png">

**Comment by yyt6801** [comment]
确实是因为config.toml未配置完全，感谢答复
