### ISSUE TITLE
Bad escape sequence in string

### ISSUE THREAD

**Issue by cmpsoares91** [dillonzq/LoveIt#78]
Hello,

I'm using this theme recently for my Hugo blog but in the home page ( https://www.cmpsoares.com ) I keep getting the following error from the google search console: Bad escape sequence in string

I'm quite new to all this scheme.org stuff so could someone enlighten and help me, please?

Kind regards,
Carlos Soares.

**Comment by dillonzq** [comment]
Hi, @cmpsoares91 
For some reason of Hugo, `&` in the content won't be escaped as `&amp;`.
I have fixed `&` of the subtitle in the home page in #79 .
But I can't fix the behavior of `hugo --minify`, which replaces some `&amp;` with `&` leading to the invalid HTML checking.
Could you show more error information from the google search console?

**Comment by cmpsoares91** [comment]
Hello @dillonzq ,

Sorry for the delayed reply.

I've been looking further into it, and it seems that the template or Hugo itself is modifying the string in the page scheme to hexadecimal ASCII and Google says that their scheme parser is unable to parse it... more specifically the error: "Bad escape sequence in string".

So for the apostrophe example: it is expecting `\'` instead of `\x27` and it happens on other similar occasions.

**Comment by cmpsoares91** [comment]
Hello @dillonzq ,

I think I might have a fix for you. But I need to wait for Google's re-index to be sure.
So, I'll keep you posted.

Many thanks,
Carlos Manuel Soares.

**Comment by cmpsoares91** [comment]
Nice thanks! Going to test this version!
