### ISSUE TITLE
[BUG] github action build error

### ISSUE THREAD

**Issue by divazone** [dillonzq/LoveIt#790]
### Describe the bug 描述你遇到的错误

When I push my blog to gitub, it have some problem.

` Liquid Exception: Liquid syntax error (line 1): Variable '{{< style "img { height: 1.25rem; }' was not properly terminated with regexp: /\}\}/ in themes/FixIt/docs/content/about/index.en.md `
 
 I ask some friends using  this themes about this question,but they have never come across something like this before.
 

### Expected behavior 期待的行为

build seccessful

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/3491934/213871428-0361e8f9-82c4-4387-b363-d38f6b1865d0.png)

### Build Environment 构建环境

Themes:latest

### Additional Information 补充信息

main.yml

`name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public`

**Comment by himazawa** [comment]
@divazone how you fixed it?

**Comment by himazawa** [comment]
To solve this issue just create a `.nojekyll` file in the root page of the repo
