### ISSUE TITLE
主页头像不展示

### ISSUE THREAD

**Issue by LyonNee** [dillonzq/LoveIt#808]
编译部署github action，部署在github pages，按照文章的配置文件，头像放在根目录/images目录下并命名avatar.png，加载不出来
gitRepo：https://github.com/[LyonNee/lyonnee.github.io](https://github.com/LyonNee/lyonnee.github.io)
baseUrl：https://lyonnee.github.io/

**Comment by bosswnx** [comment]
你好，我也遇到了这个问题，请问你是怎么解决的呢？

**Comment by bosswnx** [comment]
已收到，谢谢。

**Comment by jiaxiluo** [comment]
@bosswnx @lyonnee 你们是用的哪个版本的hugo出现该问题的，我是0.119.0，怀疑是主题跟最新的hugo框架不兼容呢，

**Comment by codeplayerpro** [comment]
遇到一样的问题，头像不显示。
还有配置的社交链接，只有telegram正常显示，其他都不显示，本地跑正常，部署到GitHub- pages就不显示了
