### ISSUE TITLE
XMPP and Mastodon social don't work

### ISSUE THREAD

**Issue by t404notfound** [dillonzq/LoveIt#81]
Hi, the xmpp and mastodon social doesn't work as intended.
For example, in my config:
```
Mastodon = "@xxxx"
MastodonPrefix = "https://mastodon.technology/"
XMPP = "xxxx@example.com"
```
Instead of showing something like:
`https://mastodon.technology/@xxxx` and `xmpp:xxxx@example.com`

It shows:
`https://mastodon.technology` and `my_blog_address/#ZgotmplZ`

**Comment by dillonzq** [comment]
Hi, @t404notfound 
It has been fixed in #83 .
