### ISSUE TITLE
Various bugs with mobile view when if the website has more than 2 pages.

### ISSUE THREAD

**Issue by t404notfound** [dillonzq/LoveIt#82]
Hi,
I noticed that when my site has two pages ( more than 6 posts) the mobile view has some problems:

* First: In the first page, TypeIt seems to be working fine but when go to page 2, it double some characters which make the subtitle weird.
* Second: This problem is hard to understand so I will make a video for it. Basically, I can move the site from left to right. It should be static, right?

**[Here is the video ](https://streamable.com/tjdpe)**

The exampleSite also has these problems. Just create some more posts to make it second page and you will understand. Sorry if my explanation isn't good.

**Comment by dillonzq** [comment]
Hi, @t404notfound 
Thanks for your explanation, which is enough for me to understand the problem.
The cause of the problem comes from a bug of `.Scratch` in Hugo.
I have fixed it in #84.

**Comment by t404notfound** [comment]
Damn. That was fast. Thank you very much!
