### ISSUE TITLE
国内静态资源CDN

### ISSUE THREAD

**Issue by YuanJ2003** [dillonzq/LoveIt#844]
我使用UNPKG镜像托管了主题的静态资源，作为CDN进行加速，[配置文件](https://jihulab.com/YuanJ2003/YuanJ2003/-/blob/83da998f06f3c6a3ac01a0063c0ea7c6fb33b3b1/themes/LoveIt/assets/data/cdn/npm.yml)
需要的朋友可以使用，主题版本为最新版

**Comment by Jerrysmd** [comment]
Thanks, but the [config file] link is 404 not found.

**Comment by YuanJ2003** [comment]
@Jerrysmd You can get source [there](https://unpkg.com/browse/hieroglyphs-resources@1.0.20/LoveIt/),and you can use faster mirror.

**Comment by Jerrysmd** [comment]
Got it, thanks @YuanJ2003
