### ISSUE TITLE
gitRepo

### ISSUE THREAD

**Issue by x1184** [dillonzq/LoveIt#86]
gitRepo参数填写无效

```
Building sites … ERROR 2020/02/20 16:44:37 Failed to read Git log: fatal: Not a git repository (or any of the parent directories): .git
Total in 450 ms
Error: Error building site: logged 1 error(s)
```
尝试填写服务器.git目录绝对路径相对路径 github的repo路径 皆报错无详细提示

**Comment by dillonzq** [comment]
哈喽， @x1184 
已经在 #108 中修复

**Comment by ron159** [comment]
> 哈喽， @x1184
> 已经在 #108 中修复

依然遇到这样的问题，我是直接在public文件夹 init的.git，然后push到github上部署。但是填写路径依然报同样的错误，没有详情，想问问应该怎么设置，我看您的网站上这个功能是正确的。

**Comment by dillonzq** [comment]
@ron159 
需要在构建网站的目录 init git 而不是 public 目录

**Comment by ron159** [comment]
> @ron159
> 需要在构建网站的目录 init git 而不是 public 目录

感谢，可以了
