### ISSUE TITLE
[BUG] code代码样式不太对

### ISSUE THREAD

**Issue by ZUCCzwp** [dillonzq/LoveIt#873]
### Describe the bug 描述你遇到的错误
代码样式不太对

### Expected behavior 期待的行为

![image](https://github.com/dillonzq/LoveIt/assets/26847647/db022184-7ae1-4d71-b307-8c8daad6f1e7)

### Screenshots 屏幕截图
![image](https://github.com/dillonzq/LoveIt/assets/26847647/ecbc08e9-5ab0-4642-9fa5-b496bea9cf99)

### Build Environment 构建环境

- OS:
- Theme version/commit lovet
- Hugo hugo v0.111.3+extended

**Comment by Croakero** [comment]
我也遇到了，如何解决的这个问题？
