### ISSUE TITLE
Hide awesome icon shortcode text in TOC

### ISSUE THREAD

**Issue by t404notfound** [dillonzq/LoveIt#88]
Hi,
When I use awesome icon in title:
`## :(fab fa-html5): Some title`

The text in Table of Content (TOC) is like this:
`:(fab fa-html5): Some title`
I think the shortcode should be hide from the TOC and only show the title or maybe show the icon as well. I prefer the former solution.
Thank you.

**Comment by dillonzq** [comment]
Hi, @t404notfound 
It has been improved in #92 .
