### ISSUE TITLE
每隔一段时间后，打开博客主页，加载就会很慢，如图（iconfont.min.css）。

### ISSUE THREAD

**Issue by ZhaoqiangCn** [dillonzq/LoveIt#90]
具体表现 ：应该是在加载头像下方动态划出的字幕和bilibili的小图标。
其中 iconfont.min.css 加载了十几秒。
![image](https://user-images.githubusercontent.com/19513914/75012126-52ebee80-54bc-11ea-9eda-18325cb896fd.png)

**Comment by dillonzq** [comment]
哈喽, @ZhaoqiangCn 
这是可以复现的现象吗？

**Comment by ZhaoqiangCn** [comment]
> 可以复现的现象吗？

我把文字效果关闭后就好了，先关闭这个Issue吧
