### ISSUE TITLE
添加不了Valine评论系统

### ISSUE THREAD

**Issue by shenshilei1022** [dillonzq/LoveIt#91]
您好！十分感谢您的hugo主题。有一个问题就是我在config.toml中已经将params.comment的enable和params.comment.valine的enable都设置为true了，valine的appID和appKey都配置好了，还是没有评论系统。望能解答！

**Comment by dillonzq** [comment]
哈喽，@shenshilei1022
在生成文件之前需要设置环境变量 HUGO_ENV=production

**Comment by shenshilei1022** [comment]
感谢您的回复。我在系统添加了环境变量，没有加博文时，在本地建站是正常的，也可以看到环境切换到生产模式![](https://raw.githubusercontent.com/shenshilei1022/hugo_image_resource/master/imgs/%E6%89%B9%E6%B3%A8%202020-02-22%20114155.png)
但是我添加文章之后，就会报下面的错误![](https://raw.githubusercontent.com/shenshilei1022/hugo_image_resource/master/imgs/%E6%89%B9%E6%B3%A8%202020-02-22%20114519.png)
对前端语言不是很了解😭望能解答~

**Comment by dillonzq** [comment]
@shenshilei1022 
请安装最新的 Hugo extended 版本
![image](https://user-images.githubusercontent.com/30786232/75086834-8ccbfc00-5573-11ea-8f8d-3d22949d4b03.png)

**Comment by shenshilei1022** [comment]
十分感谢~

**Comment by 82kg** [comment]
> 十分感谢~

你没好吧？  我发现好像是 valineJS 的问题，博主版本低，加载评论数据是请求 avoscloud.com，
我们应该是请求的另外的地址
avoscloud.com 我们请求不到。导致评论框 不加载
