### ISSUE TITLE
报告一个现象，请大佬看下。

### ISSUE THREAD

**Issue by ZhaoqiangCn** [dillonzq/LoveIt#95]
首页头像下方那一串打字效果的文字（举例：hello world），在第一页显示正常，切换到博客第二页是显示（hheelloo  wwoorrlldd），第三页以此类推。。
不知道是我的设置有问题还是什么问题？
![image](https://user-images.githubusercontent.com/19513914/75127789-08f14b80-56fc-11ea-92db-0b9734b500a5.png)

**Comment by dillonzq** [comment]
哈喽，@ZhaoqiangCn 
这个 bug 即将完整修复
