### ISSUE TITLE
部分数学表达式无法正常显示

### ISSUE THREAD

**Issue by JarvisZL** [dillonzq/LoveIt#98]
实际使用过程中，发现有的表达式无法显示,比如\dfrac{A_{ij}}{x},然而\dfrac{A_i}{x}显示正常。

**Comment by JarvisZL** [comment]
暂时可以通过在front  matter中将 math:true 更改为 markup: mmark来渲染数学公式

**Comment by dillonzq** [comment]
哈喽, @JarvisZL 
最新的版本已经修复了公式的渲染问题，[相关文档](https://hugoloveit.com/zh-cn/theme-documentation-content/#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F) 也已经发布
