### ISSUE TITLE
可否定期发布一个功能相对稳定的release

### ISSUE THREAD

**Issue by LomotHo** [dillonzq/LoveIt#99]
我看master分支已经停留了很久了，是否可以定期发布一个功能相对稳定的release，毕竟每次升级都可能需要修改配置文件，造成配置文件不兼容

**Comment by dillonzq** [comment]
哈喽, @LomotHo 
已经发布了[第一个 release 版本](https://github.com/dillonzq/LoveIt/releases)，之后会稳定更新.
[完整的主题文档](https://hugoloveit.com/zh-cn/categories/documentation/) 也发布了，可以参考
